#!/usr/bin/env python3
"""Export current Lean mainline status into a LaTeX snapshot appendix.

This file is the single source for paper status synchronization.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = ROOT.parent
DEFAULT_OUT = REPO_ROOT / "paper" / "appendix" / "lean_status_snapshot.tex"
ORCHESTRATOR = ROOT / "ACTIVE" / "orchestrator.md"

DEPENDS_RE = re.compile(r"'([^']+)'\s+depends on axioms:\s*\[(.*?)\]", re.S)
MAIN_THEOREM_SIG_RE = re.compile(r"^theorem\s+RH_of_Weil_and_Q3\b")


def run(cmd: list[str], cwd: Path, stdin_text: str | None = None) -> str:
    proc = subprocess.run(
        cmd,
        cwd=cwd,
        input=stdin_text,
        text=True,
        capture_output=True,
        check=False,
    )
    out = (proc.stdout or "") + (proc.stderr or "")
    if proc.returncode != 0:
        raise RuntimeError(f"command failed ({proc.returncode}): {' '.join(cmd)}\n{out}")
    return out


def parse_axiom_blocks(text: str) -> dict[str, list[str]]:
    blocks: dict[str, list[str]] = {}
    for theorem, body in DEPENDS_RE.findall(text):
        items = [x.strip().strip("'") for x in body.replace("\n", " ").split(",")]
        axioms = [x for x in items if x]
        seen: set[str] = set()
        deduped: list[str] = []
        for ax in axioms:
            if ax in seen:
                continue
            seen.add(ax)
            deduped.append(ax)
        blocks[theorem] = deduped
    return blocks


def latex_escape(text: str) -> str:
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(repl.get(ch, ch) for ch in text)


def read_current_status() -> str:
    if not ORCHESTRATOR.exists():
        return "(status line not found)"
    for line in ORCHESTRATOR.read_text(encoding="utf-8").splitlines():
        if line.startswith("**Current status:**"):
            return line.replace("**Current status:**", "").replace("`", "").strip()
    return "(status line not found)"


def read_project_axioms_from_orchestrator() -> list[str]:
    if not ORCHESTRATOR.exists():
        return []
    lines = ORCHESTRATOR.read_text(encoding="utf-8").splitlines()
    capture = False
    out: list[str] = []
    for line in lines:
        if "Текущие узкие project-аксиомы" in line:
            capture = True
            continue
        if capture and line.strip() == "":
            break
        if capture:
            m = re.search(r"`([^`]+)`", line)
            if m:
                out.append(m.group(1))
    seen: set[str] = set()
    uniq: list[str] = []
    for item in out:
        if item in seen:
            continue
        seen.add(item)
        uniq.append(item)
    return uniq


def git_info() -> tuple[str, str]:
    branch = run(["git", "branch", "--show-current"], cwd=REPO_ROOT).strip() or "(detached)"
    commit = run(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT).strip()
    return branch, commit


def read_theorem_signature() -> str:
    main_file = ROOT / "Q3" / "Main.lean"
    if not main_file.exists():
        return "(signature unavailable)"
    for line in main_file.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if MAIN_THEOREM_SIG_RE.match(s):
            s = s.replace(" := by", "")
            s = s.removeprefix("theorem ")
            return f"Q3.Main.{s}"
    return "(signature unavailable)"


def build_snapshot() -> str:
    branch, commit = git_info()
    current_status = read_current_status()
    theorem_sig = read_theorem_signature()

    check_out = run(["lake", "env", "lean", "Q3/CheckAxioms.lean"], cwd=ROOT)
    blocks = parse_axiom_blocks(check_out)
    main_axioms = blocks.get("Q3.Main.RH_of_Weil_and_Q3", [])
    margin_axioms = blocks.get("Q3.prime_term_pathB_tcritical_tau0_brange_thm") or blocks.get(
        "Q3.prime_term_le_at_t_critical_axiom", []
    )

    project_axioms = read_project_axioms_from_orchestrator()

    lines: list[str] = []
    lines.append("% AUTO-GENERATED FILE. DO NOT EDIT BY HAND.")
    lines.append("% Generated by q3.lean.aristotle/scripts/export_paper_status.py")
    lines.append("\\section{Lean Mainline Status Snapshot}")
    lines.append("\\label{app:lean-status-snapshot}")
    lines.append("\\begin{center}")
    lines.append("\\textbf{Auto-generated snapshot (source of truth for status).}")
    lines.append("\\end{center}")
    lines.append("")
    lines.append(f"\\paragraph{{Branch}} \\texttt{{{latex_escape(branch)}}}")
    lines.append(f"\\paragraph{{Commit}} \\texttt{{{latex_escape(commit[:12])}}}")
    lines.append(f"\\paragraph{{Current orchestrator status}} {latex_escape(current_status)}")
    lines.append("")
    lines.append("\\paragraph{Main theorem signature}")
    lines.append(f"\\texttt{{{latex_escape(theorem_sig)}}}")
    lines.append("")
    lines.append("\\paragraph{Axioms used by \\texttt{Q3.Main.RH\\_of\\_Weil\\_and\\_Q3}}")
    lines.append("\\begin{itemize}")
    if main_axioms:
        for ax in main_axioms:
            lines.append(f"  \\item \\texttt{{{latex_escape(ax)}}}")
    else:
        lines.append("  \\item (unavailable)")
    lines.append("\\end{itemize}")
    lines.append("")
    lines.append("\\paragraph{Prime gate dependency snapshot}")
    lines.append("\\begin{itemize}")
    if margin_axioms:
        for ax in margin_axioms:
            lines.append(f"  \\item \\texttt{{{latex_escape(ax)}}}")
    else:
        lines.append("  \\item (unavailable)")
    lines.append("\\end{itemize}")
    lines.append("")
    lines.append("\\paragraph{Project axioms listed in orchestrator}")
    lines.append("\\begin{itemize}")
    if project_axioms:
        for ax in project_axioms:
            lines.append(f"  \\item \\texttt{{{latex_escape(ax)}}}")
    else:
        lines.append("  \\item (not listed)")
    lines.append("\\end{itemize}")
    lines.append("")
    lines.append("\\paragraph{Canonical sources}")
    lines.append("\\begin{itemize}")
    lines.append("  \\item \\texttt{q3.lean.aristotle/Q3/CheckAxioms.lean}")
    lines.append("  \\item \\texttt{q3.lean.aristotle/ACTIVE/orchestrator.md}")
    lines.append("  \\item \\texttt{q3.lean.aristotle/scripts/check\\_axioms.sh}")
    lines.append("\\end{itemize}")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Export Lean status to paper appendix")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Output .tex file path")
    parser.add_argument("--check", action="store_true", help="Check that output file is up-to-date")
    args = parser.parse_args()

    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = (Path.cwd() / out_path).resolve()

    content = build_snapshot()

    if args.check:
        if not out_path.exists():
            print(f"snapshot missing: {out_path}", file=sys.stderr)
            return 1
        existing = out_path.read_text(encoding="utf-8")
        if existing != content:
            print(f"snapshot drift detected: {out_path}", file=sys.stderr)
            return 1
        print(f"snapshot up-to-date: {out_path}")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"wrote snapshot: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
