#!/usr/bin/env python3
import datetime as _dt
import sqlite3
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
DB_PATH = ROOT / "aristotle_db" / "aristotle_proofs.db"

TARGET_DOCS = [
    "A3_FLOOR_v3",
    "A3_FLOOR_v6",
    "A3_FLOOR_v8",
    "A3_FLOOR_v16",
    "A3_FLOOR_v19",
    "A3_FLOOR_v20_core",
    "A3_FLOOR_v20_manual",
    "A3_FLOOR_v21_manual",
    "A3_FLOOR_v22_stage4",
    "A3_FLOOR_THEOREM",
    "Q3_DigammaRemainder",
]

TARGET_FILES = [
    ROOT / "PROOF_MAP_NEW_KERNEL.md",
    ROOT / "A3_FLOOR_ROADMAP.md",
    ROOT / "PROJECT_ASCII.md",
]

BEGIN_MARK = "<!-- AUTO-STATUS:BEGIN -->"
END_MARK = "<!-- AUTO-STATUS:END -->"


def _fetch_docs(conn: sqlite3.Connection, doc_ids: Iterable[str]) -> list[dict]:
    cur = conn.cursor()
    rows = []
    for doc_id in doc_ids:
        cur.execute(
            "SELECT doc_id, status, lines, path FROM docs WHERE doc_id = ?",
            (doc_id,),
        )
        row = cur.fetchone()
        if row:
            rows.append(
                {
                    "doc_id": row[0],
                    "status": row[1],
                    "lines": row[2],
                    "path": row[3],
                }
            )
        else:
            rows.append(
                {
                    "doc_id": doc_id,
                    "status": "missing",
                    "lines": 0,
                    "path": "(not in DB)",
                }
            )
    return rows


def _render_block(rows: list[dict]) -> str:
    now = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    status_counts = {}
    for row in rows:
        status_counts[row["status"]] = status_counts.get(row["status"], 0) + 1

    lines = [
        BEGIN_MARK,
        "Auto status (DB snapshot): " + now,
        "",
        "Doc status (A3_FLOOR + Q3_DigammaRemainder):",
        "| doc_id | status | lines |",
        "| --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| {row['doc_id']} | {row['status']} | {row['lines']} |"
        )
    lines.append("")
    lines.append(
        "Counts: "
        + ", ".join(f"{k}={v}" for k, v in sorted(status_counts.items()))
    )
    lines.append("Generated by scripts/update_status.py")
    lines.append(END_MARK)
    return "\n".join(lines) + "\n"


def _replace_block(text: str, block: str) -> str:
    if BEGIN_MARK in text and END_MARK in text:
        pre = text.split(BEGIN_MARK)[0]
        post = text.split(END_MARK)[1]
        return pre + block + post.lstrip("\n")
    return text.rstrip("\n") + "\n\n" + block


def main() -> int:
    if not DB_PATH.exists():
        raise SystemExit(f"DB not found: {DB_PATH}")

    conn = sqlite3.connect(DB_PATH)
    try:
        rows = _fetch_docs(conn, TARGET_DOCS)
    finally:
        conn.close()

    block = _render_block(rows)
    for path in TARGET_FILES:
        if not path.exists():
            raise SystemExit(f"Target file missing: {path}")
        text = path.read_text(encoding="utf-8")
        new_text = _replace_block(text, block)
        if new_text != text:
            path.write_text(new_text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
