import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk0Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk1Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk2Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk3Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk4Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk5Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk6Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk7Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk8Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk9Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk10Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk11Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk12Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk13Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk14Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk15Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk16Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk17Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk18Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk19Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk20Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk21Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk22Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk23Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk24Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk25Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk26Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk27Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk28Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk29Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk30Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk31Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk32Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk33Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk34Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk35Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk36Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk37Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk38Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk39Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk40Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk41Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk42Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk43Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk44Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk45Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk46Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk47Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk48Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk49Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk50Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk51Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk52Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk53Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk54Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk55Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk56Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk57Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk58Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk59Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk60Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk61Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk62Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk63Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk64Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk65Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk66Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk67Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk68Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk69Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk70Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk71Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk72Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk73Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk74Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk75Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk76Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk77Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk78Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk79Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk80Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk81Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk82Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk83Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk84Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk85Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk86Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk87Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk88Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk89Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk90Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk91Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk92Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk93Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk94Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk95Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk96Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusChunk97Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk0Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk1Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk2Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk3Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk4Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk5Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk6Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk7Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk8Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk9Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk10Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk11Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk12Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk13Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk14Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk15Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk16Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk17Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk18Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk19Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk20Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk21Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk22Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk23Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk24Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk25Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk26Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk27Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk28Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk29Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk30Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk31Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk32Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk33Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk34Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk35Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk36Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk37Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk38Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk39Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk40Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk41Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk42Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk43Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk44Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk45Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk46Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk47Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk48Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk49Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk50Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk51Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk52Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk53Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk54Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk55Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk56Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk57Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk58Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk59Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk60Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk61Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk62Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk63Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk64Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk65Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk66Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk67Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk68Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk69Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk70Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk71Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk72Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk73Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk74Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk75Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk76Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk77Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk78Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk79Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk80Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk81Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk82Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk83Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk84Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk85Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk86Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk87Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk88Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk89Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk90Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk91Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk92Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk93Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk94Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk95Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk96Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryPlusZeroChunk97Import

set_option linter.mathlibStandardSet false
set_option maxHeartbeats 0

/-!
Generated Step33A.1 option-B primaryK11 split-`R` plus-side
zero-off-declared support wrapper.
-/

noncomputable section

open scoped BigOperators

namespace Q3
namespace PSDpd
namespace CenteredCoeffPrimeDeltaLiveRationalPayloadImport

open CenteredCoeffPayloadImport
open CenteredCoeffDictionaryImport
open CenteredCoeffBaseHboxImport
open CenteredCoeffAnalyticP0Import
open CenteredCoeffPrimeEntryHboxImport
open CenteredCoeffPrimeDeltaLivePayloadImport
open CenteredCoeffPrimePositivePartTightImport
open CenteredCoeffEntryHboxImport

/-- Generated primaryK11 RPlus zero-off-declared support fact.
Each index theorem is checked in a small chunk module; this wrapper
only dispatches by the finite active-shift index. -/
theorem primaryK11RationalDeltaLiveRPlusZeroOffDeclaredByDelta_generated :
    primaryK11RationalDeltaLiveRPlusZeroOffDeclaredByDelta := by
  intro δInt n hδ hnot
  fin_cases n
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx0 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx1 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx2 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx3 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx4 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx5 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx6 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx7 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx8 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx9 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx10 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx11 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx12 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx13 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx14 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx15 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx16 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx17 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx18 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx19 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx20 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx21 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx22 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx23 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx24 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx25 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx26 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx27 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx28 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx29 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx30 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx31 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx32 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx33 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx34 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx35 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx36 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx37 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx38 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx39 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx40 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx41 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx42 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx43 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx44 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx45 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx46 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx47 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx48 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx49 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx50 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx51 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx52 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx53 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx54 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx55 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx56 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx57 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx58 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx59 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx60 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx61 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx62 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx63 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx64 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx65 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx66 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx67 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx68 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx69 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx70 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx71 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx72 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx73 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx74 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx75 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx76 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx77 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx78 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx79 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx80 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx81 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx82 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx83 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx84 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx85 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx86 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx87 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx88 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx89 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx90 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx91 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx92 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx93 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx94 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx95 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx96 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRPlusZeroOffDeclared_idx97 δInt hδ hnot

/-- Generated primaryK11 RPlus declared-support hbox fact.
Each active-shift index theorem is checked in a small chunk module; this
wrapper dispatches by the finite active-shift index. -/
theorem primaryK11RationalDeltaLiveRPlusHboxOnDeclaredByDelta_generated :
    primaryK11RationalDeltaLiveRPlusHboxOnDeclaredByDelta := by
  intro δInt n hδ hmem
  fin_cases n
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx0 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx1 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx2 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx3 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx4 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx5 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx6 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx7 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx8 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx9 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx10 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx11 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx12 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx13 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx14 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx15 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx16 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx17 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx18 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx19 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx20 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx21 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx22 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx23 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx24 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx25 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx26 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx27 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx28 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx29 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx30 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx31 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx32 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx33 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx34 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx35 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx36 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx37 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx38 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx39 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx40 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx41 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx42 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx43 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx44 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx45 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx46 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx47 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx48 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx49 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx50 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx51 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx52 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx53 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx54 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx55 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx56 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx57 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx58 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx59 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx60 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx61 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx62 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx63 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx64 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx65 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx66 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx67 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx68 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx69 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx70 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx71 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx72 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx73 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx74 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx75 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx76 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx77 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx78 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx79 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx80 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx81 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx82 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx83 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx84 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx85 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx86 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx87 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx88 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx89 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx90 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx91 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx92 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx93 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx94 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx95 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx96 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRPlusHboxDeclared_idx97 δInt hδ hmem

end CenteredCoeffPrimeDeltaLiveRationalPayloadImport
end PSDpd
end Q3
