import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk0Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk1Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk2Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk3Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk4Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk5Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk6Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk7Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk8Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk9Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk10Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk11Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk12Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk13Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk14Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk15Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk16Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk17Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk18Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk19Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk20Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk21Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk22Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk23Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk24Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk25Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk26Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk27Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk28Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk29Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk30Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk31Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk32Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk33Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk34Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk35Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk36Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk37Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk38Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk39Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk40Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk41Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk42Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk43Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk44Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk45Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk46Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk47Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk48Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk49Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk50Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk51Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk52Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk53Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk54Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk55Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk56Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk57Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk58Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk59Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk60Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk61Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk62Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk63Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk64Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk65Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk66Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk67Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk68Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk69Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk70Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk71Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk72Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk73Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk74Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk75Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk76Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk77Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk78Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk79Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk80Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk81Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk82Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk83Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk84Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk85Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk86Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk87Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk88Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk89Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk90Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk91Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk92Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk93Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk94Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk95Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk96Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusChunk97Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk0Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk1Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk2Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk3Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk4Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk5Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk6Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk7Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk8Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk9Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk10Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk11Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk12Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk13Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk14Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk15Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk16Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk17Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk18Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk19Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk20Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk21Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk22Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk23Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk24Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk25Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk26Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk27Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk28Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk29Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk30Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk31Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk32Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk33Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk34Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk35Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk36Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk37Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk38Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk39Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk40Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk41Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk42Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk43Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk44Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk45Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk46Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk47Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk48Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk49Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk50Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk51Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk52Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk53Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk54Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk55Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk56Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk57Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk58Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk59Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk60Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk61Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk62Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk63Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk64Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk65Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk66Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk67Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk68Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk69Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk70Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk71Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk72Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk73Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk74Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk75Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk76Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk77Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk78Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk79Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk80Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk81Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk82Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk83Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk84Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk85Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk86Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk87Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk88Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk89Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk90Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk91Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk92Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk93Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk94Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk95Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk96Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlPlusZeroChunk97Import

set_option linter.mathlibStandardSet false
set_option maxHeartbeats 0

/-!
Generated Step33A.1 option-B controlK9 split-`R` plus-side
zero-off-declared support wrapper.
-/

noncomputable section

open scoped BigOperators

namespace Q3
namespace PSDpd
namespace CenteredCoeffPrimeDeltaLiveRationalPayloadImport

open CenteredCoeffPayloadImport
open CenteredCoeffDictionaryImport
open CenteredCoeffBaseHboxImport
open CenteredCoeffAnalyticP0Import
open CenteredCoeffPrimeEntryHboxImport
open CenteredCoeffPrimeDeltaLivePayloadImport
open CenteredCoeffPrimePositivePartTightImport
open CenteredCoeffEntryHboxImport

/-- Generated controlK9 RPlus zero-off-declared support fact.
Each index theorem is checked in a small chunk module; this wrapper
only dispatches by the finite active-shift index. -/
theorem controlK9RationalDeltaLiveRPlusZeroOffDeclaredByDelta_generated :
    controlK9RationalDeltaLiveRPlusZeroOffDeclaredByDelta := by
  intro δInt n hδ hnot
  fin_cases n
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx0 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx1 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx2 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx3 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx4 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx5 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx6 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx7 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx8 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx9 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx10 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx11 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx12 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx13 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx14 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx15 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx16 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx17 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx18 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx19 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx20 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx21 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx22 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx23 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx24 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx25 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx26 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx27 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx28 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx29 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx30 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx31 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx32 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx33 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx34 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx35 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx36 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx37 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx38 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx39 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx40 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx41 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx42 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx43 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx44 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx45 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx46 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx47 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx48 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx49 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx50 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx51 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx52 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx53 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx54 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx55 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx56 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx57 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx58 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx59 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx60 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx61 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx62 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx63 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx64 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx65 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx66 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx67 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx68 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx69 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx70 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx71 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx72 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx73 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx74 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx75 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx76 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx77 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx78 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx79 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx80 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx81 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx82 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx83 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx84 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx85 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx86 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx87 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx88 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx89 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx90 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx91 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx92 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx93 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx94 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx95 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx96 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRPlusZeroOffDeclared_idx97 δInt hδ hnot

/-- Generated controlK9 RPlus declared-support hbox fact.
Each active-shift index theorem is checked in a small chunk module; this
wrapper dispatches by the finite active-shift index. -/
theorem controlK9RationalDeltaLiveRPlusHboxOnDeclaredByDelta_generated :
    controlK9RationalDeltaLiveRPlusHboxOnDeclaredByDelta := by
  intro δInt n hδ hmem
  fin_cases n
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx0 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx1 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx2 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx3 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx4 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx5 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx6 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx7 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx8 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx9 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx10 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx11 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx12 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx13 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx14 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx15 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx16 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx17 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx18 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx19 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx20 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx21 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx22 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx23 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx24 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx25 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx26 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx27 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx28 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx29 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx30 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx31 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx32 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx33 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx34 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx35 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx36 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx37 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx38 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx39 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx40 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx41 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx42 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx43 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx44 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx45 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx46 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx47 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx48 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx49 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx50 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx51 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx52 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx53 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx54 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx55 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx56 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx57 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx58 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx59 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx60 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx61 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx62 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx63 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx64 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx65 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx66 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx67 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx68 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx69 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx70 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx71 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx72 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx73 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx74 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx75 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx76 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx77 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx78 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx79 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx80 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx81 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx82 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx83 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx84 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx85 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx86 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx87 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx88 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx89 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx90 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx91 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx92 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx93 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx94 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx95 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx96 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRPlusHboxDeclared_idx97 δInt hδ hmem

end CenteredCoeffPrimeDeltaLiveRationalPayloadImport
end PSDpd
end Q3
