import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk0Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk1Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk2Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk3Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk4Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk5Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk6Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk7Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk8Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk9Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk10Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk11Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk12Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk13Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk14Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk15Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk16Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk17Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk18Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk19Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk20Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk21Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk22Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk23Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk24Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk25Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk26Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk27Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk28Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk29Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk30Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk31Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk32Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk33Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk34Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk35Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk36Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk37Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk38Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk39Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk40Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk41Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk42Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk43Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk44Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk45Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk46Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk47Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk48Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk49Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk50Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk51Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk52Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk53Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk54Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk55Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk56Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk57Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk58Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk59Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk60Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk61Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk62Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk63Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk64Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk65Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk66Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk67Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk68Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk69Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk70Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk71Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk72Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk73Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk74Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk75Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk76Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk77Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk78Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk79Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk80Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk81Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk82Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk83Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk84Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk85Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk86Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk87Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk88Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk89Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk90Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk91Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk92Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk93Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk94Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk95Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk96Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusChunk97Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk0Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk1Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk2Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk3Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk4Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk5Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk6Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk7Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk8Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk9Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk10Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk11Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk12Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk13Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk14Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk15Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk16Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk17Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk18Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk19Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk20Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk21Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk22Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk23Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk24Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk25Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk26Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk27Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk28Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk29Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk30Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk31Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk32Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk33Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk34Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk35Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk36Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk37Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk38Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk39Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk40Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk41Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk42Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk43Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk44Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk45Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk46Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk47Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk48Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk49Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk50Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk51Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk52Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk53Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk54Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk55Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk56Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk57Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk58Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk59Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk60Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk61Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk62Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk63Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk64Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk65Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk66Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk67Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk68Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk69Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk70Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk71Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk72Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk73Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk74Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk75Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk76Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk77Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk78Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk79Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk80Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk81Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk82Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk83Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk84Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk85Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk86Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk87Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk88Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk89Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk90Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk91Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk92Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk93Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk94Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk95Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk96Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportPrimaryMinusZeroChunk97Import

set_option linter.mathlibStandardSet false
set_option maxHeartbeats 0

/-!
Generated Step33A.1 option-B primaryK11 split-`R` minus-side
zero-off-declared support wrapper.
-/

noncomputable section

open scoped BigOperators

namespace Q3
namespace PSDpd
namespace CenteredCoeffPrimeDeltaLiveRationalPayloadImport

open CenteredCoeffPayloadImport
open CenteredCoeffDictionaryImport
open CenteredCoeffBaseHboxImport
open CenteredCoeffAnalyticP0Import
open CenteredCoeffPrimeEntryHboxImport
open CenteredCoeffPrimeDeltaLivePayloadImport
open CenteredCoeffPrimePositivePartTightImport
open CenteredCoeffEntryHboxImport

/-- Generated primaryK11 RMinus zero-off-declared support fact.
Each index theorem is checked in a small chunk module; this wrapper
only dispatches by the finite active-shift index. -/
theorem primaryK11RationalDeltaLiveRMinusZeroOffDeclaredByDelta_generated :
    primaryK11RationalDeltaLiveRMinusZeroOffDeclaredByDelta := by
  intro δInt n hδ hnot
  fin_cases n
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx0 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx1 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx2 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx3 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx4 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx5 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx6 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx7 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx8 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx9 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx10 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx11 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx12 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx13 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx14 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx15 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx16 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx17 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx18 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx19 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx20 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx21 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx22 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx23 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx24 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx25 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx26 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx27 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx28 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx29 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx30 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx31 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx32 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx33 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx34 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx35 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx36 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx37 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx38 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx39 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx40 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx41 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx42 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx43 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx44 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx45 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx46 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx47 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx48 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx49 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx50 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx51 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx52 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx53 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx54 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx55 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx56 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx57 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx58 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx59 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx60 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx61 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx62 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx63 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx64 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx65 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx66 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx67 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx68 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx69 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx70 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx71 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx72 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx73 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx74 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx75 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx76 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx77 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx78 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx79 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx80 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx81 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx82 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx83 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx84 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx85 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx86 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx87 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx88 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx89 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx90 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx91 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx92 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx93 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx94 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx95 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx96 δInt hδ hnot
  · exact primaryK11RationalDeltaLiveRMinusZeroOffDeclared_idx97 δInt hδ hnot

/-- Generated primaryK11 RMinus declared-support hbox fact.
Each active-shift index theorem is checked in a small chunk module; this
wrapper dispatches by the finite active-shift index. -/
theorem primaryK11RationalDeltaLiveRMinusHboxOnDeclaredByDelta_generated :
    primaryK11RationalDeltaLiveRMinusHboxOnDeclaredByDelta := by
  intro δInt n hδ hmem
  fin_cases n
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx0 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx1 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx2 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx3 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx4 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx5 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx6 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx7 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx8 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx9 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx10 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx11 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx12 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx13 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx14 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx15 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx16 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx17 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx18 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx19 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx20 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx21 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx22 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx23 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx24 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx25 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx26 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx27 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx28 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx29 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx30 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx31 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx32 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx33 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx34 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx35 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx36 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx37 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx38 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx39 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx40 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx41 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx42 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx43 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx44 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx45 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx46 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx47 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx48 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx49 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx50 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx51 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx52 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx53 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx54 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx55 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx56 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx57 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx58 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx59 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx60 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx61 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx62 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx63 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx64 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx65 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx66 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx67 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx68 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx69 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx70 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx71 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx72 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx73 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx74 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx75 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx76 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx77 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx78 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx79 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx80 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx81 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx82 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx83 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx84 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx85 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx86 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx87 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx88 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx89 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx90 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx91 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx92 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx93 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx94 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx95 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx96 δInt hδ hmem
  · exact primaryK11RationalDeltaLiveRMinusHboxDeclared_idx97 δInt hδ hmem

end CenteredCoeffPrimeDeltaLiveRationalPayloadImport
end PSDpd
end Q3
