import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk0Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk1Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk2Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk3Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk4Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk5Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk6Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk7Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk8Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk9Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk10Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk11Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk12Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk13Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk14Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk15Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk16Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk17Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk18Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk19Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk20Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk21Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk22Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk23Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk24Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk25Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk26Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk27Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk28Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk29Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk30Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk31Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk32Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk33Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk34Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk35Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk36Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk37Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk38Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk39Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk40Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk41Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk42Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk43Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk44Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk45Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk46Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk47Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk48Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk49Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk50Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk51Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk52Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk53Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk54Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk55Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk56Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk57Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk58Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk59Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk60Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk61Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk62Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk63Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk64Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk65Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk66Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk67Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk68Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk69Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk70Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk71Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk72Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk73Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk74Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk75Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk76Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk77Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk78Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk79Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk80Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk81Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk82Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk83Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk84Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk85Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk86Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk87Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk88Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk89Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk90Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk91Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk92Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk93Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk94Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk95Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk96Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusChunk97Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk0Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk1Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk2Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk3Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk4Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk5Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk6Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk7Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk8Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk9Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk10Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk11Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk12Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk13Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk14Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk15Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk16Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk17Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk18Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk19Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk20Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk21Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk22Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk23Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk24Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk25Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk26Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk27Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk28Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk29Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk30Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk31Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk32Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk33Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk34Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk35Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk36Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk37Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk38Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk39Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk40Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk41Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk42Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk43Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk44Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk45Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk46Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk47Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk48Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk49Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk50Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk51Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk52Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk53Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk54Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk55Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk56Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk57Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk58Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk59Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk60Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk61Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk62Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk63Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk64Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk65Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk66Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk67Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk68Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk69Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk70Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk71Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk72Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk73Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk74Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk75Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk76Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk77Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk78Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk79Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk80Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk81Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk82Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk83Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk84Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk85Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk86Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk87Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk88Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk89Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk90Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk91Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk92Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk93Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk94Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk95Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk96Import
import Q3.Proofs.PSD_CenteredCoeffPrimeDeltaLiveRationalSupportControlMinusZeroChunk97Import

set_option linter.mathlibStandardSet false
set_option maxHeartbeats 0

/-!
Generated Step33A.1 option-B controlK9 split-`R` minus-side
zero-off-declared support wrapper.
-/

noncomputable section

open scoped BigOperators

namespace Q3
namespace PSDpd
namespace CenteredCoeffPrimeDeltaLiveRationalPayloadImport

open CenteredCoeffPayloadImport
open CenteredCoeffDictionaryImport
open CenteredCoeffBaseHboxImport
open CenteredCoeffAnalyticP0Import
open CenteredCoeffPrimeEntryHboxImport
open CenteredCoeffPrimeDeltaLivePayloadImport
open CenteredCoeffPrimePositivePartTightImport
open CenteredCoeffEntryHboxImport

/-- Generated controlK9 RMinus zero-off-declared support fact.
Each index theorem is checked in a small chunk module; this wrapper
only dispatches by the finite active-shift index. -/
theorem controlK9RationalDeltaLiveRMinusZeroOffDeclaredByDelta_generated :
    controlK9RationalDeltaLiveRMinusZeroOffDeclaredByDelta := by
  intro δInt n hδ hnot
  fin_cases n
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx0 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx1 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx2 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx3 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx4 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx5 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx6 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx7 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx8 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx9 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx10 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx11 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx12 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx13 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx14 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx15 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx16 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx17 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx18 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx19 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx20 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx21 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx22 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx23 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx24 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx25 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx26 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx27 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx28 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx29 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx30 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx31 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx32 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx33 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx34 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx35 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx36 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx37 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx38 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx39 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx40 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx41 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx42 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx43 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx44 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx45 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx46 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx47 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx48 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx49 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx50 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx51 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx52 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx53 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx54 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx55 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx56 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx57 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx58 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx59 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx60 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx61 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx62 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx63 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx64 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx65 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx66 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx67 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx68 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx69 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx70 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx71 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx72 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx73 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx74 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx75 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx76 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx77 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx78 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx79 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx80 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx81 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx82 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx83 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx84 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx85 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx86 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx87 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx88 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx89 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx90 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx91 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx92 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx93 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx94 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx95 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx96 δInt hδ hnot
  · exact controlK9RationalDeltaLiveRMinusZeroOffDeclared_idx97 δInt hδ hnot

/-- Generated controlK9 RMinus declared-support hbox fact.
Each active-shift index theorem is checked in a small chunk module; this
wrapper dispatches by the finite active-shift index. -/
theorem controlK9RationalDeltaLiveRMinusHboxOnDeclaredByDelta_generated :
    controlK9RationalDeltaLiveRMinusHboxOnDeclaredByDelta := by
  intro δInt n hδ hmem
  fin_cases n
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx0 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx1 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx2 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx3 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx4 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx5 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx6 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx7 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx8 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx9 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx10 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx11 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx12 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx13 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx14 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx15 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx16 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx17 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx18 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx19 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx20 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx21 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx22 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx23 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx24 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx25 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx26 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx27 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx28 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx29 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx30 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx31 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx32 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx33 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx34 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx35 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx36 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx37 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx38 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx39 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx40 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx41 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx42 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx43 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx44 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx45 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx46 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx47 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx48 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx49 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx50 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx51 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx52 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx53 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx54 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx55 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx56 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx57 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx58 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx59 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx60 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx61 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx62 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx63 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx64 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx65 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx66 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx67 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx68 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx69 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx70 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx71 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx72 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx73 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx74 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx75 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx76 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx77 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx78 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx79 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx80 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx81 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx82 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx83 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx84 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx85 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx86 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx87 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx88 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx89 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx90 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx91 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx92 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx93 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx94 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx95 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx96 δInt hδ hmem
  · exact controlK9RationalDeltaLiveRMinusHboxDeclared_idx97 δInt hδ hmem

end CenteredCoeffPrimeDeltaLiveRationalPayloadImport
end PSDpd
end Q3
