import Q3.Basic.WeilSquareClass

set_option linter.mathlibStandardSet false

open scoped Real

noncomputable section

namespace Q3

/-!
# Direct Weil-route gates

This file records the exact logical shape of the direct Weil route.
It deliberately separates the known equivalence interface from the unknown
global Weil positivity problem.

No density, global positivity, or RH proof is claimed here.
-/

/-- Generator support before squaring: the half-window whose square convolution
lands in `[-K,K]`. -/
def GeneratorSupportedInHalfWindow (K : ℝ) (g : ℝ → ℂ) : Prop :=
  Function.support g ⊆ Set.Icc (-(K / 2)) (K / 2)

/-- Additive-log generator class for the direct Weil route.  The exact
multiplicative-to-additive normalization is a separate interface gate; this
definition records the additive support and two boundary-null constraints. -/
def AdmissibleGenerator (K : ℝ) (g : ℝ → ℂ) : Prop :=
  SmoothCompactGenerator g ∧
    GeneratorSupportedInHalfWindow K g ∧
      HasWeilBoundaryNull g

/-- The Weil square generated by `g`. -/
abbrev WeilGeneratorSquare (g : ℝ → ℂ) : ℝ → ℝ :=
  hermitianSquare g

/-- The Weil functional evaluated on the square generated by `g`. -/
abbrev WeilGeneratorForm (g : ℝ → ℂ) : ℝ :=
  WeilForm (WeilGeneratorSquare g)

/-- Local positivity on the exact square class.  This is the unknown part of the
RH route, not a theorem. -/
def LocalWeilSquarePositivity (K : ℝ) : Prop :=
  ∀ Φ ∈ W_sq_K K, 0 ≤ WeilForm Φ

/-- Global positivity on the exact square class.  This is equivalent to RH once
the exact Weil criterion is supplied. -/
def GlobalWeilPositivity : Prop :=
  ∀ Φ ∈ W_sq, 0 ≤ WeilForm Φ

/-- Local positivity for all windows implies global positivity by unpacking the
window witness in `W_sq`. -/
theorem global_weil_positivity_of_local
    (hlocal : ∀ K : ℝ, LocalWeilSquarePositivity K) :
    GlobalWeilPositivity := by
  intro Φ hΦ
  rcases hΦ with ⟨K, -, hΦK⟩
  exact hlocal K Φ hΦK

/-- Direct use of the exact Weil criterion: after global Weil positivity, RH is
immediate.  The hard hypothesis is `GlobalWeilPositivity`. -/
theorem RH_of_global_weil_positivity
    (hcriterion : ExactWeilCriterion)
    (hpositive : GlobalWeilPositivity) :
    RH :=
  hcriterion.mpr hpositive

/-- The precise result that replaces the missing geometric sign theorem.  This
is only a name for the target positivity statement; no positivity is asserted
here. -/
abbrev WeilGeometricSignReplacement : Prop :=
  GlobalWeilPositivity

/-- If the synthetic sign theorem is supplied, the exact Weil criterion exports
RH.  The proof is just the criterion direction; the sign theorem remains the
hard independent input. -/
theorem RH_of_weil_geometric_sign_replacement
    (hcriterion : ExactWeilCriterion)
    (hsign : WeilGeometricSignReplacement) :
    RH :=
  RH_of_global_weil_positivity hcriterion hsign

/-- A finite packet model used to attack a fixed window.  The same object must
carry both the analytic generator and the finite quadratic form; otherwise PSD
certificates may prove positivity for the wrong form. -/
structure FinitePacketWeilModel (K : ℝ) (ι : Type*) where
  synth : (ι → ℝ) → ℝ → ℂ
  packetForm : (ι → ℝ) → ℝ
  analyticBoundary : (ι → ℝ) → Prop
  matrixBoundary : (ι → ℝ) → Prop

namespace FinitePacketWeilModel

variable {K : ℝ} {ι : Type*} (M : FinitePacketWeilModel K ι)

/-- Gate 1 for packet positivity: the finite form is exactly the Weil form of
the synthesized Hermitian square on analytically boundary-null vectors. -/
def ExactPacketQuadraticIdentity : Prop :=
  ∀ v : ι → ℝ, M.analyticBoundary v →
    WeilGeneratorForm (M.synth v) = M.packetForm v

/-- Gate 2: analytic boundary vanishing implies the matrix boundary predicate
used by finite PSD certificates. -/
def AnalyticBoundaryToMatrixBoundary : Prop :=
  ∀ v : ι → ℝ, M.analyticBoundary v → M.matrixBoundary v

/-- Gate 3: the finite quadratic form is PSD on the matrix boundary-null
subspace. -/
def PacketPSDOnBoundary : Prop :=
  ∀ v : ι → ℝ, M.matrixBoundary v → 0 ≤ M.packetForm v

/-- A complete finite packet certificate for one model/window. -/
structure Certificate where
  exact_identity : M.ExactPacketQuadraticIdentity
  boundary_transfer : M.AnalyticBoundaryToMatrixBoundary
  packet_psd : M.PacketPSDOnBoundary

/-- A finite certificate gives nonnegativity only for synthesized packet
generators satisfying the analytic boundary predicate. -/
theorem packet_generator_nonneg_of_certificate
    (cert : M.Certificate) (v : ι → ℝ) (hv : M.analyticBoundary v) :
    0 ≤ WeilGeneratorForm (M.synth v) := by
  rw [cert.exact_identity v hv]
  exact cert.packet_psd v (cert.boundary_transfer v hv)

end FinitePacketWeilModel

/-- Finite synthetic candidate for the missing intersection form.  The intended
reading is `C = A_arch - P_prime`, but this structure is intentionally abstract:
the exact analytic identification with the Weil form is a separate gate. -/
structure FiniteSyntheticIntersectionModel (K : ℝ) (ι : Type*) where
  synth : (ι → ℝ) → ℝ → ℂ
  archForm : (ι → ℝ) → ℝ
  primeForm : (ι → ℝ) → ℝ
  cForm : (ι → ℝ) → ℝ
  analyticBoundary : (ι → ℝ) → Prop
  matrixBoundary : (ι → ℝ) → Prop
  c_eq_arch_sub_prime : ∀ v : ι → ℝ, cForm v = archForm v - primeForm v

namespace FiniteSyntheticIntersectionModel

variable {K : ℝ} {ι : Type*} (M : FiniteSyntheticIntersectionModel K ι)

/-- First mandatory check: the synthetic `C`-form is the exact Weil form of the
generated Hermitian square on admissible vectors. -/
def ExactWeilCIdentity : Prop :=
  ∀ v : ι → ℝ, M.analyticBoundary v →
    WeilGeneratorForm (M.synth v) = M.cForm v

/-- Second mandatory check: the analytic boundary-null condition implies the
finite matrix boundary condition used by the PSD certificate. -/
def AnalyticBoundaryToMatrixBoundary : Prop :=
  ∀ v : ι → ℝ, M.analyticBoundary v → M.matrixBoundary v

/-- Third mandatory check: the synthetic `C`-form is PSD on the finite
boundary-null subspace. -/
def CPSDOnBoundary : Prop :=
  ∀ v : ι → ℝ, M.matrixBoundary v → 0 ≤ M.cForm v

/-- Complete finite sign certificate for one synthetic intersection model. -/
structure Certificate where
  exact_weil_identity : M.ExactWeilCIdentity
  boundary_transfer : M.AnalyticBoundaryToMatrixBoundary
  c_psd : M.CPSDOnBoundary

/-- A finite synthetic intersection certificate gives nonnegativity only for
the generated Hermitian squares in that finite admissible model. -/
theorem generator_nonneg_of_certificate
    (cert : M.Certificate) (v : ι → ℝ) (hv : M.analyticBoundary v) :
    0 ≤ WeilGeneratorForm (M.synth v) := by
  rw [cert.exact_weil_identity v hv]
  exact cert.c_psd v (cert.boundary_transfer v hv)

end FiniteSyntheticIntersectionModel

/-- Density gate for a fixed window: packet squares approximate every exact
square in the selected window topology.  This is a target statement, not a
claim. -/
def BoundaryNullPacketSquareDensity (K : ℝ) : Prop :=
  ∀ Φ ∈ W_sq_K K, ∃ Φn : ℕ → ℝ → ℝ,
    (∀ n, Φn n ∈ W_sq_K K) ∧
      UniformOnWindowTendsto K Φn Φ

/-- The four independent gates needed before finite packet PSD can be promoted
to the full exact Weil-square class. -/
structure WeilDirectRouteGates where
  exact_interface : ExactWeilCriterion
  local_packet_density : ∀ K : ℝ, BoundaryNullPacketSquareDensity K
  local_continuity : ∀ K : ℝ, WeilFormContinuous K
  local_square_positivity : ∀ K : ℝ, LocalWeilSquarePositivity K

#check GeneratorSupportedInHalfWindow
#check AdmissibleGenerator
#check WeilGeneratorSquare
#check WeilGeneratorForm
#check LocalWeilSquarePositivity
#check GlobalWeilPositivity
#check global_weil_positivity_of_local
#check RH_of_global_weil_positivity
#check WeilGeometricSignReplacement
#check RH_of_weil_geometric_sign_replacement
#check FinitePacketWeilModel
#check FinitePacketWeilModel.ExactPacketQuadraticIdentity
#check FinitePacketWeilModel.AnalyticBoundaryToMatrixBoundary
#check FinitePacketWeilModel.PacketPSDOnBoundary
#check FinitePacketWeilModel.Certificate
#check FinitePacketWeilModel.packet_generator_nonneg_of_certificate
#check FiniteSyntheticIntersectionModel
#check FiniteSyntheticIntersectionModel.ExactWeilCIdentity
#check FiniteSyntheticIntersectionModel.AnalyticBoundaryToMatrixBoundary
#check FiniteSyntheticIntersectionModel.CPSDOnBoundary
#check FiniteSyntheticIntersectionModel.Certificate
#check FiniteSyntheticIntersectionModel.generator_nonneg_of_certificate
#check BoundaryNullPacketSquareDensity
#check WeilDirectRouteGates

end Q3

end
