import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000Base
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_2001_2500
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_2501_3000
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_3001_3500
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_3501_4000
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_4001_4500
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_4501_5000
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_5001_5500
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_5501_6000
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_6001_6500
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_6501_7000
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_7001_7500
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_7501_8000
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_8001_8500
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_8501_9000
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_9001_9500
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseGT2000_9501_10000
set_option maxRecDepth 200000
set_option maxHeartbeats 0
set_option linter.unnecessarySimpa false
set_option linter.unusedSimpArgs false

/-!
Auto-generated i19 prime-power pointwise bounds (aggregator).

Source: q3.lean.aristotle/Q3/Proofs/PrimeCert/BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_AllBuckets.lean
Generated by: scripts/prime_brange_grid_pp_auto.py
Range: [2001, 10000]
-/

noncomputable section

namespace Q3.Proofs.PrimeCert

lemma prime_b_grid_weight_term_i19_le_pp_ub_of_2001_10000_primepow_all {n : ℕ}
    (hn : IsPrimePow n) (hlo : 2001 ≤ n) (hhi : n ≤ 10000) :
    prime_b_grid_weight_term prime_b_grid_i19 n ≤ prime_b_grid_pp_i19_all_ub n := by
  by_cases h0 : n ≤ 2500
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_2001_2500_primepow hn hlo h0
  have h0' : 2501 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h0)
  by_cases h1 : n ≤ 3000
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_2501_3000_primepow hn h0' h1
  have h1' : 3001 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h1)
  by_cases h2 : n ≤ 3500
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_3001_3500_primepow hn h1' h2
  have h2' : 3501 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h2)
  by_cases h3 : n ≤ 4000
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_3501_4000_primepow hn h2' h3
  have h3' : 4001 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h3)
  by_cases h4 : n ≤ 4500
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_4001_4500_primepow hn h3' h4
  have h4' : 4501 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h4)
  by_cases h5 : n ≤ 5000
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_4501_5000_primepow hn h4' h5
  have h5' : 5001 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h5)
  by_cases h6 : n ≤ 5500
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_5001_5500_primepow hn h5' h6
  have h6' : 5501 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h6)
  by_cases h7 : n ≤ 6000
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_5501_6000_primepow hn h6' h7
  have h7' : 6001 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h7)
  by_cases h8 : n ≤ 6500
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_6001_6500_primepow hn h7' h8
  have h8' : 6501 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h8)
  by_cases h9 : n ≤ 7000
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_6501_7000_primepow hn h8' h9
  have h9' : 7001 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h9)
  by_cases h10 : n ≤ 7500
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_7001_7500_primepow hn h9' h10
  have h10' : 7501 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h10)
  by_cases h11 : n ≤ 8000
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_7501_8000_primepow hn h10' h11
  have h11' : 8001 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h11)
  by_cases h12 : n ≤ 8500
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_8001_8500_primepow hn h11' h12
  have h12' : 8501 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h12)
  by_cases h13 : n ≤ 9000
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_8501_9000_primepow hn h12' h13
  have h13' : 9001 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h13)
  by_cases h14 : n ≤ 9500
  · exact prime_b_grid_weight_term_i19_le_pp_ub_of_9001_9500_primepow hn h13' h14
  have h14' : 9501 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h14)
  exact prime_b_grid_weight_term_i19_le_pp_ub_of_9501_10000_primepow hn h14' hhi

end Q3.Proofs.PrimeCert
