import Mathlib
import Q3.Proofs.PrimeCert.BrangeGrid_2046

/-!
Pilot interval upper bounds for the prime partial sums (two grid points).

Source: output/prime_cert_brange_tcritical_pilot_interval_2026-01-30_2357.txt
Generated by: scripts/prime_brange_pilot_interval_to_lean_ub.py
-/

noncomputable section

namespace Q3.Proofs.PrimeCert

/-- Source file (pilot interval certificate). -/
def prime_cert_brange_pilot_sum_ub_source : String :=
  "output/prime_cert_brange_tcritical_pilot_interval_2026-01-30_2357.txt"

/-- SHA256 of the pilot source file. -/
def prime_cert_brange_pilot_sum_ub_sha256 : String :=
  "d2e51b9bea1eff7b50625f3e7c40aeae6a91f3eeab4eb33a5e12e948e460b5db"

/-- Interval upper bounds for the pilot partial sums. -/
def prime_b_grid_pilot_sum_ub_q_get : Fin prime_b_grid_size -> ℚ
| ⟨0, _⟩ => 8.713579078900
| ⟨19, _⟩ => 9.231221442293
| _ => 9.231221442293

def prime_b_grid_pilot_sum_ub (i : Fin prime_b_grid_size) : ℝ :=
  (prime_b_grid_pilot_sum_ub_q_get i : ℝ)

end Q3.Proofs.PrimeCert

