import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseBase
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_Pointwise_1_2000
set_option maxRecDepth 200000
set_option maxHeartbeats 0
set_option linter.unnecessarySimpa false
set_option linter.unusedSimpArgs false

/-!
Auto-generated i19 prime-power pointwise bounds (aggregator).

Source: q3.lean.aristotle/Q3/Proofs/PrimeCert/BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_AllBuckets.lean
Generated by: scripts/prime_brange_grid_pp_auto.py
Range: [1, 2000]
-/

noncomputable section

namespace Q3.Proofs.PrimeCert

lemma prime_b_grid_weight_term_i19_le_pp_ub_of_1_2000_primepow_all {n : ℕ}
    (hn : IsPrimePow n) (hlo : 1 ≤ n) (hhi : n ≤ 2000) :
    prime_b_grid_weight_term prime_b_grid_i19 n ≤ prime_b_grid_pp_i19_all_ub n := by
  exact prime_b_grid_weight_term_i19_le_pp_ub_of_1_2000_primepow hn hlo hhi

end Q3.Proofs.PrimeCert
