import Mathlib
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_Data
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_Checker
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_Tail

/-!
Prime-heat partial-sum evidence (t_critical, tau = 0).

Source: output/prime_cert_brange_heat_prime_partial_interval_2026-01-31_0009.txt
Generated by: scripts/prime_brange_heat_partial_interval_to_lean.py

This file isolates the numeric evidence for:
- the finite partial sum upper bound (h_sum_ub)
- the tail bound (h_tail)
-/

noncomputable section

namespace Q3.Proofs.PrimeCert

/-- Source file (prime-heat partial sum evidence). -/
def prime_cert_heat_prime_partial_source : String :=
  "output/prime_cert_brange_heat_prime_partial_interval_2026-01-31_0009.txt"

/-- SHA256 of the partial-sum source file. -/
def prime_cert_heat_prime_partial_sha256 : String :=
  "622070a7c1684049b1c9147ee39b2e1fdaebe657f4e22acc6490cd452e8493f8"

def prime_cert_heat_prime_sum_up_to_ub : ℝ :=
  4.004917232592

lemma prime_cert_heat_prime_sum_up_to_ub_le_partial :
    prime_cert_heat_prime_sum_up_to_ub ≤ prime_cert_L_prime_heat_partial := by
  norm_num [prime_cert_heat_prime_sum_up_to_ub, prime_cert_L_prime_heat_partial,
    prime_cert_heat_tail_bound, prime_cert_L_prime_heat_raw]

lemma prime_heat_bucket_ub_sum_le_partial :
    prime_heat_bucket_ub_sum ≤ prime_cert_heat_prime_sum_up_to_ub := by
  norm_num [prime_heat_bucket_ub_sum, prime_heat_bucket_ub_sum_q,
    prime_cert_heat_prime_sum_up_to_ub]

structure PrimeHeatSumData where
  h_bucket : PrimeHeatBucketData prime_cert_heat_prime_sum_up_to_ub
  h_tail :
    ∑' n, prime_heat_weight_term (n + (prime_cert_heat_N + 1)) ≤
      prime_cert_heat_tail_bound

axiom prime_heat_bucket_bounds :
  ∀ k : Fin prime_heat_bucket_count,
    prime_heat_bucket_sum k ≤ prime_heat_bucket_ub k

lemma prime_heat_bucket_sum_ub :
    (Finset.univ.sum (fun k => prime_heat_bucket_ub k)) ≤
      prime_cert_heat_prime_sum_up_to_ub := by
  have hsum :
      (Finset.univ.sum (fun k : Fin prime_heat_bucket_count => prime_heat_bucket_ub k)) =
        prime_heat_bucket_ub_sum := by
    simpa using
      (prime_heat_bucket_ub_sum_eq :
        (∑ k : Fin prime_heat_bucket_count, prime_heat_bucket_ub k) =
          prime_heat_bucket_ub_sum)
  simpa [hsum] using prime_heat_bucket_ub_sum_le_partial

theorem prime_heat_bucket_data :
    PrimeHeatBucketData prime_cert_heat_prime_sum_up_to_ub := by
  refine ⟨?h_bucket, ?h_sum_ub⟩
  · intro k
    exact prime_heat_bucket_bounds k
  · exact prime_heat_bucket_sum_ub

theorem prime_heat_sum_data : PrimeHeatSumData := by
  refine ⟨prime_heat_bucket_data, ?_⟩
  exact prime_heat_tail_bound

lemma prime_heat_sum_data_sum_ub :
    prime_heat_prime_sum_up_to prime_cert_heat_N ≤ prime_cert_heat_prime_sum_up_to_ub := by
  exact prime_heat_sum_up_to_le_of_bucket
    prime_cert_heat_prime_sum_up_to_ub
    prime_heat_sum_data.h_bucket

end Q3.Proofs.PrimeCert
