import Mathlib
import Q3.Proofs.PrimeCert.BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_PointwiseCore
set_option maxRecDepth 200000
set_option maxHeartbeats 0
set_option linter.unnecessarySimpa false
set_option linter.unusedSimpArgs false

/-!
Auto-generated i19 prime-power pointwise bounds (base).

Source: q3.lean.aristotle/Q3/Proofs/PrimeCert/BrangeGrid_PrimeSum_2026_01_30_PrimePow_i19_AllBuckets.lean
Generated by: scripts/prime_brange_grid_pp_auto.py
Range: [100003, 100003]
-/

noncomputable section

namespace Q3.Proofs.PrimeCert

def pi_ub : ℝ := (314159265358979323847 : ℝ) / (100000000000000000000 : ℝ)
lemma pi_le_pi_ub : Real.pi ≤ pi_ub := by
  have h' : (pi_ub : ℝ) = (3.14159265358979323847 : ℝ) := by
    norm_num [pi_ub]
  have h : (Real.pi : ℝ) < (pi_ub : ℝ) := by
    simpa [h'] using Real.pi_lt_d20
  exact le_of_lt h
lemma pi_ub_pos : 0 < pi_ub := by
  norm_num [pi_ub]

end Q3.Proofs.PrimeCert
