import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0AutoBase
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_0_249
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_250_499
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_500_749
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_750_999
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_1000_1249
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_1250_1499
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_1500_1749
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_1750_1999
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_2000_2249
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_2250_2499
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_2500_2749
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_2750_2999
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_3000_3249
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_3250_3499
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_3500_3749
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_3750_3999
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_4000_4249
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_4250_4499
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_4500_4749
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_4750_4999
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_5000_5249
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_5250_5499
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_5500_5749
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_5750_5999
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_6000_6249
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_6250_6499
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_6500_6749
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_6750_6999
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_7000_7249
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_7250_7499
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_7500_7749
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_7750_7999
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_8000_8249
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_8250_8499
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_8500_8749
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_8750_8999
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_9000_9249
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_9250_9499
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_9500_9749
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_9750_9999
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_PrimePowBucket0Auto_10000_10000
set_option maxHeartbeats 0

/-!
Auto-generated bucket-0 prime-power interval bounds (aggregator).

Source: q3.lean.aristotle/Q3/Proofs/PrimeCert/BrangeHeatCert_2026_01_28_PrimePowData.lean
Generated by: scripts/prime_brange_heat_pp_bucket0_auto.py
-/

noncomputable section

namespace Q3.Proofs.PrimeCert

lemma prime_heat_weight_term_le_pp_ub_of_le_10000 {n : ℕ} (hN : n ≤ 10000) :
    prime_heat_weight_term n ≤ Full.prime_heat_pp_term_ub n := by
  by_cases h0 : n ≤ 249
  · exact prime_heat_weight_term_le_pp_ub_of_le_249 h0
  have h0' : 250 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h0)
  by_cases h1 : n ≤ 499
  · exact prime_heat_weight_term_le_pp_ub_of_250_499 h0' h1
  have h1' : 500 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h1)
  by_cases h2 : n ≤ 749
  · exact prime_heat_weight_term_le_pp_ub_of_500_749 h1' h2
  have h2' : 750 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h2)
  by_cases h3 : n ≤ 999
  · exact prime_heat_weight_term_le_pp_ub_of_750_999 h2' h3
  have h3' : 1000 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h3)
  by_cases h4 : n ≤ 1249
  · exact prime_heat_weight_term_le_pp_ub_of_1000_1249 h3' h4
  have h4' : 1250 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h4)
  by_cases h5 : n ≤ 1499
  · exact prime_heat_weight_term_le_pp_ub_of_1250_1499 h4' h5
  have h5' : 1500 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h5)
  by_cases h6 : n ≤ 1749
  · exact prime_heat_weight_term_le_pp_ub_of_1500_1749 h5' h6
  have h6' : 1750 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h6)
  by_cases h7 : n ≤ 1999
  · exact prime_heat_weight_term_le_pp_ub_of_1750_1999 h6' h7
  have h7' : 2000 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h7)
  by_cases h8 : n ≤ 2249
  · exact prime_heat_weight_term_le_pp_ub_of_2000_2249 h7' h8
  have h8' : 2250 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h8)
  by_cases h9 : n ≤ 2499
  · exact prime_heat_weight_term_le_pp_ub_of_2250_2499 h8' h9
  have h9' : 2500 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h9)
  by_cases h10 : n ≤ 2749
  · exact prime_heat_weight_term_le_pp_ub_of_2500_2749 h9' h10
  have h10' : 2750 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h10)
  by_cases h11 : n ≤ 2999
  · exact prime_heat_weight_term_le_pp_ub_of_2750_2999 h10' h11
  have h11' : 3000 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h11)
  by_cases h12 : n ≤ 3249
  · exact prime_heat_weight_term_le_pp_ub_of_3000_3249 h11' h12
  have h12' : 3250 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h12)
  by_cases h13 : n ≤ 3499
  · exact prime_heat_weight_term_le_pp_ub_of_3250_3499 h12' h13
  have h13' : 3500 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h13)
  by_cases h14 : n ≤ 3749
  · exact prime_heat_weight_term_le_pp_ub_of_3500_3749 h13' h14
  have h14' : 3750 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h14)
  by_cases h15 : n ≤ 3999
  · exact prime_heat_weight_term_le_pp_ub_of_3750_3999 h14' h15
  have h15' : 4000 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h15)
  by_cases h16 : n ≤ 4249
  · exact prime_heat_weight_term_le_pp_ub_of_4000_4249 h15' h16
  have h16' : 4250 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h16)
  by_cases h17 : n ≤ 4499
  · exact prime_heat_weight_term_le_pp_ub_of_4250_4499 h16' h17
  have h17' : 4500 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h17)
  by_cases h18 : n ≤ 4749
  · exact prime_heat_weight_term_le_pp_ub_of_4500_4749 h17' h18
  have h18' : 4750 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h18)
  by_cases h19 : n ≤ 4999
  · exact prime_heat_weight_term_le_pp_ub_of_4750_4999 h18' h19
  have h19' : 5000 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h19)
  by_cases h20 : n ≤ 5249
  · exact prime_heat_weight_term_le_pp_ub_of_5000_5249 h19' h20
  have h20' : 5250 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h20)
  by_cases h21 : n ≤ 5499
  · exact prime_heat_weight_term_le_pp_ub_of_5250_5499 h20' h21
  have h21' : 5500 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h21)
  by_cases h22 : n ≤ 5749
  · exact prime_heat_weight_term_le_pp_ub_of_5500_5749 h21' h22
  have h22' : 5750 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h22)
  by_cases h23 : n ≤ 5999
  · exact prime_heat_weight_term_le_pp_ub_of_5750_5999 h22' h23
  have h23' : 6000 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h23)
  by_cases h24 : n ≤ 6249
  · exact prime_heat_weight_term_le_pp_ub_of_6000_6249 h23' h24
  have h24' : 6250 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h24)
  by_cases h25 : n ≤ 6499
  · exact prime_heat_weight_term_le_pp_ub_of_6250_6499 h24' h25
  have h25' : 6500 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h25)
  by_cases h26 : n ≤ 6749
  · exact prime_heat_weight_term_le_pp_ub_of_6500_6749 h25' h26
  have h26' : 6750 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h26)
  by_cases h27 : n ≤ 6999
  · exact prime_heat_weight_term_le_pp_ub_of_6750_6999 h26' h27
  have h27' : 7000 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h27)
  by_cases h28 : n ≤ 7249
  · exact prime_heat_weight_term_le_pp_ub_of_7000_7249 h27' h28
  have h28' : 7250 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h28)
  by_cases h29 : n ≤ 7499
  · exact prime_heat_weight_term_le_pp_ub_of_7250_7499 h28' h29
  have h29' : 7500 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h29)
  by_cases h30 : n ≤ 7749
  · exact prime_heat_weight_term_le_pp_ub_of_7500_7749 h29' h30
  have h30' : 7750 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h30)
  by_cases h31 : n ≤ 7999
  · exact prime_heat_weight_term_le_pp_ub_of_7750_7999 h30' h31
  have h31' : 8000 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h31)
  by_cases h32 : n ≤ 8249
  · exact prime_heat_weight_term_le_pp_ub_of_8000_8249 h31' h32
  have h32' : 8250 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h32)
  by_cases h33 : n ≤ 8499
  · exact prime_heat_weight_term_le_pp_ub_of_8250_8499 h32' h33
  have h33' : 8500 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h33)
  by_cases h34 : n ≤ 8749
  · exact prime_heat_weight_term_le_pp_ub_of_8500_8749 h33' h34
  have h34' : 8750 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h34)
  by_cases h35 : n ≤ 8999
  · exact prime_heat_weight_term_le_pp_ub_of_8750_8999 h34' h35
  have h35' : 9000 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h35)
  by_cases h36 : n ≤ 9249
  · exact prime_heat_weight_term_le_pp_ub_of_9000_9249 h35' h36
  have h36' : 9250 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h36)
  by_cases h37 : n ≤ 9499
  · exact prime_heat_weight_term_le_pp_ub_of_9250_9499 h36' h37
  have h37' : 9500 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h37)
  by_cases h38 : n ≤ 9749
  · exact prime_heat_weight_term_le_pp_ub_of_9500_9749 h37' h38
  have h38' : 9750 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h38)
  by_cases h39 : n ≤ 9999
  · exact prime_heat_weight_term_le_pp_ub_of_9750_9999 h38' h39
  have h39' : 10000 ≤ n := by
    exact (Nat.succ_le_iff).2 (Nat.lt_of_not_ge h39)
  exact prime_heat_weight_term_le_pp_ub_of_10000_10000 h39' hN

end Q3.Proofs.PrimeCert
