import Q3.Proofs.RouteB.D0PstarSourceWeilOddTailGraphOperator

set_option linter.mathlibStandardSet false

noncomputable section

open Complex MeasureTheory
open scoped ComplexConjugate NNReal

namespace Q3.RouteB.D0Pstar

/-!
# Source-Weil even zero mode and nonzero-tail carrier

The inverse-frequency source argument cannot include frequency zero.  This
file therefore defines the source zero graph mode separately from the closed
tail generated by normalized symmetric pairs `±(n+1)`.

This is the first carrier pre-gate only.  It does not assert an exhaustive
even-sector direct sum, nonzero-mode orthonormal synthesis, compatibility with
the selected production row, a selected Rayleigh-shift floor, a Schur sign, or
a complement floor.
-/

/-- The literal source zero graph mode, kept outside the nonzero tail. -/
noncomputable def sourceWeilGraphEvenZeroMode
    (i : PairIndex) : SourceWeilGraphCarrier i :=
  sourceWeilGraphLift i
    (sourceArchimedeanModeInShiftedFormDomain i 0)

/-- A normalized nonzero reflection-even graph mode.  The public index
`n : ℕ` denotes the physical pair `±(n+1)`, so zero is excluded by type. -/
noncomputable def sourceWeilGraphEvenNonzeroMode
    (i : PairIndex) (n : ℕ) : SourceWeilGraphCarrier i :=
  ((Real.sqrt 2 : ℝ) : ℂ)⁻¹ •
    (sourceWeilGraphLift i
        (sourceArchimedeanModeInShiftedFormDomain i (n + 1 : ℕ)) +
      sourceWeilGraphLift i
        (sourceArchimedeanModeInShiftedFormDomain i (-((n + 1 : ℕ) : ℤ))))

/-- The closed nonzero-even source tail after cutoff `R`. -/
noncomputable def sourceWeilGraphEvenNonzeroTail
    (i : PairIndex) (R : ℕ) : Submodule ℂ (SourceWeilGraphCarrier i) :=
  (Submodule.span ℂ
    (Set.range (fun k : ℕ => sourceWeilGraphEvenNonzeroMode i (R + k)))).topologicalClosure

abbrev SourceWeilGraphEvenNonzeroTailCarrier (i : PairIndex) (R : ℕ) :=
  sourceWeilGraphEvenNonzeroTail i R

noncomputable instance sourceWeilGraphEvenNonzeroTailCompleteSpace
    (i : PairIndex) (R : ℕ) :
    CompleteSpace (SourceWeilGraphEvenNonzeroTailCarrier i R) :=
  (Submodule.isClosed_topologicalClosure
    (Submodule.span ℂ
      (Set.range
        (fun k : ℕ => sourceWeilGraphEvenNonzeroMode i (R + k))))).completeSpace_coe

instance sourceWeilGraphEvenNonzeroTailInnerProductSpace
    (i : PairIndex) (R : ℕ) :
    InnerProductSpace ℂ (SourceWeilGraphEvenNonzeroTailCarrier i R) :=
  Submodule.innerProductSpace (sourceWeilGraphEvenNonzeroTail i R)

noncomputable instance sourceWeilGraphEvenNonzeroTailHasOrthogonalProjection
    (i : PairIndex) (R : ℕ) :
    (sourceWeilGraphEvenNonzeroTail i R).HasOrthogonalProjection :=
  Submodule.HasOrthogonalProjection.ofCompleteSpace
    (sourceWeilGraphEvenNonzeroTail i R)

@[simp] theorem sourceWeilGraphAmbient_evenZeroMode
    (i : PairIndex) :
    sourceWeilGraphAmbient i (sourceWeilGraphEvenZeroMode i) = V_n_m i 0 := by
  rw [sourceWeilGraphEvenZeroMode, sourceWeilGraphAmbient_lift]
  rfl

@[simp] theorem sourceWeilGraphAmbient_evenNonzeroMode
    (i : PairIndex) (n : ℕ) :
    sourceWeilGraphAmbient i (sourceWeilGraphEvenNonzeroMode i n) =
      ((Real.sqrt 2 : ℝ) : ℂ)⁻¹ •
        (V_n_m i (n + 1 : ℕ) + V_n_m i (-((n + 1 : ℕ) : ℤ))) := by
  rw [sourceWeilGraphEvenNonzeroMode, map_smul, map_add,
    sourceWeilGraphAmbient_lift, sourceWeilGraphAmbient_lift]
  rfl

/-- Every algebraic nonzero-even tail vector has zero production Fourier
coefficient in every mode `|n| ≤ R`, including frequency zero. -/
theorem sourceWeilGraphEvenNonzeroTailAlgebraic_low_fourier_vanish
    (i : PairIndex) (R : ℕ) (x : SourceWeilGraphCarrier i)
    (hx : x ∈ Submodule.span ℂ
      (Set.range (fun k : ℕ => sourceWeilGraphEvenNonzeroMode i (R + k))))
    (n : ℤ) (hn : n.natAbs ≤ R) :
    inner ℂ (V_n_m i n) (sourceWeilGraphAmbient i x) = 0 := by
  refine Submodule.span_induction
    (p := fun y _ => inner ℂ (V_n_m i n) (sourceWeilGraphAmbient i y) = 0)
    ?_ ?_ ?_ ?_ hx
  · intro y hy
    rcases hy with ⟨k, rfl⟩
    have hpos : n ≠ (((R + k + 1 : ℕ) : ℤ)) := by
      intro hEq
      have habs : n.natAbs = R + k + 1 :=
        (congrArg Int.natAbs hEq).trans
          (Int.natAbs_natCast (R + k + 1))
      omega
    have hneg : n ≠ -(((R + k + 1 : ℕ) : ℤ)) := by
      intro hEq
      have habs : n.natAbs = R + k + 1 :=
        (congrArg Int.natAbs hEq).trans
          ((Int.natAbs_neg (((R + k + 1 : ℕ) : ℤ))).trans
            (Int.natAbs_natCast (R + k + 1)))
      omega
    rw [sourceWeilGraphAmbient_evenNonzeroMode, inner_smul_right,
      inner_add_right,
      (V_n_m_orthonormal i).inner_eq_zero hpos,
      (V_n_m_orthonormal i).inner_eq_zero hneg]
    simp
  · simp
  · intro y z _hy _hz hy hz
    rw [map_add, inner_add_right, hy, hz, add_zero]
  · intro a y _hy hy
    rw [map_smul, inner_smul_right, hy, mul_zero]

/-- Low-frequency cancellation extends from the algebraic span to the exact
closed graph tail. -/
theorem sourceWeilGraphEvenNonzeroTail_low_fourier_vanish
    (i : PairIndex) (R : ℕ)
    (x : SourceWeilGraphEvenNonzeroTailCarrier i R)
    (n : ℤ) (hn : n.natAbs ≤ R) :
    inner ℂ (V_n_m i n)
      (sourceWeilGraphAmbient i (x : SourceWeilGraphCarrier i)) = 0 := by
  let algebraic : Submodule ℂ (SourceWeilGraphCarrier i) :=
    Submodule.span ℂ
      (Set.range (fun k : ℕ => sourceWeilGraphEvenNonzeroMode i (R + k)))
  let coefficient : SourceWeilGraphCarrier i → ℂ := fun y =>
    inner ℂ (V_n_m i n) (sourceWeilGraphAmbient i y)
  have hcontinuous : Continuous coefficient := by
    dsimp [coefficient]
    fun_prop
  have hclosed : IsClosed {y : SourceWeilGraphCarrier i | coefficient y = 0} :=
    isClosed_eq hcontinuous continuous_const
  have hsubset :
      (algebraic : Set (SourceWeilGraphCarrier i)) ⊆
        {y : SourceWeilGraphCarrier i | coefficient y = 0} := by
    intro y hy
    exact sourceWeilGraphEvenNonzeroTailAlgebraic_low_fourier_vanish
      i R y (by simpa [algebraic] using hy) n hn
  have hxclosure :
      (x : SourceWeilGraphCarrier i) ∈
        closure (algebraic : Set (SourceWeilGraphCarrier i)) := by
    change (x : SourceWeilGraphCarrier i) ∈ algebraic.topologicalClosure
    have hxprop := x.property
    change (x : SourceWeilGraphCarrier i) ∈ algebraic.topologicalClosure at hxprop
    exact hxprop
  exact (closure_minimal hsubset hclosed) hxclosure

/-- The source zero mode is ambient-orthogonal to the closed nonzero-even
tail.  This is not a graph-orthogonal direct-sum statement. -/
theorem sourceWeilGraphEvenZeroMode_orthogonal_nonzeroTail
    (i : PairIndex) (R : ℕ)
    (x : SourceWeilGraphEvenNonzeroTailCarrier i R) :
    inner ℂ (sourceWeilGraphAmbient i (sourceWeilGraphEvenZeroMode i))
      (sourceWeilGraphAmbient i (x : SourceWeilGraphCarrier i)) = 0 := by
  rw [sourceWeilGraphAmbient_evenZeroMode]
  exact sourceWeilGraphEvenNonzeroTail_low_fourier_vanish i R x 0 (Nat.zero_le R)

#print axioms sourceWeilGraphAmbient_evenZeroMode
#print axioms sourceWeilGraphAmbient_evenNonzeroMode
#print axioms sourceWeilGraphEvenNonzeroTailAlgebraic_low_fourier_vanish
#print axioms sourceWeilGraphEvenNonzeroTail_low_fourier_vanish
#print axioms sourceWeilGraphEvenZeroMode_orthogonal_nonzeroTail

end Q3.RouteB.D0Pstar
