import Mathlib

/-!
# G6N1: exact Hilbert-pairing identity for divided-difference (Loewner) forms

The literal finite CCM Weil matrix has off-diagonal entries
`(β i - β j)/(n i - n j)`.  This file proves, for that structure alone:

* the discrete Hilbert operator `H` built from the node differences is
  antisymmetric;
* the off-diagonal quadratic form equals `2 * Σ i, β i * v i * (H v) i`
  (real carrier) and `2 * Σ i, β i * re (conj (v i) * (H v) i)` (complex);
* the pairing weight has **identically zero total mass**, because `H` is
  antisymmetric — the cancellation is built into the consumer, not assumed.

Finite-cell algebra only: no `Tendsto`, no `Filter.Eventually`, no rate
hypothesis, no cofinal conclusion, no arithmetic input about `β`.
-/

set_option linter.mathlibStandardSet false

noncomputable section

namespace Q3.RouteB

open Matrix
open scoped BigOperators

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- The discrete Hilbert operator attached to a node family `n`. -/
def dividedDifferenceHilbert (n : ι → ℝ) : Matrix ι ι ℝ :=
  fun i j => if i = j then 0 else (n i - n j)⁻¹

/-- The off-diagonal Loewner (divided-difference) matrix of `β` over `n`. -/
def loewnerOffDiag (n β : ι → ℝ) : Matrix ι ι ℝ :=
  fun i j => if i = j then 0 else (β i - β j) / (n i - n j)

/-- **Antisymmetry of the discrete Hilbert operator.** -/
theorem dividedDifferenceHilbert_antisymm (n : ι → ℝ) (i j : ι) :
    dividedDifferenceHilbert n j i = -dividedDifferenceHilbert n i j := by
  unfold dividedDifferenceHilbert
  by_cases h : i = j
  · subst h; simp
  · rw [if_neg (Ne.symm h), if_neg h]
    rw [show n j - n i = -(n i - n j) by ring, inv_neg]

/-- The Loewner entry factors through the Hilbert operator. -/
theorem loewnerOffDiag_eq (n β : ι → ℝ) (i j : ι) :
    loewnerOffDiag n β i j =
      β i * dividedDifferenceHilbert n i j -
        β j * dividedDifferenceHilbert n i j := by
  unfold loewnerOffDiag dividedDifferenceHilbert
  by_cases h : i = j
  · subst h; simp
  · rw [if_neg h, if_neg h]
    field_simp

/-- **Zero total mass of the pairing weight.**  The weight `v i * (H v) i`
generated by any test vector sums to zero, because `H` is antisymmetric.
The cancellation is structural, not an assumption. -/
theorem hilbert_weight_total_mass_zero (n v : ι → ℝ) :
    ∑ i, v i * (dividedDifferenceHilbert n *ᵥ v) i = 0 := by
  classical
  have hexp : ∑ i, v i * (dividedDifferenceHilbert n *ᵥ v) i =
      ∑ i, ∑ j, dividedDifferenceHilbert n i j * (v i * v j) := by
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [Matrix.mulVec, dotProduct, Finset.mul_sum]
    exact Finset.sum_congr rfl fun j _ => by ring
  rw [hexp]
  -- the double sum is antisymmetric under the swap i ↔ j
  have hswap : ∑ i, ∑ j, dividedDifferenceHilbert n i j * (v i * v j) =
      -∑ i, ∑ j, dividedDifferenceHilbert n i j * (v i * v j) := by
    conv_lhs => rw [Finset.sum_comm]
    rw [← Finset.sum_neg_distrib]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [← Finset.sum_neg_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [dividedDifferenceHilbert_antisymm n i j]
    ring
  linarith [hswap]

/-- **The exact Hilbert-pairing identity (real carrier).**  The off-diagonal
Loewner quadratic form is exactly twice the pairing of `β` against the
Hilbert weight generated by the test vector. -/
theorem loewner_quadratic_eq_two_mul_hilbert_pairing (n β v : ι → ℝ) :
    ∑ i, ∑ j, loewnerOffDiag n β i j * (v i * v j) =
      2 * ∑ i, β i * (v i * (dividedDifferenceHilbert n *ᵥ v) i) := by
  classical
  set H := dividedDifferenceHilbert n with hH
  -- split the Loewner entry
  have hsplit : ∑ i, ∑ j, loewnerOffDiag n β i j * (v i * v j) =
      (∑ i, ∑ j, β i * H i j * (v i * v j)) -
        ∑ i, ∑ j, β j * H i j * (v i * v j) := by
    rw [← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [loewnerOffDiag_eq n β i j, hH]
    ring
  -- the second double sum equals minus the first
  have hsecond : ∑ i, ∑ j, β j * H i j * (v i * v j) =
      -∑ i, ∑ j, β i * H i j * (v i * v j) := by
    conv_lhs => rw [Finset.sum_comm]
    rw [← Finset.sum_neg_distrib]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [← Finset.sum_neg_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [hH, dividedDifferenceHilbert_antisymm n i j]
    ring
  have hfirst : ∑ i, ∑ j, β i * H i j * (v i * v j) =
      ∑ i, β i * (v i * (H *ᵥ v) i) := by
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [Matrix.mulVec, dotProduct, Finset.mul_sum, Finset.mul_sum]
    exact Finset.sum_congr rfl fun j _ => by ring
  rw [hsplit, hsecond, hfirst]
  ring

#print axioms dividedDifferenceHilbert_antisymm
#print axioms loewnerOffDiag_eq
#print axioms hilbert_weight_total_mass_zero
#print axioms loewner_quadratic_eq_two_mul_hilbert_pairing

/-! ## Complex carrier: the literal star-first form used by the source -/

/-- Complexified Hilbert operator (real entries, complex carrier). -/
def dividedDifferenceHilbertC (n : ι → ℝ) : Matrix ι ι ℂ :=
  fun i j => ((dividedDifferenceHilbert n i j : ℝ) : ℂ)

/-- Complexified Loewner off-diagonal matrix. -/
def loewnerOffDiagC (n β : ι → ℝ) : Matrix ι ι ℂ :=
  fun i j => ((loewnerOffDiag n β i j : ℝ) : ℂ)

/-- **Zero total mass, complex carrier.**  The real part of the
conjugate-first weight sums to zero identically. -/
theorem hilbert_weight_total_mass_zero_complex (n : ι → ℝ) (v : ι → ℂ) :
    ∑ i, (starRingEnd ℂ (v i) * (dividedDifferenceHilbertC n *ᵥ v) i).re = 0 := by
  classical
  set S : ℂ := ∑ i, starRingEnd ℂ (v i) * (dividedDifferenceHilbertC n *ᵥ v) i
    with hS
  have hexp : S = ∑ i, ∑ j, dividedDifferenceHilbertC n i j *
      (starRingEnd ℂ (v i) * v j) := by
    rw [hS]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [Matrix.mulVec, dotProduct, Finset.mul_sum]
    exact Finset.sum_congr rfl fun j _ => by ring
  -- S is purely imaginary: swapping i ↔ j conjugates and negates
  have hconj : starRingEnd ℂ S = -S := by
    rw [hexp, map_sum]
    rw [show (-∑ i, ∑ j, dividedDifferenceHilbertC n i j *
        (starRingEnd ℂ (v i) * v j)) =
        ∑ i, ∑ j, -(dividedDifferenceHilbertC n j i *
          (starRingEnd ℂ (v j) * v i)) by
      rw [← Finset.sum_neg_distrib]
      conv_rhs => rw [Finset.sum_comm]
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [← Finset.sum_neg_distrib]]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [map_sum]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [dividedDifferenceHilbertC, dividedDifferenceHilbertC,
      dividedDifferenceHilbert_antisymm n j i]
    push_cast
    simp only [map_mul, map_neg, Complex.conj_ofReal, Complex.conj_conj]
    ring
  have hre := congrArg Complex.re hconj
  simp only [Complex.conj_re, Complex.neg_re] at hre
  have : S.re = 0 := by linarith
  rw [← this, hS, Complex.re_sum]

/-- **The exact Hilbert-pairing identity, complex carrier.**  The star-first
off-diagonal Loewner form is exactly twice the pairing of `β` against the
real part of the conjugate-first Hilbert weight. -/
theorem loewner_form_eq_two_mul_hilbert_pairing_complex
    (n β : ι → ℝ) (v : ι → ℂ) :
    (∑ i, ∑ j, starRingEnd ℂ (v i) * loewnerOffDiagC n β i j * v j).re =
      2 * ∑ i, β i *
        (starRingEnd ℂ (v i) * (dividedDifferenceHilbertC n *ᵥ v) i).re := by
  classical
  set H := dividedDifferenceHilbertC n with hH
  set A : ℂ := ∑ i, ∑ j, ((β i : ℝ) : ℂ) * H i j *
    (starRingEnd ℂ (v i) * v j) with hA
  have hsplit : (∑ i, ∑ j, starRingEnd ℂ (v i) * loewnerOffDiagC n β i j * v j)
      = A - ∑ i, ∑ j, ((β j : ℝ) : ℂ) * H i j *
          (starRingEnd ℂ (v i) * v j) := by
    rw [hA, ← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [loewnerOffDiagC, hH, dividedDifferenceHilbertC,
      loewnerOffDiag_eq n β i j]
    push_cast
    ring
  have hsecond : (∑ i, ∑ j, ((β j : ℝ) : ℂ) * H i j *
      (starRingEnd ℂ (v i) * v j)) = -starRingEnd ℂ A := by
    rw [hA, map_sum, ← Finset.sum_neg_distrib]
    conv_lhs => rw [Finset.sum_comm]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [map_sum, ← Finset.sum_neg_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [hH, dividedDifferenceHilbertC, dividedDifferenceHilbertC,
      dividedDifferenceHilbert_antisymm n j i]
    push_cast
    simp only [map_mul, map_neg, Complex.conj_ofReal, Complex.conj_conj]
    ring
  rw [hsplit, hsecond, sub_neg_eq_add]
  have hAre : (A + starRingEnd ℂ A).re = 2 * A.re := by
    simp only [Complex.add_re, Complex.conj_re]
    ring
  have hAvalue : A.re = ∑ i, β i *
      (starRingEnd ℂ (v i) * (dividedDifferenceHilbertC n *ᵥ v) i).re := by
    rw [hA, Complex.re_sum]
    refine Finset.sum_congr rfl fun i _ => ?_
    have hrow : (∑ j, ((β i : ℝ) : ℂ) * H i j *
        (starRingEnd ℂ (v i) * v j)) =
        ((β i : ℝ) : ℂ) *
          (starRingEnd ℂ (v i) * (dividedDifferenceHilbertC n *ᵥ v) i) := by
      rw [Matrix.mulVec, dotProduct, Finset.mul_sum, Finset.mul_sum]
      refine Finset.sum_congr rfl fun j _ => ?_
      rw [hH]
      ring
    rw [hrow, Complex.re_ofReal_mul]
  rw [hAre, hAvalue]

#print axioms hilbert_weight_total_mass_zero_complex
#print axioms loewner_form_eq_two_mul_hilbert_pairing_complex

end Q3.RouteB
