import Q3.Proofs.RouteB.QuotientByRadicalSelfAdjoint
import Mathlib.LinearAlgebra.FiniteDimensional.Basic

set_option linter.mathlibStandardSet false

noncomputable section

namespace Q3.RouteB

/-- A one-dimensional radical is exactly the line generated by any named
nonzero radical vector. -/
theorem bilinForm_ker_eq_span_singleton_of_finrank_one
    {V : Type*} [AddCommGroup V] [Module ℝ V]
    [FiniteDimensional ℝ V]
    (B : LinearMap.BilinForm ℝ V)
    (xi : V)
    (hxi : xi ∈ LinearMap.ker B)
    (hxi0 : xi ≠ 0)
    (hker1 : Module.finrank ℝ (LinearMap.ker B) = 1) :
    LinearMap.ker B = ℝ ∙ xi := by
  symm
  apply Submodule.eq_of_le_of_finrank_eq
  · exact (Submodule.span_singleton_le_iff_mem xi (LinearMap.ker B)).2 hxi
  · rw [finrank_span_singleton hxi0, hker1]

#print axioms bilinForm_ker_eq_span_singleton_of_finrank_one

end Q3.RouteB
