/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: fb91fbb3-4c87-4740-939a-c672648a38ae
-/

/-
This module proves that the sum of prime operator weights is bounded by 1/25, closing the `h_weight_sum` hypothesis needed by `rkhs_cap_rayleigh_tcap`. It establishes exponential decay bounds for the weights and sums them up, handling the small n cases separately.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators
open Finset Real Nat



-- Upper bound for weight sum
def rho_one : ℝ := 1 / 25

-- Heat parameter (t_rkhs_cap = 40)
def t_rkhs_cap : ℝ := 40

-- 4π² constant
def four_pi_sq : ℝ := 4 * Real.pi ^ 2

-- Weight function: 2 * Λ(n) / √n * exp(-4π² * t * (log n)²)
-- For our bound, we use Λ(n) ≤ log n
def weight_upper_bound (t : ℝ) (n : ℕ) : ℝ :=
  if n < 2 then 0
  else 2 * Real.log n / Real.sqrt n * Real.exp (-four_pi_sq * t * (Real.log n)^2)

lemma exp_decay_bound {n : ℕ} (hn : 3 ≤ n) (t : ℝ) (ht : 1 ≤ t) :
    Real.exp (-four_pi_sq * t * (Real.log n)^2) ≤ (n : ℝ)^(-10 : ℝ) := by
      -- Since $4\pi^2 \approx 39.5 > 10$, we have $4\pi^2 * t * (\log n)^2 \geq 10 * \log n$.
      have h_ineq : 4 * Real.pi ^ 2 * t * (Real.log n) ^ 2 ≥ 10 * Real.log n := by
        -- Since $4\pi^2 \approx 39.5 > 10$, we have $4\pi^2 * t * (\log n)^2 \geq 10 * \log n$ for $n \geq 3$.
        have h_ineq : 4 * Real.pi ^ 2 * t * (Real.log n) ≥ 10 := by
          -- Since $4\pi^2 \approx 39.5 > 10$, we have $4\pi^2 * t * \log n \geq 10 * \log n$.
          have h_ineq : 4 * Real.pi ^ 2 * Real.log n ≥ 10 := by
            have h_ineq : 4 * Real.pi ^ 2 * Real.log 3 ≥ 10 := by
              nlinarith [ Real.pi_gt_three, show 1 ≤ Real.log 3 by rw [ Real.le_log_iff_exp_le ( by norm_num ) ] ; exact Real.exp_one_lt_d9.le.trans ( by norm_num ) ];
            exact le_trans h_ineq ( mul_le_mul_of_nonneg_left ( Real.log_le_log ( by norm_num ) ( by norm_cast ) ) ( by positivity ) );
          nlinarith [ show 0 ≤ 4 * Real.pi ^ 2 * Real.log n by positivity ];
        nlinarith [ Real.log_nonneg ( by norm_cast; linarith : ( n : ℝ ) ≥ 1 ) ];
      rw [ Real.rpow_def_of_pos ( by positivity ) ] ; norm_num [ four_pi_sq ] ; ring_nf at * ; aesop

lemma weight_bound_large_n {n : ℕ} (hn : 3 ≤ n) (t : ℝ) (ht : 1 ≤ t) :
    weight_upper_bound t n ≤ 2 * Real.log n / (n : ℝ)^(10.5 : ℝ) := by
      unfold weight_upper_bound;
      rw [ if_neg ( by linarith ) ];
      refine' le_trans ( mul_le_mul_of_nonneg_left ( exp_decay_bound hn t ht ) ( by positivity ) ) _ ; ring_nf ; norm_num [ Real.sqrt_eq_rpow ];
      field_simp;
      rw [ mul_assoc, ← Real.rpow_natCast, ← Real.rpow_add ( by positivity ) ] ; norm_num

lemma tail_sum_bound :
    ∑' n : {k : ℕ // 3 ≤ k}, (2 * Real.log n / (n : ℝ)^(10.5 : ℝ)) < 0.001 := by
      -- We'll use the integral test to bound the sum. Consider the integral $\int_{3}^{\infty} \frac{2 \log x}{x^{10.5}} \, dx$.
      have h_integral_bound : ∑' (n : {k : ℕ // 3 ≤ k}), 2 * Real.log (n : ℝ) / (n : ℝ) ^ (10.5 : ℝ) ≤ 2 * ∑' (n : ℕ), Real.log (n + 3 : ℝ) / (n + 3 : ℝ) ^ (10.5 : ℝ) := by
        erw [ ← tsum_mul_left ];
        rw [ ← Equiv.tsum_eq ( Equiv.ofBijective ( fun x : ℕ => ⟨ x + 3, by linarith ⟩ : ℕ → { k : ℕ // 3 ≤ k } ) ⟨ fun a => ?_, fun a => ?_ ⟩ ) ] <;> norm_num [ mul_div_assoc ];
        exact ⟨ a.val - 3, by rcases a with ⟨ _ | _ | _ | a, ha ⟩ <;> trivial ⟩;
      -- We'll use the fact that $\sum_{n=3}^{\infty} \frac{\log n}{n^{10.5}}$ converges and can be bounded.
      have h_sum_bound : ∑' (n : ℕ), Real.log (n + 3 : ℝ) / (n + 3 : ℝ) ^ (10.5 : ℝ) ≤ ∑' (n : ℕ), (1 : ℝ) / (n + 3 : ℝ) ^ (10 : ℝ) := by
        -- We'll use the fact that $\frac{\log n}{n^{10.5}} \leq \frac{1}{n^{10}}$ for all $n \geq 3$.
        have h_log_bound : ∀ n : ℕ, 3 ≤ n → Real.log (n : ℝ) / (n : ℝ) ^ (10.5 : ℝ) ≤ 1 / (n : ℝ) ^ (10 : ℝ) := by
          intro n hn; rw [ div_le_div_iff₀ ( by positivity ) ( by positivity ) ] ; ring_nf; norm_num;
          -- We can divide both sides by $n^{10}$ to get $\log n \leq n^{0.5}$.
          have h_log_div : Real.log (n : ℝ) ≤ (n : ℝ) ^ (0.5 : ℝ) := by
            rw [ Real.le_rpow_iff_log_le ] <;> norm_num <;> try positivity;
            · have := Real.log_le_sub_one_of_pos ( show 0 < Real.log n / 2 by exact div_pos ( Real.log_pos ( by norm_cast; linarith ) ) zero_lt_two );
              rw [ Real.log_div ( ne_of_gt <| Real.log_pos <| by norm_cast; linarith ) ] at this <;> norm_num at *;
              have := Real.log_two_lt_d9 ; norm_num at * ; linarith;
            · exact Real.log_pos <| by norm_cast; linarith;
          exact le_trans ( mul_le_mul_of_nonneg_right h_log_div <| by positivity ) <| by rw [ ← Real.rpow_natCast, ← Real.rpow_add <| by positivity ] ; norm_num;
        refine' Summable.tsum_le_tsum _ _ _;
        · exact fun n => mod_cast h_log_bound ( n + 3 ) ( by linarith );
        · have h_summable : Summable (fun n : ℕ => (1 : ℝ) / (n + 3 : ℝ) ^ (10 : ℝ)) := by
            exact_mod_cast summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_pow.2 <| by norm_num;
          exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( Real.log_nonneg ( by linarith ) ) ( by positivity ) ) ( fun n => mod_cast h_log_bound ( n + 3 ) ( by linarith ) ) h_summable;
        · exact_mod_cast summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_pow.2 <| by norm_num;
      -- We'll use the fact that $\sum_{n=3}^{\infty} \frac{1}{n^{10}}$ converges and can be bounded.
      have h_sum_bound_final : ∑' (n : ℕ), (1 : ℝ) / (n + 3 : ℝ) ^ (10 : ℝ) ≤ ∑' (n : ℕ), (1 : ℝ) / (n + 3 : ℝ) ^ (2 : ℝ) * (1 / (3 : ℝ) ^ (8 : ℝ)) := by
        field_simp;
        refine' Summable.tsum_le_tsum _ _ _;
        · intro n; rw [ div_le_div_iff₀ ] <;> norm_cast <;> ring <;> nlinarith [ pow_pos ( Nat.succ_pos n ) 2, pow_pos ( Nat.succ_pos n ) 3, pow_pos ( Nat.succ_pos n ) 4, pow_pos ( Nat.succ_pos n ) 5, pow_pos ( Nat.succ_pos n ) 6, pow_pos ( Nat.succ_pos n ) 7, pow_pos ( Nat.succ_pos n ) 8 ] ;
        · exact_mod_cast summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_pow.2 <| by norm_num;
        · exact Summable.of_nonneg_of_le ( fun n => by positivity ) ( fun n => by rw [ div_le_div_iff₀ ] <;> norm_cast <;> ring <;> nlinarith ) ( summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_pow.2 one_lt_two );
      -- We'll use the fact that $\sum_{n=3}^{\infty} \frac{1}{n^{2}}$ converges and can be bounded.
      have h_sum_bound_final_final : ∑' (n : ℕ), (1 : ℝ) / (n + 3 : ℝ) ^ (2 : ℝ) = Real.pi ^ 2 / 6 - 1 - 1 / 4 := by
        convert HasSum.tsum_eq ( hasSum_nat_add_iff' 3 |>.2 <| hasSum_zeta_two ) using 1 <;> norm_num;
        ring;
      norm_num [ tsum_mul_right ] at * ; nlinarith [ Real.pi_gt_three, Real.pi_le_four ] ;

lemma weight_n2_bound (t : ℝ) (ht : 1 ≤ t) :
    weight_upper_bound t 2 < 0.00001 := by
      -- Calculate the value of the weight_upper_bound for $n = 2$.
      have h_weight_2 : weight_upper_bound t 2 ≤ 2 * Real.log 2 / Real.sqrt 2 * Real.exp (-four_pi_sq * 1 * (Real.log 2)^2) := by
        unfold weight_upper_bound; norm_num [ four_pi_sq ] ; (
        exact mul_le_mul_of_nonneg_left ( Real.exp_le_exp.mpr <| by nlinarith [ show 0 ≤ 4 * Real.pi ^ 2 * Real.log 2 ^ 2 by positivity ] ) <| by positivity;);
      -- Substitute the approximate values of the constants into the inequality.
      have h_approx : (2 * Real.log 2) / Real.sqrt 2 * Real.exp (-4 * Real.pi^2 * (Real.log 2)^2) < 1e-5 := by
        -- We'll use the fact that $Real.exp (-4 * Real.pi^2 * Real.log 2^2)$ is very small since $4 * Real.pi^2$ is large.
        have h_exp_small : Real.exp (-4 * Real.pi^2 * Real.log 2^2) < 1e-7 := by
          rw [ show ( -4 : ℝ ) * Real.pi ^ 2 * Real.log 2 ^ 2 = - ( 4 * Real.pi ^ 2 * Real.log 2 ^ 2 ) by ring, Real.exp_neg ];
          rw [ inv_lt_comm₀ ] <;> norm_num;
          · -- We'll use the fact that $Real.exp (4 * Real.pi^2 * Real.log 2^2)$ is very large since $4 * Real.pi^2$ is large.
            have h_exp_large : Real.exp (4 * Real.pi^2 * Real.log 2^2) > Real.exp (18) := by
              have h_pi_approx : Real.pi > 3.14 := by
                exact?;
              exact Real.exp_lt_exp.mpr ( by have := Real.log_two_gt_d9; norm_num1 at *; nlinarith [ Real.pi_le_four, pow_le_pow_left₀ ( by positivity ) h_pi_approx.le 2, pow_le_pow_left₀ ( by positivity ) this.le 2 ] );
            exact lt_of_le_of_lt ( by have := Real.exp_one_gt_d9.le; norm_num1 at *; rw [ show Real.exp 18 = ( Real.exp 1 ) ^ 18 by rw [ ← Real.exp_nat_mul ] ; norm_num ] ; exact le_trans ( by norm_num ) ( pow_le_pow_left₀ ( by positivity ) this _ ) ) h_exp_large;
          · positivity;
        exact lt_of_lt_of_le ( mul_lt_mul_of_pos_left h_exp_small ( by positivity ) ) ( by have := Real.log_two_lt_d9; norm_num1 at *; nlinarith [ Real.sqrt_nonneg 2, Real.sq_sqrt zero_le_two, mul_div_cancel₀ ( 2 * Real.log 2 ) ( ne_of_gt ( Real.sqrt_pos.mpr zero_lt_two ) ) ] );
      exact h_weight_2.trans_lt ( h_approx.trans_le' <| by unfold four_pi_sq; norm_num )

/-- The sum of weight upper bounds is less than 1/25 for t ≥ 1 -/
theorem weight_sum_le_rho_one (t : ℝ) (ht : 1 ≤ t) :
    ∑' n : ℕ, weight_upper_bound t n ≤ rho_one := by
      -- Split the sum into parts for \( n = 0 \), \( n = 1 \), and \( n \geq 2 \).
      have h_split_sum : (∑' n, weight_upper_bound t n) = (∑' n : {n : ℕ // 3 ≤ n}, weight_upper_bound t n.val) + (weight_upper_bound t 2) := by
        have h_split_sum : (∑' n, weight_upper_bound t n) = (∑' n : {n : ℕ // n < 3}, weight_upper_bound t n.val) + (∑' n : {n : ℕ // 3 ≤ n}, weight_upper_bound t n.val) := by
          have h_split_sum : (∑' n, weight_upper_bound t n) = (∑' n : ℕ, if n < 3 then weight_upper_bound t n else 0) + (∑' n : ℕ, if 3 ≤ n then weight_upper_bound t n else 0) := by
            rw [ ← Summable.tsum_add ] ; congr ; ext n ; split_ifs <;> linarith;
            · refine' summable_of_ne_finset_zero _;
              exacts [ Finset.range 3, fun n hn => if_neg <| by simpa using hn ];
            · -- We'll use the fact that if the series $\sum_{n=3}^\infty \frac{2 \log n}{n^{10.5}}$ converges, then the series $\sum_{n=3}^\infty \frac{2 \log n}{n^{10.5}} e^{-4\pi^2 t (\log n)^2}$ also converges.
              have h_summable : Summable (fun n : ℕ => if 3 ≤ n then (2 * Real.log n) / (n : ℝ)^(10.5 : ℝ) else 0) := by
                -- We can compare our series with the convergent p-series $\sum_{n=3}^\infty \frac{1}{n^{10}}$.
                have h_comparison : ∀ n : ℕ, 3 ≤ n → (2 * Real.log n) / (n : ℝ)^(10.5 : ℝ) ≤ 2 / (n : ℝ)^(9.5 : ℝ) := by
                  intro n hn; rw [ div_le_div_iff₀ ] <;> try positivity;
                  rw [ show ( 10.5 : ℝ ) = 9.5 + 1 by norm_num, Real.rpow_add ] <;> norm_num <;> try positivity;
                  nlinarith [ Real.log_le_sub_one_of_pos ( by positivity : 0 < ( n : ℝ ) ), show ( n : ℝ ) ^ ( 19 / 2 : ℝ ) > 0 by positivity ];
                exact Summable.of_nonneg_of_le ( fun n => by split_ifs <;> positivity ) ( fun n => by split_ifs <;> first | positivity | exact h_comparison n ‹_› ) <| Summable.mul_left _ <| Real.summable_nat_rpow_inv.2 <| by norm_num;
              refine' .of_nonneg_of_le ( fun n => _ ) ( fun n => _ ) h_summable;
              · unfold weight_upper_bound;
                split_ifs <;> positivity;
              · split_ifs <;> first | positivity | exact weight_bound_large_n ( by linarith ) t ht |> le_trans <| by norm_num;
          convert h_split_sum using 2;
          · rw [ tsum_eq_tsum_of_ne_zero_bij ];
            use fun x => ⟨ x, by
              aesop ⟩
            all_goals generalize_proofs at *;
            · aesop_cat;
            · intro x hx; aesop;
            · aesop;
          · rw [ tsum_eq_tsum_of_ne_zero_bij ];
            use fun x => ⟨ x, by
              aesop ⟩
            all_goals generalize_proofs at *;
            · aesop_cat;
            · intro x hx; aesop;
            · aesop;
        rw [ add_comm, h_split_sum ];
        norm_num [ Finset.sum_range_succ, weight_upper_bound ];
        rw [ tsum_eq_single ⟨ 2, by norm_num ⟩ ] ; aesop;
        rintro ⟨ _ | _ | _ | n, hn ⟩ hn' <;> norm_num at * ; tauto;
      -- Apply the bound for n ≥ 3 to the sum.
      have h_sum_bound : (∑' n : {n : ℕ // 3 ≤ n}, weight_upper_bound t n.val) ≤ (∑' n : {n : ℕ // 3 ≤ n}, (2 * Real.log n / (n : ℝ)^(10.5 : ℝ))) := by
        refine' Summable.tsum_le_tsum _ _ _;
        · intro n; convert weight_bound_large_n ( show 3 ≤ ( n : ℕ ) from n.2 ) t ht using 1;
        · refine' Summable.of_nonneg_of_le ( fun n => _ ) ( fun n => _ ) ( show Summable fun n : { n : ℕ // 3 ≤ n } => ( 2 * Real.log n / ( n : ℝ ) ^ ( 10.5 : ℝ ) ) from _ );
          · exact by unfold weight_upper_bound; split_ifs <;> positivity;
          · have := weight_bound_large_n n.2 t ht; aesop;
          · have h_summable : Summable (fun n : ℕ => (2 * Real.log n) / (n : ℝ)^(10.5 : ℝ)) := by
              -- We can compare our series with the convergent p-series $\sum_{n=2}^{\infty} \frac{1}{n^{10}}$.
              have h_comparison : ∀ n : ℕ, 2 ≤ n → (2 * Real.log n) / (n : ℝ)^(10.5 : ℝ) ≤ 2 / (n : ℝ)^(10 : ℝ) := by
                intro n hn
                have : Real.log n ≤ n ^ (0.5 : ℝ) := by
                  have := Real.log_le_sub_one_of_pos ( by positivity : 0 < ( n : ℝ ) ^ ( 1 / 2 : ℝ ) / 2 );
                  rw [ Real.log_div ( by positivity ) ( by positivity ), Real.log_rpow ( by positivity ) ] at this;
                  have := Real.log_two_lt_d9 ; norm_num at * ; linarith;
                rw [ div_le_div_iff₀ ] <;> try positivity;
                convert mul_le_mul_of_nonneg_right ( mul_le_mul_of_nonneg_left this zero_le_two ) ( by positivity : 0 ≤ ( n : ℝ ) ^ 10 ) using 1 ; ring;
                · norm_cast;
                · rw [ mul_assoc, ← Real.rpow_natCast, ← Real.rpow_add ] <;> norm_num ; linarith;
              rw [ ← summable_nat_add_iff 2 ];
              exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( mul_nonneg zero_le_two ( Real.log_nonneg ( by norm_cast; linarith ) ) ) ( by positivity ) ) ( fun n => h_comparison _ ( by linarith ) ) ( Summable.mul_left _ <| by simpa using summable_nat_add_iff 2 |>.2 <| Real.summable_one_div_nat_pow.2 <| by norm_num );
            exact h_summable.comp_injective Subtype.coe_injective;
        · have h_summable : Summable (fun n : ℕ => (2 * Real.log n) / (n : ℝ)^(10.5 : ℝ)) := by
            -- We can compare our series with the convergent p-series $\sum_{n=2}^{\infty} \frac{1}{n^{10}}$.
            have h_comparison : ∀ n : ℕ, 2 ≤ n → (2 * Real.log n) / (n : ℝ)^(10.5 : ℝ) ≤ 2 / (n : ℝ)^(10 : ℝ) := by
              intro n hn
              have : Real.log n ≤ n ^ (0.5 : ℝ) := by
                have := Real.log_le_sub_one_of_pos ( by positivity : 0 < ( n : ℝ ) ^ ( 1 / 2 : ℝ ) / 2 );
                rw [ Real.log_div ( by positivity ) ( by positivity ), Real.log_rpow ( by positivity ) ] at this;
                have := Real.log_two_lt_d9 ; norm_num at * ; linarith;
              rw [ div_le_div_iff₀ ] <;> try positivity;
              convert mul_le_mul_of_nonneg_right ( mul_le_mul_of_nonneg_left this zero_le_two ) ( by positivity : 0 ≤ ( n : ℝ ) ^ 10 ) using 1 ; ring;
              · norm_cast;
              · rw [ mul_assoc, ← Real.rpow_natCast, ← Real.rpow_add ] <;> norm_num ; linarith;
            rw [ ← summable_nat_add_iff 2 ];
            exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( mul_nonneg zero_le_two ( Real.log_nonneg ( by norm_cast; linarith ) ) ) ( by positivity ) ) ( fun n => h_comparison _ ( by linarith ) ) ( Summable.mul_left _ <| by simpa using summable_nat_add_iff 2 |>.2 <| Real.summable_one_div_nat_pow.2 <| by norm_num );
          exact h_summable.comp_injective Subtype.coe_injective;
      linarith [ tail_sum_bound, weight_n2_bound t ht, show rho_one = 1 / 25 by norm_num [ rho_one ] ]

/-- Specialized version for t_rkhs_cap = 40 -/
theorem weight_sum_at_tcap :
    ∑' n : ℕ, weight_upper_bound t_rkhs_cap n ≤ rho_one := by
      -- Apply the weight_sum_le_rho_one theorem with t = 40.
      apply weight_sum_le_rho_one;
      exact show 1 ≤ 40 by norm_num;