/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ee8bc919-4cf3-4f01-bab5-927a4e2a0821
-/

/-
This module proves that the sum of prime operator weights is bounded by 1/25, closing the `h_weight_sum` hypothesis needed by `rkhs_cap_rayleigh_tcap`. It defines the weight function and proves several lemmas bounding the weights for different ranges of `n`, culminating in the main theorem `weight_sum_at_tcap`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators
open Finset Real Nat

-- Upper bound for weight sum
def rho_one : ℝ := 1 / 25

-- Heat parameter (t_rkhs_cap = 40)
def t_rkhs_cap : ℝ := 40

-- 4π² constant
def four_pi_sq : ℝ := 4 * Real.pi ^ 2

-- Weight function: 2 * Λ(n) / √n * exp(-4π² * t * (log n)²)
-- For our bound, we use Λ(n) ≤ log n
def weight_upper_bound (t : ℝ) (n : ℕ) : ℝ :=
  if n < 2 then 0
  else 2 * Real.log n / Real.sqrt n * Real.exp (-four_pi_sq * t * (Real.log n)^2)

lemma exp_decay_bound {n : ℕ} (hn : 3 ≤ n) (t : ℝ) (ht : 1 ≤ t) :
    Real.exp (-four_pi_sq * t * (Real.log n)^2) ≤ (n : ℝ)^(-10 : ℝ) := by
      rw [ Real.rpow_def_of_pos ] <;> norm_num;
      · -- We'll use that $4\pi^2 \approx 39.5 > 10$ to show that $10 \leq 4\pi^2 t \log n$.
        have h_approx : 10 ≤ 4 * Real.pi ^ 2 * t * Real.log n := by
          have h_approx : 10 ≤ 4 * Real.pi ^ 2 * Real.log n := by
            have h_approx : Real.log n ≥ Real.log 3 := by
              exact Real.log_le_log ( by norm_num ) ( by norm_cast );
            have h_approx : Real.log 3 ≥ 1 := by
              exact Real.le_log_iff_exp_le ( by norm_num ) |>.2 <| Real.exp_one_lt_d9.le.trans <| by norm_num;
            nlinarith [ Real.pi_gt_three ];
          nlinarith [ show 0 ≤ 4 * Real.pi ^ 2 * Real.log n by positivity ];
        unfold four_pi_sq; nlinarith [ Real.log_nonneg ( by norm_cast; linarith : ( n : ℝ ) ≥ 1 ) ];
      · linarith

lemma weight_bound_large_n {n : ℕ} (hn : 3 ≤ n) (t : ℝ) (ht : 1 ≤ t) :
    weight_upper_bound t n ≤ 2 * Real.log n / (n : ℝ)^(10.5 : ℝ) := by
      -- Applying the bound from exp_decay_bound to our weight function.
      have h_exp_bound : Real.exp (-four_pi_sq * t * (Real.log n)^2) ≤ (n : ℝ)^(-10 : ℝ) := by
        exact?;
      unfold weight_upper_bound;
      split_ifs <;> try linarith;
      convert mul_le_mul_of_nonneg_left h_exp_bound ( by positivity : 0 ≤ 2 * Real.log n / Real.sqrt n ) using 1 ; norm_num [ Real.sqrt_eq_rpow, Real.rpow_neg ] ; ring;
      rw [ show ( 21 / 2 : ℝ ) = 1 / 2 + 10 by norm_num, Real.rpow_add ] <;> norm_cast ; ring ; positivity

lemma tail_sum_bound :
    ∑' n : {k : ℕ // 3 ≤ k}, (2 * Real.log n / (n : ℝ)^(10.5 : ℝ)) < 0.001 := by
      -- We'll use the comparison test. Since \( \frac{\log n}{n^{10.5}} \leq \frac{1}{n^{10}} \), we have:
      have h_comp : ∀ n : ℕ, 3 ≤ n → (2 * Real.log n) / (n : ℝ) ^ (10.5 : ℝ) ≤ 2 / (n : ℝ) ^ 10 := by
        intro n hn; rw [ div_le_div_iff₀ ] <;> try positivity;
        rw [ show ( n : ℝ ) ^ ( 10.5 : ℝ ) = ( n : ℝ ) ^ 10 * ( n : ℝ ) ^ ( 0.5 : ℝ ) by rw [ ← Real.rpow_natCast, ← Real.rpow_add ( by positivity ) ] ; norm_num ] ; ring_nf at * ; norm_num at *;
        rw [ mul_comm ] ; gcongr;
        rw [ ← Real.sqrt_eq_rpow ];
        have := Real.log_le_sub_one_of_pos ( by positivity : 0 < Real.sqrt n / 2 );
        rw [ Real.log_div ( by positivity ) ( by positivity ), Real.log_sqrt ( by positivity ) ] at this;
        have := Real.log_two_lt_d9 ; norm_num at * ; linarith;
      -- Therefore, it suffices to show that $\sum_{n=3}^{\infty} \frac{2}{n^{10}} < 0.001$.
      suffices h_sum : (∑' n : { k : ℕ // 3 ≤ k }, (2 : ℝ) / (n : ℝ) ^ 10) < 0.001 by
        refine' lt_of_le_of_lt ( Summable.tsum_le_tsum ( fun n => h_comp _ n.2 ) _ _ ) h_sum;
        · exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( mul_nonneg zero_le_two ( Real.log_nonneg ( Nat.one_le_cast.mpr ( by linarith [ n.2 ] ) ) ) ) ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ) ( fun n => h_comp _ n.2 ) ( Summable.mul_left _ <| by exact Summable.subtype ( Real.summable_nat_pow_inv.mpr <| by norm_num ) _ );
        · exact Summable.mul_left _ <| Summable.subtype ( Real.summable_nat_pow_inv.2 <| by norm_num ) _;
      -- We'll use the fact that $\sum_{n=3}^{\infty} \frac{2}{n^{10}}$ is a convergent p-series with $p=10$.
      have h_pseries : (∑' n : ℕ, (2 : ℝ) / (n + 3) ^ 10) < 0.001 := by
        -- We'll use the fact that $\sum_{n=3}^{\infty} \frac{2}{n^{10}}$ is a convergent p-series with $p=10$. We can bound it above by comparing it to a known convergent series.
        have h_pseries : (∑' n : ℕ, (2 : ℝ) / (n + 3) ^ 10) ≤ (∑' n : ℕ, (2 : ℝ) / (n + 3) ^ 2) * (1 / 3 ^ 8) := by
          rw [ ← tsum_mul_right ] ; refine' Summable.tsum_le_tsum _ _ _ <;> norm_num ; ring_nf ; norm_num;
          · field_simp;
            exact fun i => by nlinarith [ pow_nonneg ( Nat.cast_nonneg i : ( 0 : ℝ ) ≤ i ) 2, pow_nonneg ( Nat.cast_nonneg i : ( 0 : ℝ ) ≤ i ) 3, pow_nonneg ( Nat.cast_nonneg i : ( 0 : ℝ ) ≤ i ) 4, pow_nonneg ( Nat.cast_nonneg i : ( 0 : ℝ ) ≤ i ) 5, pow_nonneg ( Nat.cast_nonneg i : ( 0 : ℝ ) ≤ i ) 6 ] ;
          · exact Summable.mul_left _ <| by simpa using summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_pow.2 <| by norm_num;
          · exact Summable.mul_right _ <| Summable.mul_left _ <| by simpa using summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_pow.2 one_lt_two;
        -- We'll use the fact that $\sum_{n=3}^{\infty} \frac{2}{n^{2}}$ is a convergent p-series with $p=2$.
        have h_pseries_2 : (∑' n : ℕ, (2 : ℝ) / (n + 3) ^ 2) = 2 * (∑' n : ℕ, (1 : ℝ) / (n + 3) ^ 2) := by
          norm_num [ div_eq_mul_inv, tsum_mul_left ];
        have h_pseries_2_sum : (∑' n : ℕ, (1 : ℝ) / (n + 3) ^ 2) = Real.pi ^ 2 / 6 - 1 - 1 / 4 := by
          convert HasSum.tsum_eq ( hasSum_nat_add_iff' 3 |>.2 <| hasSum_zeta_two ) using 1 <;> norm_num;
          ring;
        -- We'll use the fact that $\pi \approx 3.14$ to estimate the value.
        have h_pi_approx : Real.pi < 3.15 := by
          exact?;
        norm_num at * ; nlinarith [ Real.pi_gt_three ];
      convert h_pseries using 1;
      rw [ ← Equiv.tsum_eq <| Equiv.ofBijective ( fun n : ℕ => ⟨ n + 3, by linarith ⟩ : ℕ → { k : ℕ // 3 ≤ k } ) ⟨ fun a => _, fun a => _ ⟩ ] <;> norm_num;
      exact fun n hn => ⟨ n - 3, Nat.sub_add_cancel hn ⟩

lemma weight_n2_bound (t : ℝ) (ht : 1 ≤ t) :
    weight_upper_bound t 2 < 0.00001 := by
      -- We'll use the exponential decay bound to show that the term for n=2 is very small.
      have h_exp_decay : Real.exp (-four_pi_sq * t * (Real.log 2)^2) ≤ Real.exp (-14) := by
        norm_num [ four_pi_sq ] at *;
        have := Real.log_two_gt_d9 ; norm_num at this ; nlinarith [ Real.pi_gt_three, pow_le_pow_left₀ ( by positivity ) Real.pi_gt_three.le 2, mul_le_mul_of_nonneg_left ht <| pow_nonneg Real.pi_pos.le 2 ];
      -- Now use the fact that $e^{-14} \approx 8.12 \times 10^{-7}$ to conclude the proof.
      have h_exp_approx : Real.exp (-14) < 1e-6 := by
        have := Real.exp_neg_one_lt_d9 ; norm_num1 at * ; rw [ show Real.exp ( -14 ) = ( Real.exp ( -1 ) ) ^ 14 by rw [ ← Real.exp_nat_mul ] ; ring ] ; exact lt_of_lt_of_le ( pow_lt_pow_left₀ this ( by positivity ) ( by norm_num ) ) ( by norm_num );
      refine' lt_of_le_of_lt ( mul_le_mul_of_nonneg_left h_exp_decay ( by positivity ) ) _;
      exact lt_of_le_of_lt ( mul_le_mul_of_nonneg_right ( show ( 2 * Real.log 2 / Real.sqrt 2 ) ≤ 1 by rw [ div_le_iff₀ <| by positivity ] ; have := Real.log_two_lt_d9; norm_num1 at *; nlinarith [ Real.sqrt_nonneg 2, Real.sq_sqrt zero_le_two ] ) <| by positivity ) <| by norm_num at * ; linarith;

/-- The sum of weight upper bounds is less than 1/25 for t ≥ 1 -/
theorem weight_sum_le_rho_one (t : ℝ) (ht : 1 ≤ t) :
    ∑' n : ℕ, weight_upper_bound t n ≤ rho_one := by
      -- Splitting the sum into three parts: n < 2, n = 2, and n ≥ 3.
      have h_split : ∑' n : ℕ, weight_upper_bound t n = ∑' n : {k : ℕ // 3 ≤ k}, weight_upper_bound t n + weight_upper_bound t 2 := by
        rw [ ←Summable.sum_add_tsum_nat_add 3 ];
        · erw [ ← Equiv.tsum_eq ( Equiv.ofBijective ( fun n : ℕ ↦ ⟨ n + 3, by linarith ⟩ : ℕ → { k : ℕ // 3 ≤ k } ) ⟨ fun a ↦ ?_, fun a ↦ ?_ ⟩ ) ] <;> norm_num [ Finset.sum_range_succ ] ; ring!;
          · unfold weight_upper_bound ; norm_num;
          · exact ⟨ a.val - 3, by rcases a with ⟨ _ | _ | _ | a, ha ⟩ <;> trivial ⟩;
        · have h_summable : Summable (fun n : ℕ => weight_upper_bound t n) := by
            have h_bound : ∀ n ≥ 3, weight_upper_bound t n ≤ 2 * Real.log n / (n : ℝ)^(10.5 : ℝ) := by
              exact?
            have h_summable : Summable (fun n : ℕ => 2 * Real.log n / (n : ℝ)^(10.5 : ℝ)) := by
              -- We can compare our series with the convergent p-series $\sum_{n=3}^\infty \frac{1}{n^{10.5 - \epsilon}}$ for any $\epsilon > 0$.
              have h_compare : ∀ ε > 0, ∃ C > 0, ∀ n : ℕ, n ≥ 3 → (2 * Real.log n) / (n : ℝ)^(10.5 : ℝ) ≤ C / (n : ℝ)^(10.5 - ε : ℝ) := by
                intros ε hε_pos
                obtain ⟨C, hC_pos, hC⟩ : ∃ C > 0, ∀ n : ℕ, n ≥ 3 → Real.log n ≤ C * (n : ℝ)^ε := by
                  use 1 / ε, by positivity, fun n hn => by have := Real.log_le_sub_one_of_pos ( by positivity : 0 < ( n : ℝ ) ^ ε ) ; rw [ Real.log_rpow ( by positivity ) ] at this; nlinarith [ show ( n : ℝ ) ^ ε > 0 by positivity, mul_div_cancel₀ 1 hε_pos.ne' ] ;
                use 2 * C, by positivity, fun n hn => ?_;
                rw [ Real.rpow_sub ( by positivity ) ];
                rw [ div_div_eq_mul_div, div_le_div_iff₀ ] <;> first | positivity | nlinarith [ hC n hn, Real.rpow_pos_of_pos ( by positivity : 0 < ( n : ℝ ) ) ε, Real.rpow_pos_of_pos ( by positivity : 0 < ( n : ℝ ) ) 10.5 ] ;
              obtain ⟨ C, hC₀, hC ⟩ := h_compare 1 zero_lt_one;
              rw [ ← summable_nat_add_iff 3 ];
              exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( mul_nonneg zero_le_two ( Real.log_nonneg ( by norm_cast; linarith ) ) ) ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ) ( fun n => hC _ ( by linarith ) ) ( Summable.mul_left _ <| by simpa using summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_rpow.2 <| by norm_num );
            rw [ ← summable_nat_add_iff 3 ] at *;
            exact Summable.of_nonneg_of_le ( fun n => by unfold weight_upper_bound; positivity ) ( fun n => h_bound _ ( by linarith ) ) h_summable;
          convert h_summable using 1;
      -- Apply the tail sum bound to the sum over n ≥ 3.
      have h_tail_bound : ∑' n : {k : ℕ // 3 ≤ k}, weight_upper_bound t n ≤ ∑' n : {k : ℕ // 3 ≤ k}, (2 * Real.log n / (n : ℝ)^(10.5 : ℝ)) := by
        refine' Summable.tsum_le_tsum _ _ _;
        · -- Apply the weight_bound_large_n lemma to each term in the sum.
          intros i
          apply weight_bound_large_n
          aesop;
          linarith;
        · have h_tail_summable : Summable (fun n : ℕ => 2 * Real.log n / (n : ℝ)^(10.5 : ℝ)) := by
            -- We can factor out the constant $2$ from the series.
            suffices h_factor : Summable (fun n : ℕ => Real.log n / (n : ℝ)^(10.5 : ℝ)) by
              simpa only [ mul_div_assoc ] using h_factor.mul_left 2;
            -- We can compare our series with the convergent p-series $\sum_{n=3}^{\infty} \frac{1}{n^{10}}$.
            have h_compare : ∀ n : ℕ, 3 ≤ n → (Real.log n) / (n : ℝ)^(10.5 : ℝ) ≤ 1 / (n : ℝ)^(10 : ℝ) := by
              intro n hn
              have h_log_le : Real.log n ≤ n ^ (0.5 : ℝ) := by
                have := Real.log_le_sub_one_of_pos ( by positivity : 0 < ( n : ℝ ) ^ ( 0.5 : ℝ ) / 2 );
                rw [ Real.log_div ( by positivity ) ( by positivity ), Real.log_rpow ( by positivity ) ] at this;
                have := Real.log_two_lt_d9 ; norm_num at * ; linarith;
              rw [ div_le_div_iff₀ ] <;> first | positivity | convert mul_le_mul_of_nonneg_right h_log_le <| Real.rpow_nonneg ( Nat.cast_nonneg n ) 10 using 1 ; rw [ ← Real.rpow_add <| by positivity ] ; norm_num;
            rw [ ← summable_nat_add_iff 3 ];
            exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( Real.log_nonneg ( by norm_cast; linarith ) ) ( by positivity ) ) ( fun n => h_compare _ ( by linarith ) ) ( by simpa using summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_pow.2 <| by norm_num );
          refine' .of_nonneg_of_le ( fun n => _ ) ( fun n => _ ) ( h_tail_summable.comp_injective Subtype.coe_injective );
          · exact by unfold weight_upper_bound; positivity;
          · convert weight_bound_large_n n.2 t ht using 1;
        · -- We'll use the fact that $\sum_{n=3}^{\infty} \frac{\log n}{n^{10.5}}$ converges.
          have h_summable : Summable (fun n : ℕ => (Real.log n) / (n : ℝ)^(10.5 : ℝ)) := by
            -- We can compare our series with the convergent p-series $\sum_{n=3}^{\infty} \frac{1}{n^{10}}$.
            have h_compare : ∀ n : ℕ, 3 ≤ n → (Real.log n) / (n : ℝ)^(10.5 : ℝ) ≤ 1 / (n : ℝ)^(10 : ℝ) := by
              intro n hn
              have h_log_le : Real.log n ≤ n ^ (0.5 : ℝ) := by
                have := Real.log_le_sub_one_of_pos ( by positivity : 0 < ( n : ℝ ) ^ ( 0.5 : ℝ ) / 2 );
                rw [ Real.log_div ( by positivity ) ( by positivity ), Real.log_rpow ( by positivity ) ] at this;
                have := Real.log_two_lt_d9 ; norm_num at * ; linarith;
              rw [ div_le_div_iff₀ ] <;> first | positivity | convert mul_le_mul_of_nonneg_right h_log_le <| Real.rpow_nonneg ( Nat.cast_nonneg n ) 10 using 1 ; rw [ ← Real.rpow_add <| by positivity ] ; norm_num;
            rw [ ← summable_nat_add_iff 3 ];
            exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( Real.log_nonneg ( by norm_cast; linarith ) ) ( by positivity ) ) ( fun n => h_compare _ ( by linarith ) ) ( by simpa using summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_pow.2 <| by norm_num );
          simpa only [ mul_div_assoc ] using Summable.mul_left _ ( h_summable.comp_injective Subtype.coe_injective );
      linarith [ show rho_one = 1 / 25 by rfl, show weight_upper_bound t 2 < 1 / 100000 by exact lt_of_lt_of_le ( weight_n2_bound t ht ) ( by norm_num ), show ∑' n : { k : ℕ // 3 ≤ k }, 2 * Real.log ( n : ℝ ) / ( n : ℝ ) ^ ( 10.5 : ℝ ) < 1 / 1000 by exact lt_of_lt_of_le ( tail_sum_bound ) ( by norm_num ) ]

/-- Specialized version for t_rkhs_cap = 40 -/
theorem weight_sum_at_tcap :
    ∑' n : ℕ, weight_upper_bound t_rkhs_cap n ≤ rho_one := by
      convert weight_sum_le_rho_one t_rkhs_cap ( by norm_num : ( 1 : ℝ ) ≤ 40 ) using 1