/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ba71a35a-14e1-46d0-a51c-002860d03561
-/

/-
We defined the weight upper bound function and proved that the sum of weights is bounded by 1/25 for t ≥ 1, and specifically for t = 40.

Key results:
- `exp_decay_bound`: Exponential decay of the weight function for n ≥ 3.
- `weight_bound_large_n`: Bound on individual weights for n ≥ 3.
- `tail_sum_bound`: The tail sum (n ≥ 3) is small (< 0.001).
- `weight_n2_bound`: The term for n = 2 is small (< 0.00001).
- `weight_sum_le_rho_one`: The total sum is ≤ 1/25 for any t ≥ 1.
- `weight_sum_at_tcap`: The specific bound for the RKHS cap parameter t = 40.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Open namespaces and scoped notation.
-/
open scoped BigOperators
open Finset Real Nat

/-
Define rho_one as 1/25.
-/
noncomputable def rho_one : ℝ := 1 / 25

/-
Define t_rkhs_cap as 40.
-/
noncomputable def t_rkhs_cap : ℝ := 40

/-
Define four_pi_sq as 4 * pi^2.
-/
noncomputable def four_pi_sq : ℝ := 4 * Real.pi ^ 2

/-
Define the weight upper bound function.
-/
noncomputable def weight_upper_bound (t : ℝ) (n : ℕ) : ℝ :=
  if n < 2 then 0
  else 2 * Real.log n / Real.sqrt n * Real.exp (-four_pi_sq * t * (Real.log n)^2)

/-
Exponential decay bound for n >= 3 and t >= 1.
-/
lemma exp_decay_bound {n : ℕ} (hn : 3 ≤ n) (t : ℝ) (ht : 1 ≤ t) :
    Real.exp (-four_pi_sq * t * (Real.log n)^2) ≤ (n : ℝ)^(-10 : ℝ) := by
      -- Since $4\pi^2 \approx 39.5 > 10$, we have $4\pi^2 * t * (\log n)^2 \geq 10 * \log n$.
      have h_exp_bound : 4 * Real.pi ^ 2 * t * (Real.log n) ^ 2 ≥ 10 * Real.log n := by
        -- Since $4\pi^2 \approx 39.5 > 10$, we have $4\pi^2 * t * (\log n)^2 \geq 10 * \log n$ for $n \geq 3$.
        have h_pi_approx : 4 * Real.pi ^ 2 > 10 := by
          nlinarith [ Real.pi_gt_three ];
        nlinarith [ show 1 ≤ Real.log n from by rw [ Real.le_log_iff_exp_le ( by positivity ) ] ; exact Real.exp_one_lt_d9.le.trans <| by norm_num; linarith [ show ( n :ℝ ) ≥ 3 by norm_cast ], show 0 ≤ 4 * Real.pi ^ 2 * Real.log n ^ 2 by positivity, show 0 ≤ 4 * Real.pi ^ 2 * t * Real.log n ^ 2 by positivity ];
      rw [ Real.rpow_def_of_pos ( by positivity ) ] ; norm_num [ four_pi_sq ] ; linarith;

/-
Individual weight bound for n >= 3.
-/
lemma weight_bound_large_n {n : ℕ} (hn : 3 ≤ n) (t : ℝ) (ht : 1 ≤ t) :
    weight_upper_bound t n ≤ 2 * Real.log n / (n : ℝ)^(10.5 : ℝ) := by
      -- Apply the exponential decay bound to the weight_upper_bound function.
      have h_exp_decay : Real.exp (-four_pi_sq * t * (Real.log n)^2) ≤ (n : ℝ)^(-10 : ℝ) := by
        exact?;
      unfold weight_upper_bound;
      split_ifs <;> try linarith;
      convert mul_le_mul_of_nonneg_left h_exp_decay ( show 0 ≤ 2 * Real.log n / Real.sqrt n by positivity ) using 1 ; ring;
      norm_num [ Real.sqrt_eq_rpow, Real.rpow_neg ( Nat.cast_nonneg _ ), Real.rpow_add ( Nat.cast_pos.mpr ( by linarith : 0 < n ) ) ];
      rw [ show ( 21 / 2 : ℝ ) = 1 / 2 + 10 by norm_num, Real.rpow_add ] <;> norm_num ; ring ; positivity

/-
Tail sum convergence bound.
-/
lemma tail_sum_bound :
    ∑' n : {k : ℕ // 3 ≤ k}, (2 * Real.log n / (n : ℝ)^(10.5 : ℝ)) < 0.001 := by
      have h_sum_bound : ∑' n : { k : ℕ // 3 ≤ k }, (2 * Real.log n) / (n : ℝ) ^ (10.5 : ℝ) ≤ 2 * ∑' n : ℕ, (1 : ℝ) / (n + 3) ^ (9.5 : ℝ) := by
        -- We'll use the fact that $\sum_{n=3}^{\infty} \frac{\log n}{n^{10.5}}$ is bounded above by $\sum_{n=3}^{\infty} \frac{1}{n^{9.5}}$.
        have h_sum_bound : ∑' n : ℕ, (Real.log (n + 3) : ℝ) / ((n + 3 : ℝ) ^ (10.5 : ℝ)) ≤ ∑' n : ℕ, (1 : ℝ) / ((n + 3 : ℝ) ^ (9.5 : ℝ)) := by
          have h_sum_log : ∀ n : ℕ, (Real.log (n + 3)) / ((n + 3 : ℝ) ^ (10.5 : ℝ)) ≤ (1 : ℝ) / ((n + 3 : ℝ) ^ (9.5 : ℝ)) := by
            intro n
            have h_log : Real.log (n + 3) ≤ (n + 3 : ℝ) := by
              exact le_trans ( Real.log_le_sub_one_of_pos ( by linarith ) ) ( by linarith );
            rw [ div_le_div_iff₀ ] <;> try positivity;
            exact le_trans ( mul_le_mul_of_nonneg_right h_log <| by positivity ) <| by rw [ ← Real.rpow_one_add' ] <;> norm_num ; linarith;
          refine' Summable.tsum_le_tsum h_sum_log _ _;
          · exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( Real.log_nonneg ( by linarith ) ) ( by positivity ) ) h_sum_log ( by simpa using summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_rpow.2 <| by norm_num );
          · exact_mod_cast summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_rpow.2 <| by norm_num;
        convert mul_le_mul_of_nonneg_left h_sum_bound zero_le_two using 1;
        rw [ ← tsum_mul_left ];
        rw [ ← Equiv.tsum_eq ( Equiv.ofBijective ( fun n : ℕ => ⟨ n + 3, by linarith ⟩ : ℕ → { k : ℕ // 3 ≤ k } ) ⟨ fun a => ?_, fun a => ?_ ⟩ ) ] <;> norm_num [ mul_div_assoc ];
        exact ⟨ a.val - 3, by rcases a with ⟨ _ | _ | _ | a, ha ⟩ <;> trivial ⟩;
      -- We'll use the fact that $\sum_{n=3}^{\infty} \frac{1}{n^{9.5}}$ is a convergent p-series with $p = 9.5 > 1$.
      have h_pseries : ∑' n : ℕ, (1 : ℝ) / (n + 3) ^ (9.5 : ℝ) ≤ ∑' n : ℕ, (1 : ℝ) / (n + 3) ^ 9 := by
        refine' Summable.tsum_le_tsum _ _ _ <;> norm_num +zetaDelta at *;
        · exact fun n => inv_anti₀ ( by positivity ) ( by exact le_trans ( by norm_num ) ( Real.rpow_le_rpow_of_exponent_le ( by linarith ) ( show ( 19 : ℝ ) / 2 ≥ 9 by norm_num ) ) );
        · exact_mod_cast summable_nat_add_iff 3 |>.2 <| Real.summable_nat_rpow_inv.2 <| by norm_num;
        · exact_mod_cast summable_nat_add_iff 3 |>.2 <| Real.summable_nat_pow_inv.2 <| by norm_num;
      have h_pseries_eval : ∑' n : ℕ, (1 : ℝ) / (n + 3) ^ 9 ≤ ∑' n : ℕ, (1 : ℝ) / (n + 3) ^ 2 * (1 / 3 ^ 7) := by
        field_simp;
        refine' Summable.tsum_le_tsum _ _ _;
        · intro i; rw [ div_le_div_iff₀ ] <;> first | positivity | ring_nf;
          nlinarith [ pow_nonneg ( Nat.cast_nonneg i : ( 0 : ℝ ) ≤ i ) 2, pow_nonneg ( Nat.cast_nonneg i : ( 0 : ℝ ) ≤ i ) 3, pow_nonneg ( Nat.cast_nonneg i : ( 0 : ℝ ) ≤ i ) 4, pow_nonneg ( Nat.cast_nonneg i : ( 0 : ℝ ) ≤ i ) 5, pow_nonneg ( Nat.cast_nonneg i : ( 0 : ℝ ) ≤ i ) 6 ];
        · exact_mod_cast summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_pow.2 <| by norm_num;
        · exact Summable.of_nonneg_of_le ( fun n => by positivity ) ( fun n => by rw [ div_le_div_iff₀ ] <;> norm_cast <;> ring <;> nlinarith ) ( summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_pow.2 one_lt_two );
      have h_pseries_eval : ∑' n : ℕ, (1 : ℝ) / (n + 3) ^ 2 = Real.pi ^ 2 / 6 - 1 - 1 / 4 := by
        convert HasSum.tsum_eq ( hasSum_nat_add_iff' 3 |>.2 <| hasSum_zeta_two ) using 1 <;> norm_num;
        ring;
      norm_num [ tsum_mul_right ] at *;
      -- We'll use the fact that $\pi \approx 3.14$ to estimate the value.
      have h_pi_approx : Real.pi < 3.15 := by
        exact?;
      norm_num at h_pi_approx ; nlinarith [ Real.pi_gt_three ]

/-
Bound for n = 2.
-/
lemma weight_n2_bound (t : ℝ) (ht : 1 ≤ t) :
    weight_upper_bound t 2 < 0.00001 := by
      -- Calculate the weight for n = 2 using the given formula.
      have h_weight_2 : weight_upper_bound t 2 = 2 * Real.log 2 / Real.sqrt 2 * Real.exp (-four_pi_sq * t * (Real.log 2)^2) := by
        unfold weight_upper_bound; norm_num;
      -- We'll use the fact that $\exp(-x)$ is very small for large $x$.
      have h_exp_small : Real.exp (-four_pi_sq * t * (Real.log 2)^2) ≤ Real.exp (-39 * (Real.log 2)^2) := by
        have h_exp_small : four_pi_sq ≥ 39 := by
          -- We'll use the fact that $\pi \approx 3.14$ to show that $4\pi^2 \geq 39$.
          have h_pi_approx : Real.pi > 3.14 := by
            exact?;
          exact le_trans ( by norm_num ) ( mul_le_mul_of_nonneg_left ( pow_le_pow_left₀ ( by norm_num ) h_pi_approx.le 2 ) zero_le_four );
        exact Real.exp_le_exp.mpr ( by nlinarith [ show 0 ≤ Real.log 2 ^ 2 * t by positivity ] );
      -- We'll use the fact that $\exp(-39 * (\log 2)^2)$ is very small.
      have h_exp_small_val : Real.exp (-39 * (Real.log 2)^2) < 1 / 1000000 := by
        rw [ ← Real.log_lt_log_iff ( by positivity ) ( by positivity ), Real.log_div ] <;> norm_num;
        rw [ show ( 1000000 : ℝ ) = 2 ^ 6 * 5 ^ 6 by norm_num, Real.log_mul, Real.log_pow, Real.log_pow ] <;> norm_num;
        rw [ show ( 5 : ℝ ) = 2 ^ 2 * 1.25 by norm_num, Real.log_mul, Real.log_pow ] <;> ring <;> norm_num;
        have := Real.log_two_gt_d9 ; norm_num at * ; nlinarith [ Real.log_le_sub_one_of_pos ( show 0 < 5 / 4 by norm_num ), Real.log_pos ( show 1 < 5 / 4 by norm_num ) ];
      exact h_weight_2.symm ▸ by exact lt_of_le_of_lt ( mul_le_mul_of_nonneg_left h_exp_small ( by positivity ) ) ( by exact lt_of_le_of_lt ( mul_le_mul_of_nonneg_right ( show 2 * Real.log 2 / Real.sqrt 2 ≤ 1 by rw [ div_le_iff₀ <| by positivity ] ; have := Real.log_two_lt_d9; norm_num1 at *; nlinarith [ Real.sqrt_nonneg 2, Real.sq_sqrt zero_le_two ] ) <| by positivity ) <| by norm_num at *; linarith ) ;

/-
The sum of weight upper bounds is less than 1/25 for t >= 1.
-/
theorem weight_sum_le_rho_one (t : ℝ) (ht : 1 ≤ t) :
    ∑' n : ℕ, weight_upper_bound t n ≤ rho_one := by
      have h_split : (∑' n : ℕ, weight_upper_bound t n) = weight_upper_bound t 0 + weight_upper_bound t 1 + weight_upper_bound t 2 + ∑' n : {k : ℕ // 3 ≤ k}, weight_upper_bound t ↑n := by
        rw [ ← Summable.sum_add_tsum_nat_add 3 ];
        · rw [ ← Equiv.tsum_eq ( Equiv.ofBijective ( fun n : ℕ => ⟨ n + 3, by linarith ⟩ : ℕ → { k : ℕ // 3 ≤ k } ) ⟨ fun a => _, fun a => _ ⟩ ) ] <;> norm_num [ Finset.sum_range_succ ];
          exact fun a ha => ⟨ a - 3, Nat.sub_add_cancel ha ⟩;
        · rw [ ← summable_nat_add_iff 3 ];
          have h_summable : Summable (fun n : ℕ => 2 * Real.log (n + 3) / (n + 3 : ℝ)^(10.5 : ℝ)) := by
            -- We can compare our series with the convergent p-series $\sum_{n=3}^{\infty} \frac{1}{n^{10}}$.
            have h_compare : ∀ n : ℕ, (2 * Real.log (n + 3) / (n + 3 : ℝ)^(10.5 : ℝ)) ≤ (2 / (n + 3 : ℝ)^(9.5 : ℝ)) := by
              intro n; rw [ div_le_div_iff₀ ( by positivity ) ( by positivity ) ] ; ring_nf;
              rw [ show ( 21 / 2 : ℝ ) = ( 19 / 2 : ℝ ) + 1 by norm_num, Real.rpow_add ] <;> norm_num <;> try linarith;
              nlinarith [ Real.log_le_sub_one_of_pos ( by positivity : 0 < ( 3 : ℝ ) + n ), Real.rpow_pos_of_pos ( by positivity : 0 < ( 3 : ℝ ) + n ) ( 19 / 2 : ℝ ) ];
            exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( mul_nonneg zero_le_two ( Real.log_nonneg ( by linarith ) ) ) ( by positivity ) ) h_compare ( Summable.mul_left _ <| by simpa using summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_rpow.2 <| by norm_num );
          refine' .of_nonneg_of_le ( fun n => _ ) ( fun n => _ ) h_summable;
          · unfold weight_upper_bound; norm_num;
            exact mul_nonneg ( div_nonneg ( mul_nonneg zero_le_two ( Real.log_nonneg ( by linarith ) ) ) ( Real.sqrt_nonneg _ ) ) ( Real.exp_nonneg _ );
          · convert weight_bound_large_n ( show 3 ≤ n + 3 by linarith ) t ht using 1 ; norm_cast;
      -- Apply the bounds for n < 2, n = 2, and n ≥ 3.
      have h_bounds : weight_upper_bound t 0 = 0 ∧ weight_upper_bound t 1 = 0 ∧ weight_upper_bound t 2 < 0.00001 ∧ ∑' n : {k : ℕ // 3 ≤ k}, weight_upper_bound t ↑n ≤ ∑' n : {k : ℕ // 3 ≤ k}, (2 * Real.log n / (n : ℝ)^(10.5 : ℝ)) := by
        refine' ⟨ _, _, _, Summable.tsum_le_tsum _ _ _ ⟩;
        any_goals unfold weight_upper_bound; norm_num;
        · convert weight_n2_bound t ht using 1;
          · unfold weight_upper_bound; norm_num;
          · norm_num;
        · intro n hn; rw [ if_neg ( by linarith ) ] ; convert weight_bound_large_n hn t ht using 1 ; norm_num [ Real.sqrt_eq_rpow, ← Real.rpow_mul ] ; ring;
          · unfold weight_upper_bound; norm_num [ ← Real.sqrt_eq_rpow ] ; ring;
            rw [ if_neg ( by linarith ) ];
          · norm_num;
        · have h_summable : Summable (fun n : ℕ => if n < 3 then 0 else 2 * Real.log n / (n : ℝ)^(10.5 : ℝ)) := by
            -- We'll use the fact that if the denominator grows faster than the numerator, the series converges.
            have h_series_conv : Summable (fun n : ℕ => (2 * Real.log n) / (n : ℝ)^(10.5 : ℝ)) := by
              have h_summable : Summable (fun n : ℕ => Real.log n / (n : ℝ)^(10.5 : ℝ)) := by
                -- We can compare our series with the convergent p-series $\sum_{n=3}^\infty \frac{1}{n^{10.5 - \epsilon}}$ for any $\epsilon > 0$.
                have h_compare : ∀ ε > 0, ∃ C > 0, ∀ n : ℕ, 3 ≤ n → Real.log n / (n : ℝ)^(10.5 : ℝ) ≤ C / (n : ℝ)^(10.5 - ε : ℝ) := by
                  intro ε hε_pos
                  obtain ⟨C, hC_pos, hC⟩ : ∃ C > 0, ∀ n : ℕ, 3 ≤ n → Real.log n ≤ C * (n : ℝ)^ε := by
                    use 1 / ε, by positivity, fun n hn => by have := Real.log_le_sub_one_of_pos ( by positivity : 0 < ( n : ℝ ) ^ ε ) ; rw [ Real.log_rpow ( by positivity ) ] at this; nlinarith [ show ( n : ℝ ) ^ ε > 0 by positivity, mul_div_cancel₀ 1 hε_pos.ne' ] ;
                  use C, hC_pos;
                  intro n hn; rw [ div_le_div_iff₀ ( by positivity ) ( by positivity ) ] ; convert mul_le_mul_of_nonneg_right ( hC n hn ) ( by positivity : 0 ≤ ( n : ℝ ) ^ ( 10.5 - ε ) ) using 1 ; rw [ mul_assoc, ← Real.rpow_add ( by positivity ) ] ; ring;
                obtain ⟨ C, hC₀, hC ⟩ := h_compare 1 zero_lt_one;
                rw [ ← summable_nat_add_iff 3 ];
                exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( Real.log_nonneg ( by norm_cast; linarith ) ) ( by positivity ) ) ( fun n => hC _ ( by linarith ) ) ( Summable.mul_left _ <| by simpa using summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_rpow.2 <| by norm_num );
              simpa only [ mul_div_assoc ] using h_summable.mul_left 2;
            rw [ ← summable_nat_add_iff 3 ] at * ; aesop;
          have h_summable : Summable (fun n : {k : ℕ // 3 ≤ k} => 2 * Real.log n / (n : ℝ)^(10.5 : ℝ)) := by
            convert h_summable.comp_injective ( show Function.Injective ( fun n : { k : ℕ // 3 ≤ k } => ( n : ℕ ) ) from fun a b h => by aesop ) using 1;
            grind;
          refine' .of_nonneg_of_le ( fun n => _ ) ( fun n => _ ) h_summable;
          · split_ifs <;> positivity;
          · split_ifs <;> norm_num;
            · linarith [ n.2 ];
            · convert weight_bound_large_n ( show 3 ≤ ( n : ℕ ) from n.2 ) t ht using 1;
              · unfold weight_upper_bound; aesop;
              · norm_num;
        · have h_summable : Summable (fun n : ℕ => (2 * Real.log n) / (n : ℝ)^(10.5 : ℝ)) := by
            have h_summable : Summable (fun n : ℕ => Real.log n / (n : ℝ)^(10.5 : ℝ)) := by
              -- We can compare our series with the convergent p-series $\sum_{n=3}^\infty \frac{1}{n^{10.5 - \epsilon}}$ for any $\epsilon > 0$.
              have h_compare : ∀ ε > 0, ∃ C > 0, ∀ n : ℕ, 3 ≤ n → Real.log n / (n : ℝ)^(10.5 : ℝ) ≤ C / (n : ℝ)^(10.5 - ε : ℝ) := by
                intro ε hε_pos
                obtain ⟨C, hC_pos, hC⟩ : ∃ C > 0, ∀ n : ℕ, 3 ≤ n → Real.log n ≤ C * (n : ℝ)^ε := by
                  use 1 / ε, by positivity, fun n hn => by have := Real.log_le_sub_one_of_pos ( by positivity : 0 < ( n : ℝ ) ^ ε ) ; rw [ Real.log_rpow ( by positivity ) ] at this; nlinarith [ show ( n : ℝ ) ^ ε > 0 by positivity, mul_div_cancel₀ 1 hε_pos.ne' ] ;
                use C, hC_pos;
                intro n hn; rw [ div_le_div_iff₀ ( by positivity ) ( by positivity ) ] ; convert mul_le_mul_of_nonneg_right ( hC n hn ) ( by positivity : 0 ≤ ( n : ℝ ) ^ ( 10.5 - ε ) ) using 1 ; rw [ mul_assoc, ← Real.rpow_add ( by positivity ) ] ; ring;
              obtain ⟨ C, hC₀, hC ⟩ := h_compare 1 zero_lt_one;
              rw [ ← summable_nat_add_iff 3 ];
              exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( Real.log_nonneg ( by norm_cast; linarith ) ) ( by positivity ) ) ( fun n => hC _ ( by linarith ) ) ( Summable.mul_left _ <| by simpa using summable_nat_add_iff 3 |>.2 <| Real.summable_one_div_nat_rpow.2 <| by norm_num );
            simpa only [ mul_div_assoc ] using h_summable.mul_left 2;
          exact h_summable.comp_injective Subtype.coe_injective;
      linarith [ tail_sum_bound, show rho_one = 1 / 25 by rfl ]

/-
Specialized version for t_rkhs_cap = 40.
-/
theorem weight_sum_at_tcap :
    ∑' n : ℕ, weight_upper_bound t_rkhs_cap n ≤ rho_one := by
      convert weight_sum_le_rho_one t_rkhs_cap ( by norm_num : 1 ≤ ( 40 : ℝ ) ) using 1