/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4ec30af1-6d92-4140-9767-7954aafaeb0c
-/

/-
We have successfully proven that the imaginary part of the trigamma function is negative for any complex number with positive real and imaginary parts. The proof relies on expressing the imaginary part of the trigamma function as a series of negative terms.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat Classical Pointwise
open Real Complex MeasureTheory Set


def digamma (z : ℂ) : ℂ := (deriv Complex.Gamma z) / (Complex.Gamma z)
def trigamma (z : ℂ) : ℂ := ∑' n : ℕ, 1 / (z + n)^2

theorem im_one_div_sq_add_nat_neg {z : ℂ} (n : ℕ) (hz : 0 < z.re) (hzi : 0 < z.im) :
    (1 / (z + n)^2).im < 0 := by
  norm_num [sq, Complex.normSq, Complex.div_im]
  exact add_neg
    (mul_neg_of_pos_of_neg (div_pos (by positivity) (by positivity))
      (div_neg_of_neg_of_pos (by linarith) (by positivity)))
    (mul_neg_of_neg_of_pos (div_neg_of_neg_of_pos (by linarith) (by positivity))
      (div_pos (by positivity) (by positivity)))

lemma summable_trigamma_series {z : ℂ} (hz : 0 < z.re) :
    Summable (fun n : ℕ => 1 / (z + n)^2) := by
  have h_comparison : ∃ N : ℕ, ∀ n ≥ N, ‖1 / (z + n)^2‖ ≤ 1 / n^2 := by
    norm_num [Complex.normSq, Complex.sq_norm]
    exact ⟨Nat.ceil (2 * |z.re| + 2 * |z.im| + 1), fun n hn =>
      inv_anti₀
        (sq_pos_of_pos <| Nat.cast_pos.mpr <| Nat.pos_of_ne_zero <| by
          rintro rfl; norm_num at hn; linarith [abs_nonneg z.re, abs_nonneg z.im])
        (by cases abs_cases z.re <;> cases abs_cases z.im <;>
          nlinarith [Nat.ceil_le.mp hn])⟩
  have h_abs_summable : Summable (fun n : ℕ => ‖1 / (z + n)^2‖) := by
    rw [← summable_nat_add_iff h_comparison.choose]
    exact Summable.of_nonneg_of_le (fun _ => norm_nonneg _) (fun n =>
      h_comparison.choose_spec _ (Nat.le_add_left _ _))
      (by
        simpa using
          summable_nat_add_iff h_comparison.choose |>.2
            (Real.summable_one_div_nat_pow.2 one_lt_two))
  exact h_abs_summable.of_norm

lemma im_trigamma_eq_tsum_im {z : ℂ} (hz : 0 < z.re) :
    (trigamma z).im = ∑' n : ℕ, (1 / (z + n)^2).im := by
  have hsum : Summable (fun n : ℕ => 1 / (z + n)^2) := summable_trigamma_series hz
  simpa [trigamma] using (Complex.im_tsum hsum)

/-
The imaginary part of the trigamma function is negative for z with positive real and imaginary parts.
-/
theorem im_trigamma_neg {z : ℂ} (hz : 0 < z.re) (hzi : 0 < z.im) :
    (trigamma z).im < 0 := by
      rw [ im_trigamma_eq_tsum_im hz ];
      -- By the properties of summability and the fact that the imaginary part of each term is negative, the sum of the imaginary parts is also strictly negative.
      have h_im_sum_neg : Summable (fun n : ℕ => (1 / (z + n)^2).im) ∧ ∃ n : ℕ, (1 / (z + n)^2).im < 0 := by
        exact ⟨ by simpa using Complex.imCLM.summable ( summable_trigamma_series hz ), 0, by simpa using im_one_div_sq_add_nat_neg 0 hz hzi ⟩;
      obtain ⟨ hn_summable, n, hn_neg ⟩ := h_im_sum_neg;
      -- Since the imaginary part of each term is negative, the sum of the imaginary parts is strictly negative.
      have h_im_sum_neg : ∑' n : ℕ, (1 / (z + n)^2).im = ∑' n : ℕ, |(1 / (z + n)^2).im| * (-1) := by
        exact tsum_congr fun n => by rw [ abs_of_neg ( im_one_div_sq_add_nat_neg n hz hzi ) ] ; ring;
      simp_all +decide [ tsum_neg, tsum_mul_right ];
      exact lt_of_lt_of_le ( abs_pos.mpr hn_neg.ne ) ( Summable.le_tsum ( show Summable _ from Summable.abs hn_summable ) n ( fun _ _ => abs_nonneg _ ) )