/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f2dbbad1-3f72-4aff-b365-ab1329cfad2f
-/

/-
I have proven the two requested lemmas: `GammaSeq_uniform_bound_integrable` and `TendstoLocallyUniformlyOn_div`.
For `GammaSeq_uniform_bound_integrable`, I split the integral into two parts (0 to 1 and 1 to infinity) and used comparison with `x^(a-1)` and `x^b` respectively, along with the properties of the Gamma function.
For `TendstoLocallyUniformlyOn_div`, I first proved helper lemmas `TendstoLocallyUniformlyOn_inv` and `TendstoLocallyUniformlyOn_mul` (the latter using `Metric.tendstoLocallyUniformlyOn_iff` and local boundedness), and then combined them to prove the quotient rule.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped Real
open scoped Pointwise
open scoped BigOperators
open Real Complex MeasureTheory Set

lemma GammaSeq_uniform_bound_integrable (a b : ℝ) (ha : 0 < a) :
    MeasureTheory.IntegrableOn
      (fun x : ℝ => Real.exp (-x) * (if x ≤ 1 then x ^ (a - 1) else x ^ (b - 1)))
      (Set.Ioi 0) := by
        -- We'll use the fact that if the denominator grows faster than the numerator, the integral converges.
        have h_integrable : MeasureTheory.IntegrableOn (fun x => Real.exp (-x) * x ^ (a - 1)) (Set.Ioc 0 1) ∧ MeasureTheory.IntegrableOn (fun x => Real.exp (-x) * x ^ (b - 1)) (Set.Ioi 1) := by
          constructor;
          · have h_integrable : MeasureTheory.IntegrableOn (fun x => x ^ (a - 1)) (Set.Ioc (0 : ℝ) 1) := by
              exact ( intervalIntegral.intervalIntegrable_rpow' ( by linarith ) ).1;
            refine' h_integrable.mono' _ _;
            · exact MeasureTheory.AEStronglyMeasurable.mul ( Continuous.aestronglyMeasurable ( by continuity ) ) h_integrable.aestronglyMeasurable;
            · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with x hx using by rw [ Real.norm_of_nonneg ( mul_nonneg ( Real.exp_nonneg _ ) ( Real.rpow_nonneg hx.1.le _ ) ) ] ; exact mul_le_of_le_one_left ( Real.rpow_nonneg hx.1.le _ ) ( Real.exp_le_one_iff.mpr <| by linarith [ hx.1, hx.2 ] ) ;
          · -- Since $x^{b-1} \leq x^{b}$ for $x > 1$, we can bound the integrand.
            have h_bound : ∀ x ∈ Set.Ioi 1, Real.exp (-x) * x ^ (b - 1) ≤ Real.exp (-x) * x ^ (b) := by
              exact fun x hx => mul_le_mul_of_nonneg_left ( Real.rpow_le_rpow_of_exponent_le hx.out.le ( by linarith ) ) ( Real.exp_nonneg _ );
            have h_integrable : MeasureTheory.IntegrableOn (fun x => Real.exp (-x) * x ^ b) (Set.Ioi 1) := by
              have h_integrable : MeasureTheory.IntegrableOn (fun x => Real.exp (-x) * x ^ (⌈b⌉₊ : ℝ)) (Set.Ioi 1) := by
                have h_gamma : ∫ x in Set.Ioi 0, Real.exp (-x) * x ^ (⌈b⌉₊ : ℝ) = Real.Gamma (⌈b⌉₊ + 1) := by
                  rw [ Real.Gamma_eq_integral ( by positivity ) ];
                  norm_num;
                exact MeasureTheory.IntegrableOn.mono_set ( by exact ( by contrapose! h_gamma; rw [ MeasureTheory.integral_undef h_gamma ] ; positivity ) ) ( Set.Ioi_subset_Ioi zero_le_one );
              refine' h_integrable.mono' _ _;
              · exact Measurable.aestronglyMeasurable ( by exact Measurable.mul ( Real.continuous_exp.measurable.comp measurable_neg ) ( measurable_id.pow_const _ ) );
              · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioi ] with x hx using by rw [ Real.norm_of_nonneg ( mul_nonneg ( Real.exp_pos _ |> le_of_lt ) ( Real.rpow_nonneg ( by linarith [ hx.out ] ) _ ) ) ] ; exact mul_le_mul_of_nonneg_left ( Real.rpow_le_rpow_of_exponent_le ( by linarith [ hx.out ] ) ( Nat.le_ceil _ ) ) ( Real.exp_pos _ |> le_of_lt ) ;
            refine' h_integrable.mono' _ _;
            · exact Measurable.aestronglyMeasurable ( by exact Measurable.mul ( Real.continuous_exp.measurable.comp measurable_neg ) ( measurable_id.pow_const _ ) );
            · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioi ] with x hx using by rw [ Real.norm_of_nonneg ( mul_nonneg ( Real.exp_pos _ |> le_of_lt ) ( Real.rpow_nonneg ( by linarith [ hx.out ] ) _ ) ) ] ; exact h_bound x hx;
        have h_integrable : MeasureTheory.IntegrableOn (fun x => Real.exp (-x) * (if x ≤ 1 then x ^ (a - 1) else x ^ (b - 1))) (Set.Ioc 0 1 ∪ Set.Ioi 1) := by
          apply MeasureTheory.IntegrableOn.union;
          · exact h_integrable.1.congr_fun ( fun x hx => by aesop ) measurableSet_Ioc;
          · exact h_integrable.2.congr_fun ( fun x hx => by rw [ if_neg hx.out.not_le ] ) measurableSet_Ioi;
        aesop

lemma eventually_norm_ge_of_tendstoLocallyUniformlyOn {ι : Type*} [Preorder ι]
    {G : ι → ℂ → ℂ} {g : ℂ → ℂ} {S : Set ℂ} {x : ℂ}
    (hx : x ∈ S)
    (hg : TendstoLocallyUniformlyOn G g Filter.atTop S)
    (hg_cont : ContinuousOn g S)
    (hg_ne_zero : g x ≠ 0) :
    ∃ U ∈ nhdsWithin x S, ∀ᶠ n in Filter.atTop, ∀ z ∈ U, ‖G n z‖ ≥ ‖g x‖ / 2 := by
      -- Since `g` is continuous at `x` within `S`, there exists a neighborhood `U₁` of `x` within `S` such that for all `z ∈ U₁`, `‖g z - g x‖ < ‖g x‖ / 4`.
      obtain ⟨U₁, hU₁⟩ : ∃ U₁ ∈ nhdsWithin x S, ∀ z ∈ U₁, ‖g z - g x‖ < ‖g x‖ / 4 := by
        replace := hg_cont x hx;
        exact ⟨ _, this.eventually ( Metric.ball_mem_nhds _ ( by positivity ) ), fun z hz => hz ⟩;
      -- Since `G` converges locally uniformly to `g`, there exists a neighborhood `U₂` of `x` within `S` such that `G` converges uniformly to `g` on `U₂`.
      obtain ⟨U₂, hU₂⟩ : ∃ U₂ ∈ nhdsWithin x S, ∀ᶠ n in Filter.atTop, ∀ z ∈ U₂, ‖G n z - g z‖ < ‖g x‖ / 4 := by
        rw [ Metric.tendstoLocallyUniformlyOn_iff ] at hg;
        simpa only [ dist_comm, norm_sub_rev ] using hg ( ‖g x‖ / 4 ) ( div_pos ( norm_pos_iff.mpr hg_ne_zero ) zero_lt_four ) x hx;
      use U₁ ∩ U₂;
      refine' ⟨ _, _ ⟩;
      · exact Filter.inter_mem hU₁.1 hU₂.1;
      · filter_upwards [ hU₂.2 ] with n hn z hz using by have := norm_sub_le ( G n z ) ( G n z - g z ) ; have := norm_sub_le ( g z ) ( g z - g x ) ; norm_num at * ; linarith [ hU₁.2 z hz.1, hn z hz.2 ] ;

lemma TendstoLocallyUniformlyOn_inv {ι : Type*} [Preorder ι] {G : ι → ℂ → ℂ} {g : ℂ → ℂ} {S : Set ℂ}
    (hg : TendstoLocallyUniformlyOn G g Filter.atTop S)
    (hg_cont : ContinuousOn g S)
    (hg_ne_zero : ∀ z ∈ S, g z ≠ 0) :
    TendstoLocallyUniformlyOn (fun i z => (G i z)⁻¹) (fun z => (g z)⁻¹) Filter.atTop S := by
      have h_uniform_converge : ∀ x ∈ S, ∃ U ∈ nhdsWithin x S, ∃ C > 0, ∀ᶠ n in Filter.atTop, ∀ z ∈ U, ‖G n z‖ ≥ C ∧ ‖g z‖ ≥ C := by
        intro x hx;
        obtain ⟨ U, hU₁, hU₂ ⟩ := eventually_norm_ge_of_tendstoLocallyUniformlyOn hx hg hg_cont ( hg_ne_zero x hx );
        -- Since $g$ is continuous and nonzero on $S$, we can find a neighborhood $V$ of $x$ within $S$ such that $‖g z‖ ≥ ‖g x‖ / 2$ for all $z ∈ V$.
        obtain ⟨V, hV₁, hV₂⟩ : ∃ V ∈ nhdsWithin x S, ∀ z ∈ V, ‖g z‖ ≥ ‖g x‖ / 2 := by
          have := hg_cont x hx;
          have := this.norm;
          have := this.eventually ( le_mem_nhds ( half_lt_self ( norm_pos_iff.mpr ( hg_ne_zero x hx ) ) ) ) ; aesop;
        exact ⟨ U ∩ V, Filter.inter_mem hU₁ hV₁, ‖g x‖ / 2, half_pos ( norm_pos_iff.mpr ( hg_ne_zero x hx ) ), by filter_upwards [ hU₂ ] with n hn z hz using ⟨ hn z hz.1, hV₂ z hz.2 ⟩ ⟩;
      rw [ Metric.tendstoLocallyUniformlyOn_iff ] at *;
      intro ε εpos x hx
      obtain ⟨U, hU_nhds, C, hC_pos, hC⟩ := h_uniform_converge x hx
      obtain ⟨δ, hδ_pos, hδ⟩ : ∃ δ > 0, δ < C ∧ δ < ε * C^2 := by
        exact ⟨ Min.min ( C / 2 ) ( ε * C ^ 2 / 2 ), lt_min ( half_pos hC_pos ) ( half_pos ( mul_pos εpos ( sq_pos_of_pos hC_pos ) ) ), min_lt_of_left_lt ( half_lt_self hC_pos ), min_lt_of_right_lt ( half_lt_self ( mul_pos εpos ( sq_pos_of_pos hC_pos ) ) ) ⟩
      obtain ⟨t, ht_nhds, ht⟩ := hg δ hδ_pos x hx
      use t ∩ U
      simp_all +decide [ dist_eq_norm ];
      filter_upwards [ ht, hC ] with n hn hn' y hy hy' ; rw [ inv_sub_inv ] <;> simp_all +decide [ norm_sub_rev ];
      · rw [ div_lt_iff₀ ] <;> nlinarith [ hn y hy, hn' y hy', mul_le_mul ( hn' y hy' |>.1 ) ( hn' y hy' |>.2 ) ( by positivity ) ( by positivity ) ];
      · grind;
      · exact fun h => by have := hn' y hy'; norm_num [ h ] at this; linarith;

lemma TendstoLocallyUniformlyOn_mul {ι : Type*} [Preorder ι] {F : ι → ℂ → ℂ}
    {f : ℂ → ℂ} {G : ι → ℂ → ℂ} {g : ℂ → ℂ} {S : Set ℂ}
    (hf : TendstoLocallyUniformlyOn F f Filter.atTop S)
    (hg : TendstoLocallyUniformlyOn G g Filter.atTop S)
    (hf_cont : ContinuousOn f S)
    (hg_cont : ContinuousOn g S) :
    TendstoLocallyUniformlyOn (fun i z => F i z * G i z) (fun z => f z * g z)
      Filter.atTop S := by
        intro ε εpos x hx;
        -- Since $f$ and $g$ are continuous at $x$, they are bounded on some neighborhood $U$ of $x$.
        obtain ⟨U, hU⟩ : ∃ U ∈ nhdsWithin x S, ∃ M > 0, ∀ z ∈ U, ‖f z‖ ≤ M ∧ ‖g z‖ ≤ M := by
          have h_bounded : ∃ U ∈ nhdsWithin x S, ∃ M > 0, ∀ z ∈ U, ‖f z‖ ≤ M := by
            have h_bounded : ∃ U ∈ nhdsWithin x S, ∃ M > 0, ∀ z ∈ U, ‖f z‖ ≤ M := by
              have h_cont : ContinuousOn f S := hf_cont
              have h_bounded : ∃ M > 0, ∀ᶠ z in nhdsWithin x S, ‖f z‖ ≤ M := by
                have := h_cont x hx;
                have := this.norm;
                exact ⟨ ‖f x‖ + 1, by positivity, this.eventually ( ge_mem_nhds <| lt_add_one _ ) ⟩
              exact ⟨ _, h_bounded.choose_spec.2, _, h_bounded.choose_spec.1, fun z hz => hz ⟩;
            exact h_bounded;
          have h_bounded_g : ∃ U ∈ nhdsWithin x S, ∃ M > 0, ∀ z ∈ U, ‖g z‖ ≤ M := by
            have := hg_cont x hx;
            have := this.norm.tendsto;
            exact ⟨ { z : ℂ | ‖g z‖ ≤ ‖g x‖ + 1 }, this.eventually ( ge_mem_nhds <| lt_add_one _ ), ‖g x‖ + 1, add_pos_of_nonneg_of_pos ( norm_nonneg _ ) zero_lt_one, fun z hz => hz ⟩;
          obtain ⟨ U, hU₁, M, hM₁, hM₂ ⟩ := h_bounded; obtain ⟨ V, hV₁, N, hN₁, hN₂ ⟩ := h_bounded_g; exact ⟨ U ∩ V, Filter.inter_mem hU₁ hV₁, Max.max M N, lt_max_of_lt_left hM₁, fun z hz => ⟨ le_trans ( hM₂ z hz.1 ) ( le_max_left _ _ ), le_trans ( hN₂ z hz.2 ) ( le_max_right _ _ ) ⟩ ⟩ ;
        rcases Metric.mem_uniformity_dist.1 εpos with ⟨ δ, δpos, hδ ⟩;
        -- Choose $\delta$ such that $0 < \delta < \min(1, \frac{\epsilon}{2M})$.
        obtain ⟨δ', δ'pos, hδ'⟩ : ∃ δ' > 0, δ' < min 1 (δ / (2 * (hU.right.choose + 1))) := by
          exact exists_between ( lt_min zero_lt_one ( div_pos δpos ( mul_pos zero_lt_two ( add_pos_of_nonneg_of_pos ( le_of_lt hU.2.choose_spec.1 ) zero_lt_one ) ) ) );
        -- Since $F$ and $G$ converge locally uniformly, they are eventually bounded on some neighborhood $V$ of $x$.
        obtain ⟨V, hV⟩ : ∃ V ∈ nhdsWithin x S, ∀ᶠ n in Filter.atTop, ∀ z ∈ V, ‖F n z - f z‖ < δ' ∧ ‖G n z - g z‖ < δ' := by
          have hF : ∃ V ∈ nhdsWithin x S, ∀ᶠ n in Filter.atTop, ∀ z ∈ V, ‖F n z - f z‖ < δ' := by
            rw [ Metric.tendstoLocallyUniformlyOn_iff ] at hf;
            simpa only [ dist_eq_norm', norm_sub_rev ] using hf δ' δ'pos x hx;
          have hG : ∃ V ∈ nhdsWithin x S, ∀ᶠ n in Filter.atTop, ∀ z ∈ V, ‖G n z - g z‖ < δ' := by
            have := Metric.tendstoLocallyUniformlyOn_iff.1 hg δ' δ'pos;
            simpa only [ dist_comm, norm_sub_rev ] using this x hx;
          obtain ⟨ V₁, hV₁, hV₁' ⟩ := hF; obtain ⟨ V₂, hV₂, hV₂' ⟩ := hG; exact ⟨ V₁ ∩ V₂, Filter.inter_mem hV₁ hV₂, by filter_upwards [ hV₁', hV₂' ] with n hn hn' using fun z hz => ⟨ hn z hz.1, hn' z hz.2 ⟩ ⟩ ;
        refine' ⟨ V ∩ U, _, _ ⟩ <;> simp_all +decide [ eventually_nhdsWithin_iff ];
        filter_upwards [ hV.2 ] with n hn y hy hyU;
        -- Using the triangle inequality and the bounds on $F$ and $G$, we get:
        have h_triangle : ‖F n y * G n y - f y * g y‖ ≤ ‖F n y - f y‖ * ‖G n y‖ + ‖f y‖ * ‖G n y - g y‖ := by
          simpa only [ ← norm_mul ] using by convert norm_add_le ( ( F n y - f y ) * G n y ) ( f y * ( G n y - g y ) ) using 1 ; ring;
        -- Using the bounds on $F$ and $G$, we get:
        have h_bounds : ‖G n y‖ ≤ hU.right.choose + δ' ∧ ‖f y‖ ≤ hU.right.choose := by
          exact ⟨ by have := hU.2.choose_spec.2 y hyU; have := hn y hy; exact le_trans ( by simpa using norm_add_le ( G n y - g y ) ( g y ) ) ( by linarith ), hU.2.choose_spec.2 y hyU |>.1 ⟩;
        have h_final : ‖F n y * G n y - f y * g y‖ < δ := by
          have := hn y hy;
          rw [ lt_div_iff₀ ] at hδ' <;> nlinarith [ hU.2.choose_spec.1, norm_nonneg ( F n y - f y ), norm_nonneg ( G n y - g y ) ];
        exact hδ ( by simpa [ dist_eq_norm' ] using h_final )

lemma TendstoLocallyUniformlyOn_div {ι : Type*} [Preorder ι] {F : ι → ℂ → ℂ}
    {f : ℂ → ℂ} {G : ι → ℂ → ℂ} {g : ℂ → ℂ} {S : Set ℂ}
    (hf : TendstoLocallyUniformlyOn F f Filter.atTop S)
    (hg : TendstoLocallyUniformlyOn G g Filter.atTop S)
    (hf_cont : ContinuousOn f S)
    (hg_cont : ContinuousOn g S)
    (hg_ne_zero : ∀ z ∈ S, g z ≠ 0) :
    TendstoLocallyUniformlyOn (fun i z => F i z / G i z) (fun z => f z / g z)
      Filter.atTop S := by
        have := @TendstoLocallyUniformlyOn_inv ι _ G g S;
        simpa only [ div_eq_mul_inv ] using TendstoLocallyUniformlyOn_mul hf ( this hg hg_cont hg_ne_zero ) hf_cont ( hg_cont.inv₀ hg_ne_zero )