use Cwd qw(abs_path);
my $q3_bib_dir = abs_path('../../../docs/routeB_bus/litreview');
$ENV{'BIBINPUTS'} = $q3_bib_dir . ':' . ($ENV{'BIBINPUTS'} // '');
$pdf_mode = 1;
$pdflatex = 'xelatex -interaction=nonstopmode -halt-on-error -synctex=1 %O %S';
@default_files = ('print.tex');
