#!/usr/bin/env python3
"""
Convert a pilot interval certificate into a Lean UB table.

Usage:
  scripts/prime_brange_pilot_interval_to_lean_ub.py \
    --input q3.lean.aristotle/output/prime_cert_brange_tcritical_pilot_interval_2026-01-30_2357.txt \
    --output q3.lean.aristotle/Q3/Proofs/PrimeCert/BrangeGrid_Pilot_2026_01_30_UB.lean \
    --digits 12
"""

from __future__ import annotations

import argparse
import hashlib
from decimal import Decimal, getcontext
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--input", required=True)
    p.add_argument("--output", required=True)
    p.add_argument("--digits", type=int, default=12)
    return p.parse_args()


def sha256_hex(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def source_label(path: Path) -> str:
    parts = path.resolve().parts
    if "q3.lean.aristotle" in parts:
        idx = parts.index("q3.lean.aristotle")
        rel = Path(*parts[idx + 1 :])
        return str(rel)
    return str(path)


def parse_pilot_sums(text: str) -> dict[float, str]:
    rows: dict[float, str] = {}
    current_B: float | None = None
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("B ="):
            try:
                current_B = float(line.split("=", 1)[1].strip())
            except ValueError:
                current_B = None
            continue
        if line.startswith("pilot_prime_sum ="):
            if current_B is None:
                raise SystemExit("pilot_prime_sum without preceding B")
            rows[current_B] = line.split("=", 1)[1].strip()
    if not rows:
        raise SystemExit("No pilot_prime_sum entries found.")
    return rows


def main() -> None:
    args = parse_args()
    inp = Path(args.input)
    outp = Path(args.output)

    if not inp.exists():
        raise SystemExit(f"Missing input file: {inp}")

    getcontext().prec = max(50, args.digits + 10)
    quant = Decimal(f"1e-{args.digits}")

    rows = parse_pilot_sums(inp.read_text(encoding="utf-8"))
    b_values = [3.0, 4.9]
    vals: list[str] = []
    for b in b_values:
        if b not in rows:
            raise SystemExit(f"Missing pilot entry for B={b}")
        vals.append(format(Decimal(rows[b]).quantize(quant), "f"))

    digest = sha256_hex(inp)
    src = source_label(inp)

    lean = f"""import Mathlib
import Q3.Proofs.PrimeCert.BrangeGrid_2046

/-!
Pilot interval upper bounds for the prime partial sums (two grid points).

Source: {src}
Generated by: scripts/prime_brange_pilot_interval_to_lean_ub.py
-/

noncomputable section

namespace Q3.Proofs.PrimeCert

/-- Source file (pilot interval certificate). -/
def prime_cert_brange_pilot_sum_ub_source : String :=
  "{src}"

/-- SHA256 of the pilot source file. -/
def prime_cert_brange_pilot_sum_ub_sha256 : String :=
  "{digest}"

/-- Interval upper bounds for the pilot partial sums. -/
def prime_b_grid_pilot_sum_ub_q_get : Fin prime_b_grid_size -> ℚ
| ⟨0, _⟩ => {vals[0]}
| ⟨19, _⟩ => {vals[1]}
| _ => {vals[1]}

def prime_b_grid_pilot_sum_ub (i : Fin prime_b_grid_size) : ℝ :=
  (prime_b_grid_pilot_sum_ub_q_get i : ℝ)

end Q3.Proofs.PrimeCert
"""

    outp.parent.mkdir(parents=True, exist_ok=True)
    outp.write_text(lean + "\n", encoding="utf-8")
    print(f"Wrote {outp}")


if __name__ == "__main__":
    main()
