#!/usr/bin/env python3
"""
Generate prime-power upper bounds for prime-heat partial sums (t_critical, tau=0).

This emits a Lean file with a lookup table mapping n ↦ upper bound for
prime_heat_weight_term n. Values are rounded *up* to a fixed number of
decimal places to preserve the upper-bound property.
"""

from __future__ import annotations

import argparse
import hashlib
from dataclasses import dataclass
from decimal import ROUND_CEILING, Decimal, getcontext
from pathlib import Path

import mpmath as mp
from mpmath import iv


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--input", required=True)
    p.add_argument("--output", required=True)
    p.add_argument("--digits", type=int, default=30)
    p.add_argument(
        "--buckets",
        default="",
        help="Comma-separated bucket indices to include (default: all).",
    )
    p.add_argument(
        "--subnamespace",
        default="",
        help="Optional sub-namespace for generated definitions.",
    )
    return p.parse_args()


def sha256_hex(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def source_label(path: Path) -> str:
    parts = path.resolve().parts
    if "q3.lean.aristotle" in parts:
        idx = parts.index("q3.lean.aristotle")
        rel = Path(*parts[idx + 1 :])
        return str(rel)
    return str(path)


def parse_value(text: str, key: str) -> str:
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith(key):
            continue
        _, rhs = line.split("=", 1)
        return rhs.strip()
    raise SystemExit(f"Missing '{key}' in input file")


def sieve_primes(limit: int) -> list[int]:
    is_prime = bytearray(b"\x01") * (limit + 1)
    is_prime[0:2] = b"\x00\x00"
    for p in range(2, int(limit**0.5) + 1):
        if is_prime[p]:
            start = p * p
            step = p
            is_prime[start : limit + 1 : step] = b"\x00" * (((limit - start) // step) + 1)
    return [i for i in range(2, limit + 1) if is_prime[i]]


@dataclass
class Entry:
    n: int
    p: int


def prime_powers(limit: int) -> list[Entry]:
    primes = sieve_primes(limit)
    out: list[Entry] = []
    for p in primes:
        pk = p
        while pk <= limit:
            out.append(Entry(n=pk, p=p))
            pk *= p
    out.sort(key=lambda e: e.n)
    return out


def main() -> None:
    args = parse_args()
    inp = Path(args.input)
    outp = Path(args.output)

    if not inp.exists():
        raise SystemExit(f"Missing input file: {inp}")

    text = inp.read_text(encoding="utf-8")
    n_raw = parse_value(text, "N")
    b_max_raw = parse_value(text, "B_max")

    # interval precision
    mp.mp.dps = 120

    N = int(n_raw)
    _ = mp.mpf(b_max_raw)

    entries = prime_powers(N)

    pi = iv.pi
    two_pi = iv.mpf(2) * pi
    four_pi_sq = iv.mpf(4) * pi * pi
    t_critical = iv.mpf(3) / iv.mpf(20)

    getcontext().prec = max(80, args.digits + 40)
    quant = Decimal(f"1e-{args.digits}")

    def round_up(x: iv.mpf) -> Decimal:
        upper = mp.mpf(x.b)
        return Decimal(mp.nstr(upper, 120)).quantize(quant, rounding=ROUND_CEILING)

    ub_map: dict[int, Decimal] = {}
    for e in entries:
        logp = iv.log(iv.mpf(e.p))
        n_iv = iv.mpf(e.n)
        xi = iv.log(n_iv) / two_pi
        w_q = (iv.mpf(2) * logp) / iv.sqrt(n_iv)
        heat = iv.exp(-four_pi_sq * t_critical * xi * xi)
        term = w_q * heat * abs(xi)
        ub_map[e.n] = round_up(term)

    scale = 10**args.digits
    ub_num_map: dict[int, int] = {}
    for n, ub in ub_map.items():
        ub_num_map[n] = int(ub * scale)

    digest = sha256_hex(inp)
    src = source_label(inp)

    lines: list[str] = []
    lines.append("import Mathlib")
    lines.append("import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_Data")
    lines.append("set_option maxHeartbeats 0")
    lines.append("")
    lines.append("/-!")
    lines.append("Prime-heat prime-power term bounds (t_critical, tau = 0).")
    lines.append("")
    lines.append(f"Source: {src}")
    lines.append("Generated by: scripts/prime_brange_heat_pp_interval_checker.py")
    lines.append("-/")
    lines.append("")
    lines.append("noncomputable section")
    lines.append("")
    lines.append("namespace Q3.Proofs.PrimeCert")
    if args.subnamespace:
        lines.append(f"namespace {args.subnamespace}")
    lines.append("")
    lines.append("/-- Source file (prime-heat partial interval certificate). -/")
    lines.append("def prime_cert_heat_pp_term_source : String :=")
    lines.append(f'  "{src}"')
    lines.append("")
    lines.append("/-- SHA256 of the source file. -/")
    lines.append("def prime_cert_heat_pp_term_sha256 : String :=")
    lines.append(f'  "{digest}"')
    lines.append("")
    bucket_width = 10000
    bucket_count = (N + bucket_width - 1) // bucket_width
    bucket_filter = None
    if args.buckets:
        bucket_filter = {int(x.strip()) for x in args.buckets.split(",") if x.strip()}
    buckets: dict[int, list[tuple[int, Decimal]]] = {}
    for n, ub in ub_map.items():
        k = (n - 1) // bucket_width
        buckets.setdefault(k, []).append((n, ub))
    for k in buckets:
        buckets[k].sort()
    selected_buckets = list(range(bucket_count))
    if bucket_filter is not None:
        selected_buckets = [k for k in selected_buckets if k in bucket_filter]

    lines.append("/-- Common denominator for prime-power term bounds. -/")
    lines.append(f"def prime_heat_pp_term_ub_den : ℚ := {scale}")
    lines.append("")
    lines.append("/-- Upper bounds for prime-power terms (rational), per bucket. -/")
    for k in selected_buckets:
        lines.append(f"def prime_heat_pp_term_ub_q_get_bucket_{k} : ℕ -> ℚ")
        for n, _ub in buckets.get(k, []):
            num = ub_num_map[n]
            lines.append(f"| {n} => ({num} : ℚ) / prime_heat_pp_term_ub_den")
        lines.append("| _ => 0")
        lines.append("")

    lines.append("/-- Bucket index for prime-power term lookup. -/")
    lines.append("def prime_heat_pp_term_bucket_width : Nat := 10000")
    lines.append("def prime_heat_pp_term_bucket_index (n : ℕ) : ℕ :=")
    lines.append("  (n - 1) / prime_heat_pp_term_bucket_width")
    lines.append("")

    lines.append("/-- Upper bounds for prime-power terms (rational). -/")
    lines.append("def prime_heat_pp_term_ub_q_get (n : ℕ) : ℚ :=")
    lines.append("  match prime_heat_pp_term_bucket_index n with")
    for k in selected_buckets:
        lines.append(f"  | {k} => prime_heat_pp_term_ub_q_get_bucket_{k} n")
    lines.append("  | _ => 0")
    lines.append("")
    lines.append("/-- Upper bounds for prime-power terms (real). -/")
    lines.append("def prime_heat_pp_term_ub (n : ℕ) : ℝ :=")
    lines.append("  (prime_heat_pp_term_ub_q_get n : ℝ)")
    lines.append("")
    if selected_buckets:
        lines.append("/-- Prime-power bucket sums (rational). -/")
        for k in selected_buckets:
            total = sum(ub_num_map[n] for n, _ in buckets.get(k, []))
            lines.append(
                f"def prime_heat_pp_term_ub_q_sum_bucket_{k} : ℚ := ({total} : ℚ) / prime_heat_pp_term_ub_den"
            )
        lines.append("")

    if args.subnamespace:
        lines.append(f"end {args.subnamespace}")
    lines.append("end Q3.Proofs.PrimeCert")

    outp.parent.mkdir(parents=True, exist_ok=True)
    outp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {outp}")


if __name__ == "__main__":
    main()
