#!/usr/bin/env python3
"""
Convert prime-heat partial interval output into a Lean SumData file.

Usage:
  scripts/prime_brange_heat_partial_interval_to_lean.py \
    --input q3.lean.aristotle/output/prime_cert_brange_heat_prime_partial_interval_2026-01-31_0009.txt \
    --output q3.lean.aristotle/Q3/Proofs/PrimeCert/BrangeHeatCert_2026_01_28_SumData.lean \
    --digits 12
"""

from __future__ import annotations

import argparse
import hashlib
from decimal import Decimal, getcontext
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--input", required=True)
    p.add_argument("--output", required=True)
    p.add_argument("--digits", type=int, default=12)
    return p.parse_args()


def sha256_hex(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def source_label(path: Path) -> str:
    parts = path.resolve().parts
    if "q3.lean.aristotle" in parts:
        idx = parts.index("q3.lean.aristotle")
        rel = Path(*parts[idx + 1 :])
        return str(rel)
    return str(path)


def parse_value(text: str, key: str) -> str:
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith(key):
            continue
        _, rhs = line.split("=", 1)
        return rhs.strip()
    raise SystemExit(f"Missing '{key}' in input file")


def main() -> None:
    args = parse_args()
    inp = Path(args.input)
    outp = Path(args.output)

    if not inp.exists():
        raise SystemExit(f"Missing input file: {inp}")

    text = inp.read_text(encoding="utf-8")
    sum_ub_raw = parse_value(text, "prime_heat_sum_up_to_ub")
    l_partial_raw = parse_value(text, "L_prime_heat_partial")

    getcontext().prec = max(50, args.digits + 10)
    quant = Decimal(f"1e-{args.digits}")
    sum_ub = format(Decimal(sum_ub_raw).quantize(quant), "f")
    l_partial = Decimal(l_partial_raw)
    if Decimal(sum_ub_raw) > l_partial:
        raise SystemExit("prime_heat_sum_up_to_ub exceeds L_prime_heat_partial")

    digest = sha256_hex(inp)
    src = source_label(inp)

    lean = f"""import Mathlib
import Q3.Proofs.PrimeCert.BrangeHeatCert_2026_01_28_Data

/-!
Prime-heat partial-sum evidence (t_critical, tau = 0).

Source: {src}
Generated by: scripts/prime_brange_heat_partial_interval_to_lean.py

This file isolates the numeric evidence for:
- the finite partial sum upper bound (h_sum_ub)
- the tail bound (h_tail)
-/

noncomputable section

namespace Q3.Proofs.PrimeCert

/-- Source file (prime-heat partial sum evidence). -/
def prime_cert_heat_prime_partial_source : String :=
  "{src}"

/-- SHA256 of the partial-sum source file. -/
def prime_cert_heat_prime_partial_sha256 : String :=
  "{digest}"

def prime_cert_heat_prime_sum_up_to_ub : ℝ :=
  {sum_ub}

lemma prime_cert_heat_prime_sum_up_to_ub_le_partial :
    prime_cert_heat_prime_sum_up_to_ub ≤ prime_cert_L_prime_heat_partial := by
  norm_num [prime_cert_heat_prime_sum_up_to_ub, prime_cert_L_prime_heat_partial,
    prime_cert_heat_tail_bound, prime_cert_L_prime_heat_raw]

structure PrimeHeatSumData where
  h_sum_ub : prime_heat_prime_sum_up_to prime_cert_heat_N ≤ prime_cert_heat_prime_sum_up_to_ub
  h_tail :
    ∑' n, prime_heat_weight_term (n + (prime_cert_heat_N + 1)) ≤
      prime_cert_heat_tail_bound

axiom prime_heat_sum_data : PrimeHeatSumData

end Q3.Proofs.PrimeCert
"""

    outp.parent.mkdir(parents=True, exist_ok=True)
    outp.write_text(lean + "\n", encoding="utf-8")
    print(f"Wrote {outp}")


if __name__ == "__main__":
    main()
