#!/usr/bin/env python3
"""
Convert a prime B-range interval certificate into a Lean UB table.

Usage:
  scripts/prime_brange_interval_to_lean_ub.py \
    --input q3.lean.aristotle/output/prime_cert_brange_tcritical_interval_2026-01-30_2206.txt \
    --output q3.lean.aristotle/Q3/Proofs/PrimeCert/BrangeGrid_PrimeSum_2026_01_30_UB.lean \
    --digits 12
"""

from __future__ import annotations

import argparse
import hashlib
from decimal import Decimal, getcontext
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--input", required=True)
    p.add_argument("--output", required=True)
    p.add_argument("--digits", type=int, default=12)
    return p.parse_args()


def sha256_hex(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def source_label(path: Path) -> str:
    parts = path.resolve().parts
    if "q3.lean.aristotle" in parts:
        idx = parts.index("q3.lean.aristotle")
        rel = Path(*parts[idx + 1 :])
        return str(rel)
    return str(path)


def parse_prime_sums(text: str) -> list[str]:
    values: list[str] = []
    for line in text.splitlines():
        line = line.strip()
        if not line or not line[0].isdigit():
            continue
        parts = [p.strip() for p in line.split(",")]
        if len(parts) < 2:
            continue
        values.append(parts[1])
    if not values:
        raise SystemExit("No data rows parsed.")
    return values


def main() -> None:
    args = parse_args()
    inp = Path(args.input)
    outp = Path(args.output)

    if not inp.exists():
        raise SystemExit(f"Missing input file: {inp}")

    getcontext().prec = max(50, args.digits + 10)
    quant = Decimal(f"1e-{args.digits}")

    raw_values = parse_prime_sums(inp.read_text(encoding="utf-8"))
    values: list[str] = []
    for raw in raw_values:
        val = Decimal(raw).quantize(quant)
        values.append(format(val, "f"))

    def render_fin_table(name: str, rows: list[str]) -> str:
        lines = [f"def {name} : Fin prime_b_grid_size -> ℚ"]
        for idx, val in enumerate(rows):
            lines.append(f"| ⟨{idx}, _⟩ => {val}")
        lines.append(f"| _ => {rows[-1]}")
        return "\n".join(lines)

    table = render_fin_table("prime_b_grid_prime_sum_ub_q_get", values)
    digest = sha256_hex(inp)

    src = source_label(inp)

    lean = f"""import Mathlib
import Q3.Proofs.PrimeCert.BrangeGrid_2046

/-!
Interval upper bounds for the prime partial sums on the B-grid.

Source: {src}
Generated by: scripts/prime_brange_interval_to_lean_ub.py
-/

noncomputable section

namespace Q3.Proofs.PrimeCert

/-- Source file (full B-grid certificate). -/
def prime_cert_brange_sum_ub_source : String :=
  "{src}"

/-- SHA256 of the full source file. -/
def prime_cert_brange_sum_ub_sha256 : String :=
  "{digest}"

/-- Interval upper bounds for the prime partial sums (same B grid). -/
{table}


def prime_b_grid_prime_sum_ub (i : Fin prime_b_grid_size) : ℝ :=
  (prime_b_grid_prime_sum_ub_q_get i : ℝ)

lemma prime_b_grid_prime_sum_ub_le_table :
    ∀ i : Fin prime_b_grid_size,
      prime_b_grid_prime_sum_ub i ≤ prime_b_grid_prime_sum i := by
  intro i
  fin_cases i <;>
    norm_num [prime_b_grid_prime_sum_ub, prime_b_grid_prime_sum_ub_q_get,
      prime_b_grid_prime_sum, prime_b_grid_prime_sum_q_get]

end Q3.Proofs.PrimeCert
"""

    outp.parent.mkdir(parents=True, exist_ok=True)
    outp.write_text(lean + "\n", encoding="utf-8")
    print(f"Wrote {outp}")


if __name__ == "__main__":
    main()
