#!/bin/bash
# Research Swarm Task Generator — converts insight to TASK.md

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../research_swarm/config.sh"

INSIGHT_FILE="$1"
INSIGHT_ID="$2"

if [[ -z "$INSIGHT_FILE" || -z "$INSIGHT_ID" ]]; then
    echo "Usage: $0 <insight_file> <insight_id>"
    exit 1
fi

WORKER_DIR="${WORKERS_DIR}/${INSIGHT_ID}"
mkdir -p "${WORKER_DIR}"

# Extract metadata from insight YAML frontmatter
extract_yaml() {
    local key="$1"
    sed -n '/^---$/,/^---$/p' "$INSIGHT_FILE" | grep "^${key}:" | sed "s/^${key}: *//"
}

SUBPROBLEM=$(extract_yaml "subproblem")
CONFIDENCE=$(extract_yaml "confidence")
PRIORITY=$(extract_yaml "priority")

# Extract title (first H1 after frontmatter) - macOS compatible
TITLE=$(awk '/^---$/{f=!f;next} !f && /^# /{gsub(/^# /,"");print;exit}' "$INSIGHT_FILE")

# Extract sections
extract_section() {
    local header="$1"
    sed -n "/^## ${header}/,/^## /p" "$INSIGHT_FILE" | sed '1d;$d'
}

SUMMARY=$(extract_section "One-Line Summary")
MATH_CONTENT=$(extract_section "Mathematical Content")
LEAN_TRANSLATION=$(extract_section "Lean Translation")
VERIFICATION_PLAN=$(extract_section "Verification Plan")

# Generate TASK.md
cat > "${WORKER_DIR}/TASK.md" << EOF
# TASK: ${TITLE:-$INSIGHT_ID}

**Insight ID:** \`${INSIGHT_ID}\`
**Subproblem:** ${SUBPROBLEM:-unknown}
**Confidence:** ${CONFIDENCE:-medium}
**Priority:** ${PRIORITY:-5}
**Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)

---

## Objective

${SUMMARY:-Investigate and formalize the insight described below.}

## Context

This task was auto-generated from an insight file. Your job is to:

1. **Understand** the mathematical insight
2. **Translate** it to Lean 4 code
3. **Verify** it compiles and type-checks
4. **Integrate** into the main proof chain if successful

## Mathematical Content

${MATH_CONTENT:-See original insight file.}

## Lean Translation Hints

${LEAN_TRANSLATION:-No specific hints provided.}

## 🔍 Finding Mathlib Lemmas (CRITICAL!)

**DO NOT guess lemma names!** Use Explore sub-agent:

\`\`\`
Task(
  subagent_type="Explore",
  prompt="Search Mathlib for lemmas about [description].
          Look in [relevant module paths].
          Find EXACT lemma names with signatures."
)
\`\`\`

The sub-agent will grep through:
- \`~/.elan/toolchains/*/lib/lean4/library/\`
- \`.lake/packages/mathlib/\`

**WRONG:** Guessing names like "I think it's \`foo_bar\`..."
**WRONG:** Using \`exact?\` (often timeouts)
**RIGHT:** Task(Explore, "Search for...") → get EXACT names

## Verification Plan

${VERIFICATION_PLAN:-
1. Create a standalone .lean file with the formalization
2. Run \`lake build\` to check it compiles
3. Run \`#check\` on main definitions
4. If successful, create PR to main branch
}

---

## Project Context

**Main problem file:** \`/Users/emalam/Documents/GitHub/chen_q3/PROBLEM.md\`
**Orchestrator:** \`full/q3.lean.aristotle/PROJECT_ORCHESTRATOR.md\`
**Axioms file:** \`full/q3.lean.aristotle/Q3/Axioms.lean\`

## Commands

\`\`\`bash
# Build
lake build Q3.Main

# Check axioms
./scripts/check_axioms.sh

# Run tests
lake test
\`\`\`

## When Done

1. Update \`status.json\` to \`completed\` or \`failed\`
2. If successful, create summary in \`insights/completed/\`
3. Notify main session (write to \`REGISTRY.md\`)

---

*This task was auto-generated by Research Swarm at $(date)*
EOF

echo "Generated TASK.md for: $INSIGHT_ID"
