import Q3.Proofs.PSD_CenteredCoeffRawOmegaAEndpointRationalImport

/-!
Step33A.1-A endpoint v18 Aristotle pilot.

This file is an Aristotle input file, not a project proof import.  The two
`sorry` proofs below are the proof-bearing analytic endpoint packages missing
from the checked rational endpoint layer:

* Omega: `Step22OmegaClosedFormEndpointBoundsCert`
* ShapeSq: `ShapeSqEndpointBoundsCert`

The final definition is already pure local plumbing through the checked
`primaryFiniteRow0Parent0Split100Sub0EndpointIntervalCert_of_endpoint_bounds_generated`.

## Status

Both endpoint packages require rigorous high-precision (≥77 decimal places)
evaluation of transcendental functions at specific rational points.  The
exact missing analytic lemmas are identified below as sorry'd statements.

### Omega endpoint — missing analytic lemmas:

1. `neg_euler_mascheroni_sub_log_pi_lower` / `_upper`: tight bounds on
   `-γ - log π` to ~80 decimal places, needed for the anchor value interval.
2. `trigammaImTermClosedForm_interval_bounds`: monotonicity-based interval
   enclosure for the rational function `trigammaImSeriesTermClosedForm` on
   the narrow subchunk interval `[a, b]`.
3. `cubic_tail_series_bound`: upper bound on `∑' n, η / ((n+N+1/4)^3)`.

### ShapeSq endpoint — missing analytic lemmas:

1. `sin_at_inv_800_bounds`: bounds on `sin(1/800)` to ≥80 decimal places,
   needed for `realSinc(1/800)^12` evaluation and the anchor-square target.
2. `sqrt_bspline_norm_bounds`: bounds on `√(6 · B₂₃(0))` to ≥80 decimal
   places, where `B₂₃(0) = centeredCardinalBSpline 23 0` is rational.
3. Corresponding derivative closed-form bounds involving `cos(1/800)`.

All of these are provable using Mathlib's `Complex.exp_bound'` Taylor
remainder (for sin/cos), `Real.sum_le_exp_of_nonneg` / `Real.exp_bound'`
(for log/exp), and `Real.eulerMascheroniSeq` / `eulerMascheroniSeq'` (for γ),
but require a high-precision rational arithmetic layer that generates the
~80-digit interval certificates.
-/

set_option linter.mathlibStandardSet false
set_option autoImplicit false
set_option maxHeartbeats 0

noncomputable section

namespace Q3
namespace PSDpd
namespace CenteredCoeffPrimeDeltaLiveRationalPayloadImport
namespace RawOmegaAChunkIntegral
namespace RawOmegaATaylorModelCertificate

#check Step22OmegaClosedFormEndpointBoundsCert
#check Step22OmegaClosedFormEndpointBoundsCert.of_re_series_anchor_trigamma_im_closed_form_term_prefix_cubic_tail_Icc
#check step22OmegaArchWeight_bounds_from_re_series_prefix_tail_abs
#check ShapeSqEndpointBoundsCert
#check ShapeSqEndpointBoundsCert.of_closedForm_value_derivClosedForm_intervals
#check primaryFiniteRow0Parent0Split100Sub0ShapeSqEndpointBounds_of_value_deriv_bounds_generated
#check centeredBSplineImagTransformRealClosedForm
#check centeredBSplineImagTransformRealClosedFormDerivClosedForm
#check primaryFiniteRow0Parent0Split100Sub0EndpointIntervalCert_of_endpoint_bounds_generated

/-!
## Missing analytic lemma: tight bounds on -γ - log π

The Omega anchor value is `-γ - log π + Σ step22OmegaArchWeightReSeriesTerm (1/20) n`,
so tight bounds on the transcendental constant `-γ - log π` are required.
The target anchor interval has width ~2e-77, so the bounds must be
correspondingly tight.

Proof route (not yet formalised):
- Use `Real.eulerMascheroniSeq_lt_eulerMascheroniConstant` at large N
  for a lower bound on γ, and `eulerMascheroniConstant_lt_eulerMascheroniSeq'`
  for an upper bound.  Both require `harmonic(N)` (exact rational) and
  `log(N)` / `log(N+1)` bounds.
- Bound `log(N)` using `Real.le_log_iff_exp_le` / `Real.log_lt_iff_lt_exp`
  combined with Taylor-remainder bounds on `exp` from
  `Real.sum_le_exp_of_nonneg` and `Real.exp_bound'`.
- Bound `log π` similarly, using `Real.pi_gt_d20` and `Real.pi_lt_d20`
  for 20-digit π bounds.
-/

-- NOTE: The exact rational bounds below are placeholders.
-- The true values would be generated by a high-precision computation tool.
-- γ ≈ 0.5772156649015328606065120900824024310421593359...
-- log π ≈ 1.1447298858494001741434273513530587116232...
-- -γ - log π ≈ -1.72194555075093303475...

/-!
## Omega endpoint proof skeleton

The proof applies the checked receiver
`Step22OmegaClosedFormEndpointBoundsCert.of_re_series_anchor_trigamma_im_closed_form_term_prefix_cubic_tail_Icc`
with:
- `derivN` = number of trigamma Im series terms to sum explicitly
- `anchorN` = number of re-series terms for anchor evaluation
- `termLower/termUpper` = interval enclosures for each series term
- remaining parameters = tight rational bounds on prefix sums, tail, and
  transcendental constants

Each hypothesis is either:
(a) pure rational arithmetic (dischargeable by `norm_num`), or
(b) an analytic interval enclosure requiring the missing transcendental bounds.
-/

theorem primaryFiniteRow0Parent0Split100Sub0OmegaEndpointBounds_aristotle_v18 :
    Step22OmegaClosedFormEndpointBoundsCert
      ((499999999999999999999 : Real) /
        (10000000000000000000000 : Real))
      ((1 : Real) / (20 : Real))
      ((1 : Real) / (20 : Real))
      ((158505952906660723821263128341789211522648013468721929299728671434816372504101837787327827 : Real) /
        (100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : Real))
      ((3170119058133214476431664946316801151647880016814754257913171534756799214149224661058141 : Real) /
        (2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : Real))
      ((-106643293527304552591821287391961407544994279623740339344557023924606219973211357305502357 : Real) /
        (20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : Real))
      ((-106643293527304552591821287391961407544994279623740339344557023924606219973211356905502357 : Real) /
        (20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : Real)) := by
  sorry

/-!
## ShapeSq endpoint proof skeleton

The proof applies the checked generated helper
`primaryFiniteRow0Parent0Split100Sub0ShapeSqEndpointBounds_of_value_deriv_bounds_generated`
which needs:
1. Lower bound on `centeredBSplineImagTransformRealClosedForm 11 (3/10) eta`
   for `eta ∈ [a, b]` — involves `sin` and `√` to ~80 digits
2. Upper bound on same
3. Lower bound on `centeredBSplineImagTransformRealClosedFormDerivClosedForm 11 (3/10) eta`
   for `eta ∈ [a, b]` — involves `sin`, `cos`, `√` to ~80 digits
4. Upper bound on same
5. Lower bound on `centeredBSplineImagTransformRealClosedForm 11 (3/10) (1/20) ^ 2`
6. Upper bound on same

Hypotheses (1)-(4) are analytic interval enclosures over the narrow
subchunk interval.  Hypotheses (5)-(6) are point evaluations (squared).
-/

theorem primaryFiniteRow0Parent0Split100Sub0ShapeSqEndpointBounds_aristotle_v18 :
    ShapeSqEndpointBoundsCert
      11
      ((3 : Real) / (10 : Real))
      ((499999999999999999999 : Real) /
        (10000000000000000000000 : Real))
      ((1 : Real) / (20 : Real))
      ((1 : Real) / (20 : Real))
      ((-46448578038952412672149872160407802487877144879577655939872927993464875466132202360827276104665062142415173687016462681408869026457238530060336008763092149959616648869724829277353 : Real) /
        (312500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : Real))
      ((-3715886243116193013422691188469113889347186857741575631430658701842124693104660254420490862373908779177392095867429176165007789167568948045769667316015512783831667117451096516791 : Real) /
        (25000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : Real))
      ((37158858560446920756861350578635783668117859273616803460403855154979728937804568063431171 : Real) /
        (62500000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : Real))
      ((37158858560446920756861350578635783668117859273616803460403855154979728937804569313431171 : Real) /
        (62500000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : Real)) := by
  sorry

def primaryFiniteRow0Parent0Split100Sub0EndpointIntervalCert_aristotle_v18 :=
  primaryFiniteRow0Parent0Split100Sub0EndpointIntervalCert_of_endpoint_bounds_generated
    primaryFiniteRow0Parent0Split100Sub0OmegaEndpointBounds_aristotle_v18
    primaryFiniteRow0Parent0Split100Sub0ShapeSqEndpointBounds_aristotle_v18

end RawOmegaATaylorModelCertificate
end RawOmegaAChunkIntegral
end CenteredCoeffPrimeDeltaLiveRationalPayloadImport
end PSDpd
end Q3
