import RequestProject.Main

#check EStarMuntzZeroMassContinuation.Estar
#check EStarMuntzZeroMassContinuation.Mellin
#check EStarMuntzZeroMassContinuation.Gwin
#check EStarMuntzZeroMassContinuation.Rminus
#check EStarMuntzZeroMassContinuation.Rplus
#check EStarMuntzZeroMassContinuation.ZetaMellinReg
#check EStarMuntzZeroMassContinuation.Estar_eq_zero_of_gt
#check EStarMuntzZeroMassContinuation.zeta_product_not_continuousAt_of_simple_zero
#check EStarMuntzZeroMassContinuation.shifted_zeta_product_not_continuousAt_of_simple_zero
#check EStarMuntzZeroMassContinuation.dilation_tsum_uniform_bound
#check EStarMuntzZeroMassContinuation.norm_Estar_le_sqrt

#print axioms EStarMuntzZeroMassContinuation.Estar_eq_zero_of_gt
#print axioms EStarMuntzZeroMassContinuation.zeta_product_not_continuousAt_of_simple_zero
#print axioms EStarMuntzZeroMassContinuation.shifted_zeta_product_not_continuousAt_of_simple_zero
#print axioms EStarMuntzZeroMassContinuation.dilation_tsum_uniform_bound
#print axioms EStarMuntzZeroMassContinuation.norm_Estar_le_sqrt
