/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 74219d5a-863e-47fa-a277-428c6cc97773

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.

-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

noncomputable def digamma (z : ℂ) : ℂ := (deriv Complex.Gamma z) / (Complex.Gamma z)

noncomputable def trigamma (z : ℂ) : ℂ := ∑' n : ℕ, 1 / (z + n)^2

noncomputable def a (ξ : ℝ) : ℝ := Real.log Real.pi - (digamma (1/4 + Complex.I * Real.pi * ξ)).re

lemma im_trigamma_neg {z : ℂ} (hz : 0 < z.re) (hzi : 0 < z.im) :
    (trigamma z).im < 0 := by
      -- The series $\sum_{n=0}^{\infty} \frac{1}{(z+n)^2}$ is convergent and its imaginary part is summable.
      have h_summable : Summable (fun n : ℕ => 1 / (z + n : ℂ) ^ 2) := by
        have h_summable : Summable (fun n : ℕ => (1 : ℝ) / (n : ℝ) ^ 2) := by
          exact Real.summable_one_div_nat_pow.2 one_lt_two;
        rw [ ← summable_norm_iff ] at *;
        -- Since $|z + n| \geq n$ for all $n$, we have $\frac{1}{|z + n|^2} \leq \frac{1}{n^2}$.
        have h_bound : ∀ n : ℕ, n ≥ 1 → ‖(z + n : ℂ)⁻¹ ^ 2‖ ≤ (1 : ℝ) / (n : ℝ) ^ 2 := by
          norm_num [ Complex.normSq, Complex.sq_norm ];
          exact fun n hn => inv_anti₀ ( by positivity ) ( by nlinarith [ show ( n : ℝ ) ≥ 1 by norm_cast ] );
        rw [ ← summable_nat_add_iff 1 ] at *;
        exact Summable.of_nonneg_of_le ( fun n => norm_nonneg _ ) ( fun n => by simpa using h_bound ( n + 1 ) ( by linarith ) ) h_summable;
      have h_trigamma_pos : (trigamma z).im = ∑' n : ℕ, -2 * (z.im * (z.re + n)) / ((z.re + n) ^ 2 + z.im ^ 2) ^ 2 := by
        have h_trigamma_pos : (trigamma z).im = ∑' n : ℕ, Complex.im (1 / (z + n : ℂ) ^ 2) := by
          convert Complex.im_tsum h_summable;
        convert h_trigamma_pos using 3 ; norm_num [ Complex.normSq, Complex.div_im, sq ] ; ring;
        rw [ inv_pow ] ; ring;
      rw [ h_trigamma_pos ];
      have h_sum_neg : ∑' n : ℕ, -2 * (z.im * (z.re + n)) / ((z.re + n) ^ 2 + z.im ^ 2) ^ 2 = -2 * z.im * ∑' n : ℕ, (z.re + n) / ((z.re + n) ^ 2 + z.im ^ 2) ^ 2 := by
        rw [ ← tsum_mul_left ] ; congr ; ext n ; ring;
      exact h_sum_neg.symm ▸ mul_neg_of_neg_of_pos ( by linarith ) ( lt_of_lt_of_le ( by positivity ) ( Summable.le_tsum ( show Summable fun n : ℕ => ( z.re + n ) / ( ( z.re + n ) ^ 2 + z.im ^ 2 ) ^ 2 from by
                                                                                                                            have h_summable : Summable (fun n : ℕ => (z.re + n) / ((z.re + n) ^ 2) ^ 2) := by
                                                                                                                              have h_summable : Summable (fun n : ℕ => (1 : ℝ) / ((z.re + n) ^ 3)) := by
                                                                                                                                have h_summable : Summable (fun n : ℕ => (1 : ℝ) / (n : ℝ) ^ 3) := by
                                                                                                                                  exact Real.summable_one_div_nat_pow.2 ( by norm_num );
                                                                                                                                rw [ ← summable_nat_add_iff ⌈z.re⌉₊ ] at *;
                                                                                                                                exact Summable.of_nonneg_of_le ( fun n => by positivity ) ( fun n => by gcongr ; linarith [ Nat.le_ceil z.re ] ) h_summable;
                                                                                                                              convert h_summable using 2 ; ring;
                                                                                                                              -- Combine and simplify the fractions
                                                                                                                              field_simp
                                                                                                                              ring;
                                                                                                                            exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( by positivity ) ( sq_nonneg _ ) ) ( fun n => div_le_div_of_nonneg_left ( by positivity ) ( by positivity ) ( by gcongr ; nlinarith ) ) h_summable ) 0 ( fun n _ => by positivity ) ) )

lemma deriv_a_eq {ξ : ℝ} (hξ : 0 < ξ) :
    deriv a ξ = Real.pi * (deriv (fun z : ℂ => digamma z) (1/4 + Complex.I * Real.pi * ξ)).im := by
      convert HasDerivAt.deriv _ using 1;
      -- Apply the chain rule to find the derivative of $a(\xi)$.
      have h_chain : HasDerivAt (fun ξ : ℝ => - (digamma (1 / 4 + Complex.I * Real.pi * ξ)).re) (Real.pi * (deriv (fun z : ℂ => digamma z) (1 / 4 + Complex.I * Real.pi * ξ)).im) ξ := by
        -- Apply the chain rule to find the derivative of the real part of the digamma function.
        have h_chain : HasDerivAt (fun ξ : ℝ => digamma (1 / 4 + Complex.I * Real.pi * ξ)) (deriv (fun z : ℂ => digamma z) (1 / 4 + Complex.I * Real.pi * ξ) * (Complex.I * Real.pi)) ξ := by
          have h_deriv : DifferentiableAt ℂ (fun z => digamma z) (1 / 4 + Complex.I * Real.pi * ξ) := by
            refine' DifferentiableAt.div _ _ _ <;> norm_num [ Complex.Gamma_ne_zero ];
            · -- The Gamma function is analytic everywhere except at non-positive integers, so its derivative is also analytic there.
              have h_gamma_analytic : AnalyticAt ℂ Complex.Gamma (1 / 4 + Complex.I * Real.pi * ξ) := by
                refine' DifferentiableOn.analyticAt _ _;
                exact { z : ℂ | 0 < z.re };
                · intro z hz; exact Complex.differentiableAt_Gamma _ ( by contrapose! hz; aesop ) |> DifferentiableAt.differentiableWithinAt;
                · exact IsOpen.mem_nhds ( isOpen_lt continuous_const Complex.continuous_re ) ( by norm_num [ Complex.ext_iff ] );
              exact h_gamma_analytic.deriv.differentiableAt;
            · refine' Complex.differentiableAt_Gamma _ _ ; norm_num [ Complex.ext_iff ] ; ring ; norm_num [ Real.pi_ne_zero ] ; aesop;
            · rw [ Complex.Gamma_eq_zero_iff ] ; norm_num [ Complex.ext_iff ];
              exact fun x hx => by linarith;
          convert HasDerivAt.comp ξ ( h_deriv.hasDerivAt ) ( HasDerivAt.add ( hasDerivAt_const _ _ ) ( HasDerivAt.mul ( hasDerivAt_const _ _ ) ( hasDerivAt_id _ |> HasDerivAt.ofReal_comp ) ) ) using 1 ; norm_num;
        rw [ hasDerivAt_iff_tendsto_slope_zero ] at *;
        convert Complex.continuous_re.continuousAt.tendsto.comp ( h_chain.neg ) using 2 ; norm_num ; ring;
        norm_num [ Complex.ext_iff ] ; ring;
      convert h_chain.const_add ( Real.log Real.pi ) using 2

lemma continuousOn_a : ContinuousOn a (Set.Ici 0) := by
  -- The digamma function is continuous on the complex plane except for non-positive integers. Since $1/4 + \mathrm{i} \pi \xi$ is never a non-positive integer for $\xi \geq 0$, the digamma function is continuous there.
  have h_digamma_cont : ContinuousOn (fun z : ℂ => digamma z) {z : ℂ | z.re > 0} := by
    -- The Gamma function is analytic on the right half-plane, hence its derivative is also analytic.
    have h_gamma_analytic : ∀ z : ℂ, 0 < z.re → AnalyticAt ℂ Complex.Gamma z := by
      intro z hz;
      refine' DifferentiableOn.analyticAt _ _;
      exact { w : ℂ | 0 < w.re };
      · intro w hw; exact Complex.differentiableAt_Gamma _ ( by contrapose! hw; aesop ) |> DifferentiableAt.differentiableWithinAt;
      · exact IsOpen.mem_nhds ( isOpen_lt continuous_const Complex.continuous_re ) hz;
    refine' continuousOn_of_forall_continuousAt _;
    intro z hz;
    exact ContinuousAt.div ( h_gamma_analytic z hz |> AnalyticAt.deriv |> AnalyticAt.continuousAt ) ( h_gamma_analytic z hz |> AnalyticAt.continuousAt ) ( Complex.Gamma_ne_zero_of_re_pos hz );
  refine ContinuousOn.sub ( continuousOn_const ) ( Complex.continuous_re.comp_continuousOn <| h_digamma_cont.comp ( Continuous.continuousOn <| show Continuous fun z : ℝ => 1 / 4 + Complex.I * Real.pi * z by continuity ) fun x hx => ?_ );
  norm_num [ Complex.ext_iff ]

lemma trigamma_add_one {z : ℂ} (hz : 0 < z.re) :
    trigamma (z + 1) = trigamma z - 1 / z ^ 2 := by
      -- By definition of trigamma, we have:
      have h_trigamma_def : trigamma z = ∑' n : ℕ, (1 / (z + n)^2 : ℂ) := by
        exact?;
      rw [ h_trigamma_def, eq_comm, Summable.tsum_eq_zero_add ];
      · norm_num [ add_assoc, add_left_comm, add_comm, trigamma ];
      · -- We'll use the fact that if the real part of $z$ is positive, then the series $\sum_{n=0}^{\infty} \frac{1}{(z+n)^2}$ converges.
        have h_summable : Summable (fun n : ℕ => (1 / (z + n)^2 : ℂ)) := by
          have h_abs : Summable (fun n : ℕ => (1 / (n : ℝ)^2 : ℝ)) := by
            exact Real.summable_one_div_nat_pow.2 one_lt_two
          rw [ ← summable_norm_iff ] at *;
          -- Since $|z + n| \geq n$ for $n \geq 1$, we have $\frac{1}{|z + n|^2} \leq \frac{1}{n^2}$.
          have h_bound : ∀ n : ℕ, 1 ≤ n → ‖1 / (z + n)^2‖ ≤ 1 / (n : ℝ)^2 := by
            intros n hn
            have h_abs : ‖z + n‖ ≥ n := by
              exact Real.le_sqrt_of_sq_le ( by simpa [ Complex.normSq ] using by nlinarith [ show ( n : ℝ ) ≥ 1 by norm_cast ] );
            simpa using inv_anti₀ ( by positivity ) ( pow_le_pow_left₀ ( by positivity ) h_abs 2 );
          rw [ ← summable_nat_add_iff 1 ];
          exact Summable.of_nonneg_of_le ( fun n => norm_nonneg _ ) ( fun n => h_bound _ le_add_self ) ( by simpa using summable_nat_add_iff 1 |>.2 h_abs );
        convert h_summable using 1

lemma diff_digamma_trigamma_add_one {z : ℂ} (hz : 0 < z.re) :
    deriv digamma (z + 1) - trigamma (z + 1) = deriv digamma z - trigamma z := by
      -- Use the recurrence relation for the digamma function: $\psi(z+1) = \psi(z) + \frac{1}{z}$.
      have h_recurrence : deriv (fun z => digamma z) (z + 1) = deriv (fun z => digamma z + 1 / z) z := by
        have h_recurrence : ∀ z : ℂ, 0 < z.re → digamma (z + 1) = digamma z + 1 / z := by
          -- Using the recurrence relation for the Gamma function, we have Γ(z+1) = zΓ(z). Taking the derivative of both sides with respect to z, we get Γ'(z+1) = Γ(z) + zΓ'(z).
          have h_gamma_recurrence : ∀ z : ℂ, 0 < z.re → deriv Complex.Gamma (z + 1) = Complex.Gamma z + z * deriv Complex.Gamma z := by
            intro z hz;
            have h_gamma_recurrence : HasDerivAt (fun z => Complex.Gamma (z + 1)) (Complex.Gamma z + z * deriv Complex.Gamma z) z := by
              have h_gamma_recurrence : HasDerivAt (fun z => z * Complex.Gamma z) (Complex.Gamma z + z * deriv Complex.Gamma z) z := by
                convert HasDerivAt.mul ( hasDerivAt_id z ) ( Complex.differentiableAt_Gamma _ _ |> DifferentiableAt.hasDerivAt ) using 1;
                · norm_num;
                · exact fun m => ne_of_apply_ne Complex.re <| by norm_num; linarith;
              exact h_gamma_recurrence.congr_of_eventuallyEq ( by filter_upwards [ IsOpen.mem_nhds ( isOpen_lt continuous_const Complex.continuous_re ) hz ] with x hx using by rw [ Complex.Gamma_add_one ] ; aesop );
            convert h_gamma_recurrence.deriv using 1;
            exact?;
          -- Using the definition of digamma, we can rewrite the recurrence relation in terms of digamma.
          intros z hz
          have h_digamma_recurrence : deriv Complex.Gamma (z + 1) / Complex.Gamma (z + 1) = (Complex.Gamma z + z * deriv Complex.Gamma z) / (z * Complex.Gamma z) := by
            rw [ h_gamma_recurrence z hz, Complex.Gamma_add_one ] ; ring ; aesop;
          unfold digamma;
          rw [ h_digamma_recurrence, div_add_div ] <;> ring <;> norm_num [ Complex.Gamma_ne_zero, show z ≠ 0 from by rintro rfl; norm_num at hz ];
          exact Complex.Gamma_ne_zero_of_re_pos hz;
        have h_trigamma_recurrence : deriv (fun z => digamma (z + 1)) z = deriv (fun z => digamma z + 1 / z) z := by
          exact Filter.EventuallyEq.deriv_eq ( Filter.eventuallyEq_of_mem ( IsOpen.mem_nhds ( isOpen_lt continuous_const Complex.continuous_re ) hz ) fun x hx => h_recurrence x hx );
        convert h_trigamma_recurrence using 1;
        exact?;
      -- Apply the linearity of the derivative and the fact that the derivative of $1/z$ is $-1/z^2$.
      have h_deriv_sum : deriv (fun z => digamma z + 1 / z) z = deriv digamma z + deriv (fun z => 1 / z) z := by
        -- Since both digamma and 1/z are differentiable at z, we can apply the linearity of the derivative.
        have h_diff : DifferentiableAt ℂ (fun z => digamma z) z ∧ DifferentiableAt ℂ (fun z => 1 / z) z := by
          refine' ⟨ _, DifferentiableAt.div ( differentiableAt_const _ ) differentiableAt_id ( by aesop ) ⟩;
          refine' DifferentiableAt.div _ _ _ <;> norm_num [ Complex.Gamma_ne_zero_of_re_pos, hz ];
          · -- The Gamma function is analytic in the right half-plane, so its derivative is also analytic there.
            have h_gamma_analytic : AnalyticAt ℂ Complex.Gamma z := by
              refine' DifferentiableOn.analyticAt _ _;
              exact { w : ℂ | 0 < w.re };
              · intro w hw; exact Complex.differentiableAt_Gamma _ ( by contrapose! hw; aesop ) |> DifferentiableAt.differentiableWithinAt;
              · exact IsOpen.mem_nhds ( isOpen_lt continuous_const Complex.continuous_re ) hz;
            exact h_gamma_analytic.deriv.differentiableAt;
          · refine' Complex.differentiableAt_Gamma _ _;
            exact fun m => ne_of_apply_ne Complex.re <| by norm_num; linarith;
        exact deriv_add h_diff.1 h_diff.2;
      rw [ h_recurrence, h_deriv_sum ];
      rw [ trigamma_add_one hz ] ; norm_num [ sub_eq_add_neg, add_assoc ]

lemma trigamma_tendsto_zero :
    Filter.Tendsto (fun x : ℝ => trigamma x) Filter.atTop (nhds 0) := by
      -- We'll use the fact that if the series $\sum_{n=0}^{\infty} \frac{1}{(x+n)^2}$ converges uniformly, then the limit function is continuous.
      have h_uniform : ∀ x : ℝ, x > 0 → ∑' n : ℕ, (1 / ((x + n : ℂ) ^ 2 : ℂ)) = ∑' n : ℕ, (1 / ((x + n : ℝ) ^ 2 : ℝ)) := by
        norm_num [ Complex.ofReal_tsum ];
      -- Since $\sum_{n=0}^{\infty} \frac{1}{(x+n)^2}$ converges uniformly, we can apply the fact that the limit of a uniformly convergent series of continuous functions is continuous.
      have h_cont : Filter.Tendsto (fun x : ℝ => ∑' n : ℕ, (1 / ((x + n : ℝ) ^ 2 : ℝ))) Filter.atTop (nhds (∑' n : ℕ, (0 : ℝ))) := by
        refine' ( tendsto_tsum_of_dominated_convergence _ _ _ );
        use fun k => 1 / ( k + 1 ) ^ 2;
        · simpa using summable_nat_add_iff 1 |>.2 <| Real.summable_one_div_nat_pow.2 one_lt_two;
        · exact fun k => tendsto_const_nhds.div_atTop ( Filter.tendsto_pow_atTop ( by positivity ) |> Filter.Tendsto.comp <| Filter.tendsto_id.atTop_add tendsto_const_nhds );
        · filter_upwards [ Filter.eventually_gt_atTop 1 ] with n hn using fun k => by rw [ Real.norm_of_nonneg ( by positivity ) ] ; exact one_div_le_one_div_of_le ( by positivity ) ( by ring_nf; nlinarith ) ;
      rw [ Filter.tendsto_congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with x hx using h_uniform x hx ) ] ; simpa using Complex.continuous_ofReal.continuousAt.tendsto.comp h_cont;

#check Real.eulerMascheroniConstant