/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 028f042c-7bf3-44de-8bee-140a756108d4

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.

-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

noncomputable def digamma (z : ℂ) : ℂ := (deriv Complex.Gamma z) / (Complex.Gamma z)
noncomputable def trigamma (z : ℂ) : ℂ := ∑' n : ℕ, 1 / (z + n)^2
noncomputable def a (ξ : ℝ) : ℝ := Real.log Real.pi - (digamma (1/4 + Complex.I * Real.pi * ξ)).re

theorem im_trigamma_neg {z : ℂ} (hz : 0 < z.re) (hzi : 0 < z.im) :
    (trigamma z).im < 0 := by
      -- The series representation of the trigamma function is convergent and the imaginary part of each term is negative.
      have h_series : (trigamma z).im = ∑' n : ℕ, (1 / (z + n)^2).im := by
        rw [ ← Complex.im_tsum ];
        · rfl;
        · -- We'll use the fact that if the real part of $z$ is positive, then the series $\sum_{n=0}^{\infty} \frac{1}{(z+n)^2}$ converges.
          have h_summable : Summable (fun n : ℕ => 1 / (n + z.re)^2 : ℕ → ℝ) := by
            have h_trigamma_real : Summable (fun n : ℕ => (1 : ℝ) / (n : ℝ)^2) := by
              exact Real.summable_one_div_nat_pow.2 one_lt_two;
            rw [ ← summable_nat_add_iff 1 ] at *;
            exact Summable.of_nonneg_of_le ( fun n => by positivity ) ( fun n => by gcongr ; linarith ) h_trigamma_real;
          rw [ ← summable_norm_iff ] at *;
          norm_num [ Complex.normSq, Complex.sq_norm ] at *;
          exact Summable.of_nonneg_of_le ( fun n => inv_nonneg.2 ( by nlinarith ) ) ( fun n => inv_anti₀ ( by positivity ) ( by nlinarith ) ) h_summable;
      -- The imaginary part of each term $\frac{1}{(z+n)^2}$ is $-\frac{2(z+n).re(z+n).im}{((z+n).re^2 + (z+n).im^2)^2}$.
      have h_im_term : ∀ n : ℕ, (1 / (z + n)^2).im = - (2 * (z.re + n) * z.im) / ((z.re + n)^2 + z.im^2)^2 := by
        intro n; norm_num [ Complex.normSq, Complex.div_im, sq ] ; ring;
        rw [ inv_pow ] ; ring;
      rw [ h_series, tsum_congr h_im_term ];
      norm_num [ neg_div, tsum_neg ];
      refine' Summable.tsum_pos ..;
      -- We'll use the fact that if the denominator grows faster than the numerator, the series converges.
      have h_summable : Summable (fun n : ℕ => (2 * (z.re + n) * z.im) / ((z.re + n)^2 + z.im^2)^2) := by
        have h_abs_conv : Summable (fun n : ℕ => (2 * (z.re + n) * z.im) / ((z.re + n)^2)^2) := by
          field_simp;
          have h_abs_conv : Summable (fun n : ℕ => (1 : ℝ) / (z.re + n)^3) := by
            have h_pseries : Summable (fun n : ℕ => (1 : ℝ) / (n : ℝ)^3) := by
              exact Real.summable_one_div_nat_pow.2 ( by norm_num );
            rw [ ← summable_nat_add_iff ⌈z.re⌉₊ ];
            exact Summable.of_nonneg_of_le ( fun n => by positivity ) ( fun n => by simpa using inv_anti₀ ( by positivity ) ( pow_le_pow_left₀ ( by positivity ) ( show ( z.re + ( n + ⌈z.re⌉₊ ) : ℝ ) ≥ n + ⌈z.re⌉₊ by linarith ) 3 ) ) ( h_pseries.comp_injective ( add_left_injective ⌈z.re⌉₊ ) );
          convert h_abs_conv.mul_left ( 2 * z.im ) using 2 ; ring;
        exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( mul_nonneg ( mul_nonneg zero_le_two ( add_nonneg hz.le ( Nat.cast_nonneg n ) ) ) hzi.le ) ( sq_nonneg _ ) ) ( fun n => div_le_div_of_nonneg_left ( mul_nonneg ( mul_nonneg zero_le_two ( add_nonneg hz.le ( Nat.cast_nonneg n ) ) ) hzi.le ) ( by positivity ) ( by gcongr ; nlinarith ) ) h_abs_conv;
      exacts [ h_summable, fun n => div_nonneg ( mul_nonneg ( mul_nonneg zero_le_two ( add_nonneg hz.le ( Nat.cast_nonneg _ ) ) ) hzi.le ) ( sq_nonneg _ ), 0, by positivity ]

theorem deriv_a_eq {ξ : ℝ} (hξ : 0 < ξ) :
    deriv a ξ = Real.pi * (deriv digamma (1/4 + Complex.I * Real.pi * ξ)).im := by
      -- By definition of the derivative, we know that
      have h_deriv_def : HasDerivAt (fun ξ : ℝ => Real.log Real.pi - (digamma (1 / 4 + Complex.I * Real.pi * ξ)).re) (Real.pi * (deriv digamma (1 / 4 + Complex.I * Real.pi * ξ)).im) ξ := by
        have h_deriv : HasDerivAt (fun ξ : ℝ => digamma (1 / 4 + Complex.I * Real.pi * ξ)) (Real.pi * Complex.I * deriv digamma (1 / 4 + Complex.I * Real.pi * ξ)) ξ := by
          have h_chain : HasDerivAt (fun ξ : ℂ => digamma ξ) (deriv digamma (1 / 4 + Complex.I * Real.pi * ξ)) (1 / 4 + Complex.I * Real.pi * ξ) := by
            have h_analytic : AnalyticAt ℂ (fun z => (deriv Complex.Gamma z) / Complex.Gamma z) (1 / 4 + Complex.I * Real.pi * ξ) := by
              have h_analytic : AnalyticAt ℂ (fun z => Complex.Gamma z) (1 / 4 + Complex.I * Real.pi * ξ) := by
                apply_rules [ DifferentiableOn.analyticAt ];
                refine' fun z hz => Complex.differentiableAt_Gamma _ _ |> DifferentiableAt.differentiableWithinAt;
                exact { z : ℂ | 0 < z.re };
                · exact fun m => ne_of_apply_ne Complex.re <| by norm_num; linarith [ hz.out ];
                · exact IsOpen.mem_nhds ( isOpen_lt continuous_const Complex.continuous_re ) ( by norm_num [ Complex.ext_iff ] );
              apply_rules [ AnalyticAt.div, AnalyticAt.deriv ];
              refine' Complex.Gamma_ne_zero _ ; norm_num [ Complex.ext_iff ] ; aesop;
            exact h_analytic.differentiableAt.hasDerivAt;
          convert h_chain.comp ξ ( HasDerivAt.add ( hasDerivAt_const _ _ ) ( HasDerivAt.mul ( hasDerivAt_const _ _ ) ( hasDerivAt_id _ |> HasDerivAt.ofReal_comp ) ) ) using 1 ; norm_num ; ring;
        rw [ hasDerivAt_iff_tendsto_slope_zero ] at *;
        convert Complex.continuous_re.continuousAt.tendsto.comp ( h_deriv.neg ) using 2 <;> norm_num ; ring;
      exact h_deriv_def.deriv

theorem continuousOn_a : ContinuousOn a (Set.Ici 0) := by
  refine' ContinuousOn.sub continuousOn_const _;
  -- The digamma function is analytic in the right half-plane, and the real part of an analytic function is continuous.
  have h_analytic : ∀ z : ℂ, 0 < z.re → AnalyticAt ℂ (fun z => digamma z) z := by
    intro z hz
    have h_analytic : AnalyticAt ℂ (fun z => Complex.Gamma z) z := by
      refine' DifferentiableOn.analyticAt _ _;
      exact { w : ℂ | 0 < w.re };
      · intro w hw; exact Complex.differentiableAt_Gamma _ ( by contrapose! hw; aesop ) |> DifferentiableAt.differentiableWithinAt;
      · exact IsOpen.mem_nhds ( isOpen_lt continuous_const Complex.continuous_re ) hz
    have h_analytic_deriv : AnalyticAt ℂ (fun z => deriv Complex.Gamma z) z := by
      apply_rules [ AnalyticAt.deriv, h_analytic ]
    have h_analytic_div : AnalyticAt ℂ (fun z => deriv Complex.Gamma z / Complex.Gamma z) z := by
      exact h_analytic_deriv.div h_analytic <| Complex.Gamma_ne_zero_of_re_pos hz
    exact h_analytic_div.congr (by
    filter_upwards [ IsOpen.mem_nhds ( isOpen_lt continuous_const Complex.continuous_re ) hz ] with x hx using by unfold digamma; aesop;);
  exact continuousOn_of_forall_continuousAt fun x hx => Complex.continuous_re.continuousAt.comp <| h_analytic _ ( by simp +decide [ Complex.ext_iff ] ) |> AnalyticAt.continuousAt |> ContinuousAt.comp <| Continuous.continuousAt <| by continuity;

theorem trigamma_add_one {z : ℂ} (hz : 0 < z.re) :
    trigamma (z + 1) = trigamma z - 1 / z ^ 2 := by
      -- By shifting the index of summation, we can rewrite the series for trigamma(z+1).
      have h_shift : ∑' n : ℕ, 1 / (z + 1 + n)^2 = ∑' m : ℕ, 1 / (m + z)^2 - 1 / z^2 := by
        rw [ eq_comm, Summable.tsum_eq_zero_add ];
        · norm_num [ add_comm, add_left_comm, add_assoc ];
        · -- Since $|m + z| \geq m/2$ for sufficiently large $m$, we can compare the series to $\sum_{m=1}^{\infty} \frac{4}{m^2}$, which converges.
          have h_comparison : ∃ C > 0, ∀ m : ℕ, m ≥ ⌈2 * ‖z‖⌉₊ → ‖(m + z)⁻¹ ^ 2‖ ≤ C / m ^ 2 := by
            -- Since $|m + z| \geq m/2$ for $m \geq 2|z|$, we have $|(m + z)⁻¹| \leq 2/m$.
            have h_bound : ∀ m : ℕ, m ≥ ⌈2 * ‖z‖⌉₊ → ‖(m + z)⁻¹‖ ≤ 2 / m := by
              intros m hm
              have h_abs : ‖m + z‖ ≥ m / 2 := by
                have := norm_add_le ( m + z ) ( -z ) ; norm_num at * ; linarith;
              simpa using inv_anti₀ ( div_pos ( Nat.cast_pos.mpr <| Nat.pos_of_ne_zero <| by rintro rfl; norm_num at hm; linarith [ show 0 < ‖z‖ from norm_pos_iff.mpr <| by aesop ] ) zero_lt_two ) h_abs;
            exact ⟨ 4, by norm_num, fun m hm => by simpa using pow_le_pow_left₀ ( by positivity ) ( h_bound m hm ) 2 |> le_trans <| by ring_nf; norm_num ⟩;
          have h_summable : Summable (fun m : ℕ => ‖(m + z)⁻¹ ^ 2‖) := by
            rw [ ← summable_nat_add_iff ⌈2 * ‖z‖⌉₊ ];
            exact Summable.of_nonneg_of_le ( fun n => norm_nonneg _ ) ( fun n => h_comparison.choose_spec.2 _ ( Nat.le_add_left _ _ ) ) ( Summable.mul_left _ <| by simpa using summable_nat_add_iff ⌈2 * ‖z‖⌉₊ |>.2 <| Real.summable_one_div_nat_pow.2 one_lt_two );
          exact Summable.of_norm <| by simpa using h_summable;
      unfold trigamma; ring_nf at *; aesop;

theorem diff_digamma_trigamma_add_one {z : ℂ} (hz : 0 < z.re) :
    deriv digamma (z + 1) - trigamma (z + 1) = deriv digamma z - trigamma z := by
      -- Using the recurrence relation for the digamma function, we have $\psi(z+1) = \psi(z) + \frac{1}{z}$.
      have h_recurrence : ∀ z : ℂ, 0 < z.re → digamma (z + 1) = digamma z + 1 / z := by
        -- Using the recurrence relation of the Gamma function, we have $\Gamma(z+1) = z \Gamma(z)$, which leads to $\frac{d}{dz} \Gamma(z+1) = \Gamma(z) + z \frac{d}{dz} \Gamma(z)$.
        have h_gamma_recurrence : ∀ z : ℂ, 0 < z.re → deriv Complex.Gamma (z + 1) = Complex.Gamma z + z * deriv Complex.Gamma z := by
          intro z hz;
          have h_gamma_diff : deriv (fun z => Complex.Gamma (z + 1)) z = deriv Complex.Gamma (z + 1) := by
            exact?;
          rw [ ← h_gamma_diff ];
          convert HasDerivAt.deriv ( HasDerivAt.congr_of_eventuallyEq ( HasDerivAt.mul ( hasDerivAt_id z ) ( Complex.differentiableAt_Gamma _ _ |> DifferentiableAt.hasDerivAt ) ) <| Filter.eventuallyEq_of_mem ( isOpen_ne.mem_nhds <| show z ≠ 0 by rintro rfl; norm_num at hz ) fun x hx => Complex.Gamma_add_one x hx ) using 1;
          · norm_num;
          · exact fun m => ne_of_apply_ne Complex.re <| by norm_num; linarith;
        -- Substitute the recurrence relation for the Gamma function into the expression for the digamma function.
        intro z hz
        have h_digamma_recurrence : deriv Complex.Gamma (z + 1) / Complex.Gamma (z + 1) = (Complex.Gamma z + z * deriv Complex.Gamma z) / (z * Complex.Gamma z) := by
          rw [ h_gamma_recurrence z hz, Complex.Gamma_add_one ] ; ring ; aesop;
        unfold digamma;
        rw [ h_digamma_recurrence, div_add_div ] <;> ring <;> norm_num [ Complex.Gamma_ne_zero_of_re_pos hz, show z ≠ 0 from by rintro rfl; norm_num at hz ];
      -- Using the recurrence relation for the digamma function, we have $\psi'(z+1) = \psi'(z) - \frac{1}{z^2}$.
      have h_recurrence_deriv : ∀ z : ℂ, 0 < z.re → deriv digamma (z + 1) = deriv digamma z - 1 / z^2 := by
        intros z hz
        have h_diff : deriv (fun z => digamma z + 1 / z) z = deriv digamma z - 1 / z^2 := by
          convert HasDerivAt.deriv ( HasDerivAt.add ( hasDerivAt_deriv_iff.mpr _ ) ( HasDerivAt.div ( hasDerivAt_const _ _ ) ( hasDerivAt_id z ) _ ) ) using 1 <;> norm_num [ hz.ne' ];
          · ring;
          · refine' DifferentiableAt.div _ _ _;
            · have h_diff : AnalyticAt ℂ (deriv Complex.Gamma) z := by
                have h_analytic : AnalyticAt ℂ Complex.Gamma z := by
                  apply_rules [ DifferentiableOn.analyticAt ];
                  rotate_right;
                  exact { w : ℂ | 0 < w.re };
                  · intro w hw;
                    refine' DifferentiableAt.differentiableWithinAt _;
                    apply_rules [ Complex.differentiableAt_Gamma ];
                    exact fun m => ne_of_apply_ne Complex.re <| by norm_num; linarith [ hw.out ];
                  · exact IsOpen.mem_nhds ( isOpen_lt continuous_const Complex.continuous_re ) hz
                exact h_analytic.deriv;
              exact h_diff.differentiableAt;
            · exact Complex.differentiableAt_Gamma _ ( by contrapose! hz; aesop );
            · exact Complex.Gamma_ne_zero_of_re_pos hz;
          · exact ne_of_apply_ne Complex.re hz.ne';
        rw [ ← h_diff, show deriv ( fun z => digamma z + 1 / z ) z = deriv ( fun z => digamma ( z + 1 ) ) z by exact Filter.EventuallyEq.deriv_eq ( by filter_upwards [ IsOpen.mem_nhds ( isOpen_lt continuous_const Complex.continuous_re ) hz ] with x hx using by rw [ h_recurrence x hx ] ) ];
        exact?;
      rw [ h_recurrence_deriv z hz, trigamma_add_one ] ; ring;
      exact?

theorem trigamma_tendsto_zero :
    Filter.Tendsto (fun x : ℝ => trigamma x) Filter.atTop (nhds 0) := by
      -- We'll use the fact that the sum of the series $\sum_{n=0}^{\infty} \frac{1}{(x+n)^2}$ converges to $\frac{1}{x^2}$ as $x \to \infty$.
      have h_sum : Filter.Tendsto (fun x : ℝ => ∑' n : ℕ, (1 / (x + n : ℝ) ^ 2)) Filter.atTop (nhds 0) := by
        -- We can use the fact that the series $\sum_{n=1}^\infty \frac{1}{n^2}$ converges to $\frac{\pi^2}{6}$.
        have h_sum : Filter.Tendsto (fun x : ℝ => ∑' n : ℕ, (1 / (x + n : ℝ) ^ 2)) Filter.atTop (nhds (∑' n : ℕ, (0 : ℝ))) := by
          refine' ( tendsto_tsum_of_dominated_convergence _ _ _ );
          use fun k => 1 / ( k + 1 ) ^ 2;
          · simpa using summable_nat_add_iff 1 |>.2 <| Real.summable_one_div_nat_pow.2 one_lt_two;
          · exact fun k => tendsto_const_nhds.div_atTop ( Filter.tendsto_pow_atTop ( by positivity ) |> Filter.Tendsto.comp <| Filter.tendsto_id.atTop_add tendsto_const_nhds );
          · norm_num;
            exact ⟨ 1, fun x hx k => inv_anti₀ ( by positivity ) ( by ring_nf; nlinarith ) ⟩;
        aesop;
      convert Complex.continuous_ofReal.continuousAt.tendsto.comp h_sum using 2 ; norm_num [ trigamma ];
      rw [ Complex.ofReal_tsum ] ; norm_num

lemma diff_const (z : ℂ) (hz : 0 < z.re) (n : ℕ) :
    deriv digamma (z + n) - trigamma (z + n) = deriv digamma z - trigamma z := by
      induction' n with n ih;
      · norm_num;
      · have := diff_digamma_trigamma_add_one ( show 0 < ( z + n : ℂ ).re from by simpa using by linarith );
        simp_all +decide [ add_assoc ]

lemma trigamma_tendsto_zero_complex (z : ℂ) (hz : 0 < z.re) :
    Filter.Tendsto (fun n : ℕ => trigamma (z + n)) Filter.atTop (nhds 0) := by
      -- We have trigamma(z+n) = sum_{k=0}^infty 1/(z+n+k)^2.
      have h_trigamma_sum : ∀ n : ℕ, trigamma (z + n) = ∑' k : ℕ, 1 / (z + n + k)^2 := by
        exact?;
      -- For large $n$, $|z+n+k|^2 \geq (Re(z)+n+k)^2$, so $|1/(z+n+k)^2| \leq 1/(Re(z)+n+k)^2$.
      have h_bound : ∀ n : ℕ, n > |z.im| → ‖trigamma (z + n)‖ ≤ ∑' k : ℕ, 1 / (z.re + n + k)^2 := by
        intro n hn
        rw [h_trigamma_sum n]
        have h_bound : ∀ k : ℕ, ‖1 / (z + n + k)^2‖ ≤ 1 / (z.re + n + k)^2 := by
          norm_num [ Complex.normSq, Complex.norm_def ];
          exact fun k => inv_anti₀ ( by positivity ) ( by rw [ Real.sq_sqrt ( by nlinarith ) ] ; nlinarith );
        refine' le_trans ( norm_tsum_le_tsum_norm _ ) ( Summable.tsum_le_tsum h_bound _ _ );
        · refine' Summable.of_nonneg_of_le ( fun k => norm_nonneg _ ) ( fun k => h_bound k ) _;
          -- The series $\sum_{k=0}^\infty \frac{1}{(z.re + n + k)^2}$ is a convergent p-series with $p=2$.
          have h_pseries : Summable (fun k : ℕ => 1 / (k + z.re + n : ℝ)^2) := by
            have h_summable : Summable (fun k : ℕ => (1 : ℝ) / (k + z.re + n)^2) := by
              have h_summable : Summable (fun k : ℕ => (1 : ℝ) / (k : ℝ)^2) := by
                exact Real.summable_one_div_nat_pow.2 one_lt_two
              rw [ ← summable_nat_add_iff ( ⌈z.re⌉₊ + n ) ] at *;
              exact Summable.of_nonneg_of_le ( fun _ => by positivity ) ( fun _ => by gcongr ; linarith [ Nat.le_ceil z.re ] ) h_summable;
            convert h_summable using 1;
          exact h_pseries.congr fun k => by ring;
        · refine' Summable.of_nonneg_of_le ( fun k => norm_nonneg _ ) ( fun k => h_bound k ) _;
          have h_summable : Summable (fun k : ℕ => 1 / (k : ℝ)^2) := by
            exact Real.summable_one_div_nat_pow.2 one_lt_two;
          rw [ ← summable_nat_add_iff ( ⌈z.re + n⌉₊ + 1 ) ];
          exact_mod_cast h_summable.comp_injective ( add_left_injective ( ⌈z.re + n⌉₊ + 1 ) ) |> Summable.of_nonneg_of_le ( fun _ => by positivity ) fun _ => by simpa using inv_anti₀ ( by positivity ) ( by ring_nf; nlinarith [ Nat.le_ceil ( z.re + n ) ] ) ;
        · have h_summable : Summable (fun k : ℕ => 1 / (k : ℝ)^2) := by
            exact Real.summable_one_div_nat_pow.2 one_lt_two;
          rw [ ← summable_nat_add_iff ( ⌈z.re + n⌉₊ + 1 ) ] at *;
          exact Summable.of_nonneg_of_le ( fun _ => by positivity ) ( fun _ => by gcongr ; linarith [ Nat.le_ceil ( z.re + n ) ] ) h_summable;
      -- Since $\sum_{k=0}^{\infty} \frac{1}{(z.re + n + k)^2}$ converges to 0 as $n \to \infty$, we can apply the squeeze theorem.
      have h_sum_zero : Filter.Tendsto (fun n : ℕ => ∑' k : ℕ, 1 / (z.re + n + k : ℝ)^2) Filter.atTop (nhds 0) := by
        convert tendsto_sum_nat_add fun k => 1 / ( z.re + k : ℝ ) ^ 2 using 2;
        exact tsum_congr fun _ => by push_cast; ring;
      exact squeeze_zero_norm' ( Filter.eventually_atTop.mpr ⟨ ⌈|z.im|⌉₊ + 1, fun n hn => h_bound n <| Nat.lt_of_ceil_lt hn ⟩ ) h_sum_zero

lemma deriv_digamma_add_one (z : ℂ) (hz : 0 < z.re) :
    deriv digamma (z + 1) = deriv digamma z - 1 / z ^ 2 := by
      -- To prove the equality, it suffices to show that $deriv \digamma(z+1) - trigamma(z+1) = deriv \digamma(z) - trigamma(z)$.
      suffices h_eq : deriv digamma (z + 1) - trigamma (z + 1) = deriv digamma z - trigamma z by
        have := trigamma_add_one ( show 0 < z.re from hz );
        linear_combination' h_eq + this;
      exact?

#check Complex.GammaSeq
#check Complex.GammaSeq_tendsto_Gamma

#print Complex.GammaSeq

noncomputable def digammaSeq (z : ℂ) (n : ℕ) : ℂ := (Real.log n : ℂ) - ∑ k ∈ Finset.range (n + 1), 1 / (z + k)

lemma digammaSeq_deriv (z : ℂ) (n : ℕ) (hz : ∀ k ≤ n, z ≠ -k) :
    deriv (fun z => digammaSeq z n) z = ∑ k ∈ Finset.range (n + 1), 1 / (z + k)^2 := by
      unfold digammaSeq;
      convert HasDerivAt.deriv ( HasDerivAt.const_sub _ <| HasDerivAt.sum fun i hi => ?_ ) using 1;
      congr!;
      any_goals exact Finset.range ( n + 1 );
      rotate_left;
      rotate_left;
      use fun i => fun x => 1 / ( x + i );
      use fun i => -1 / ( z + i ) ^ 2;
      · simpa [ div_eq_mul_inv ] using HasDerivAt.inv ( HasDerivAt.add ( hasDerivAt_id z ) ( hasDerivAt_const _ _ ) ) ( show ( z + i : ℂ ) ≠ 0 from by exact fun h => hz i ( Finset.mem_range_succ_iff.mp hi ) <| by linear_combination' h );
      · norm_num;
      · norm_num [ neg_div ]

lemma digammaSeq_eq (z : ℂ) (n : ℕ) (hz : ∀ k ≤ n, z ≠ -k) :
    digammaSeq z n = (Real.log n : ℂ) - (1 / z + ∑ k ∈ Finset.range n, 1 / (z + 1 + k)) := by
      unfold digammaSeq
      simp [Finset.sum_range_succ'];
      ac_rfl

lemma deriv_digammaSeq_tendsto_trigamma (z : ℂ) (hz : 0 < z.re) :
    Filter.Tendsto (fun n => deriv (fun z => digammaSeq z n) z) Filter.atTop (nhds (trigamma z)) := by
      -- Apply the fact that the sequence of partial sums converges to the infinite sum.
      have h_partial_sums : Filter.Tendsto (fun n : ℕ => ∑ k ∈ Finset.range (n + 1), (1 / (z + k)^2)) Filter.atTop (nhds (∑' k : ℕ, (1 / (z + k)^2))) := by
        refine' ( Summable.hasSum _ ) |> HasSum.tendsto_sum_nat |> Filter.Tendsto.comp <| Filter.tendsto_add_atTop_nat 1;
        have h_abs_conv : Summable (fun k : ℕ => ‖(1 / (z + k)^2 : ℂ)‖) := by
          -- Since $|z + k| \geq k$ for all $k$, we have $|1 / (z + k)^2| \leq 1 / k^2$.
          have h_bound : ∀ k : ℕ, k ≥ 1 → ‖(1 / (z + k)^2 : ℂ)‖ ≤ 1 / (k : ℝ)^2 := by
            norm_num [ Complex.normSq, Complex.norm_def ];
            exact fun k hk => inv_anti₀ ( by positivity ) ( by rw [ Real.sq_sqrt ( by nlinarith ) ] ; nlinarith [ show ( k : ℝ ) ≥ 1 by norm_cast ] );
          rw [ ← summable_nat_add_iff 1 ];
          exact Summable.of_nonneg_of_le ( fun n => norm_nonneg _ ) ( fun n => h_bound _ le_add_self ) ( by simpa using summable_nat_add_iff 1 |>.2 <| Real.summable_one_div_nat_pow.2 one_lt_two );
        exact h_abs_conv.of_norm;
      convert h_partial_sums using 2;
      convert digammaSeq_deriv z ‹_› _ using 1;
      exact fun k hk => ne_of_apply_ne Complex.re <| by norm_num; linarith