/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f86d36da-3cb8-47bc-a4c7-a1398634b1aa

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.

-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of digamma, trigamma, a(ξ), and the P_A functional components.
-/
open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise


open Real Complex MeasureTheory Set
open scoped BigOperators

-- Digamma function
def digamma (z : ℂ) : ℂ := (deriv Complex.Gamma z) / (Complex.Gamma z)

-- Trigamma function
def trigamma (z : ℂ) : ℂ := ∑' n : ℕ, 1 / (z + n)^2

-- Archimedean density a(ξ)
def a (ξ : ℝ) : ℝ := Real.log Real.pi - (digamma (1/4 + Complex.I * Real.pi * ξ)).re

-- Fixed parameters
def B_min : ℝ := 3
def t_sym : ℝ := 3 / 50
def c_star : ℝ := 11 / 10

-- Fejér×heat window
def w (B t ξ : ℝ) : ℝ :=
  max 0 (1 - |ξ| / B) * Real.exp (-4 * Real.pi^2 * t * ξ^2)

-- Weighted density
def g (B t ξ : ℝ) : ℝ := a ξ * w B t ξ

-- Archimedean symbol (period-1 periodized)
def P_A (B t θ : ℝ) : ℝ :=
  2 * Real.pi * ∑' (m : ℤ), g B t (θ + m)

/-
The imaginary part of the trigamma function is negative for z in the upper right quadrant.
-/
lemma im_trigamma_neg {z : ℂ} (hz : 0 < z.re) (hzi : 0 < z.im) :
    (trigamma z).im < 0 := by
      unfold trigamma;
      rw [ Complex.im_tsum ];
      · -- Let's simplify the expression for the imaginary part.
        have h_im : ∀ n : ℕ, (1 / (z + n) ^ 2).im = -2 * z.im * (z.re + n) / ((z.re + n) ^ 2 + z.im ^ 2) ^ 2 := by
          norm_num [ Complex.normSq, Complex.div_im, sq ] ; intros ; ring;
          rw [ inv_pow ] ; ring;
        rw [ tsum_congr h_im ];
        rw [ Summable.tsum_eq_zero_add ];
        · norm_num [ div_eq_mul_inv, tsum_neg, tsum_mul_left ];
          exact lt_of_lt_of_le ( neg_lt_zero.mpr ( by positivity ) ) ( tsum_nonneg fun _ => by positivity );
        · have h_summable : Summable (fun n : ℕ => (z.re + n) / ((z.re + n) ^ 2 + z.im ^ 2) ^ 2) := by
            have h_summable : Summable (fun n : ℕ => (z.re + n) / ((z.re + n) ^ 2) ^ 2) := by
              have h_summable : Summable (fun n : ℕ => (1 : ℝ) / ((z.re + n) ^ 3)) := by
                have h_summable : Summable (fun n : ℕ => (1 / (n : ℝ) ^ 3)) := by
                  exact Real.summable_one_div_nat_pow.2 ( by norm_num );
                rw [ ← summable_nat_add_iff ⌈z.re⌉₊ ] at *;
                exact Summable.of_nonneg_of_le ( fun n => by positivity ) ( fun n => by gcongr ; linarith [ Nat.le_ceil z.re ] ) h_summable;
              grind;
            exact Summable.of_nonneg_of_le ( fun n => div_nonneg ( by positivity ) ( by positivity ) ) ( fun n => div_le_div_of_nonneg_left ( by positivity ) ( by positivity ) ( by gcongr ; nlinarith ) ) h_summable;
          convert h_summable.mul_left ( -2 * z.im ) using 2 ; ring;
      · -- We'll use the fact that if the denominator grows sufficiently faster than the numerator, the series converges.
        have h_summable : Summable (fun n : ℕ => (1 : ℝ) / (n + z.re)^2) := by
          have h_summable : Summable (fun n : ℕ => (1 : ℝ) / (n : ℝ)^2) := by
            exact Real.summable_one_div_nat_pow.2 one_lt_two;
          rw [ ← summable_nat_add_iff ⌈z.re⌉₊ ] at *;
          exact Summable.of_nonneg_of_le ( fun n => by positivity ) ( fun n => by gcongr ; linarith [ Nat.le_ceil z.re ] ) h_summable;
        rw [ ← summable_norm_iff ] at *;
        refine' .of_nonneg_of_le ( fun n => norm_nonneg _ ) ( fun n => _ ) h_summable;
        norm_num [ Complex.normSq, Complex.sq_norm ];
        exact inv_anti₀ ( by positivity ) ( by nlinarith )

/-
The derivative of a(ξ) is related to the imaginary part of the derivative of the digamma function.
-/
lemma deriv_a_eq {ξ : ℝ} (hξ : 0 < ξ) :
    deriv a ξ = Real.pi * (deriv (fun z : ℂ => digamma z) (1/4 + Complex.I * Real.pi * ξ)).im := by
      unfold a;
      -- The digamma function is differentiable at $1/4 + i\pi\xi$ because $1/4 + i\pi\xi$ is not a non-positive integer.
      have h_diff : DifferentiableAt ℂ (fun z => digamma z) (1 / 4 + Complex.I * Real.pi * ξ) := by
        refine' DifferentiableAt.div _ _ _ <;> norm_num;
        · have h_gamma_deriv : AnalyticAt ℂ Complex.Gamma (1 / 4 + Complex.I * Real.pi * ξ) := by
            apply_rules [ DifferentiableOn.analyticAt, Complex.differentiableAt_Gamma ];
            refine' fun z hz => Complex.differentiableAt_Gamma _ _ |> DifferentiableAt.differentiableWithinAt;
            exact { z : ℂ | z.re > 0 };
            · exact fun m => ne_of_apply_ne Complex.re <| by norm_num; linarith [ hz.out ] ;
            · exact IsOpen.mem_nhds ( isOpen_lt continuous_const Complex.continuous_re ) ( by norm_num );
          exact h_gamma_deriv.deriv.differentiableAt;
        · refine' Complex.differentiableAt_Gamma _ _ ; norm_num [ Complex.ext_iff ];
          exact fun m hm => by linarith;
        · rw [ Complex.Gamma_eq_zero_iff ] ; norm_num [ Complex.ext_iff ];
          exact fun x hx => by linarith;
      convert HasDerivAt.deriv _ using 1;
      have h_deriv : HasDerivAt (fun ξ : ℝ => digamma (1 / 4 + Complex.I * Real.pi * ξ)) (Complex.I * Real.pi * (deriv (fun z => digamma z) (1 / 4 + Complex.I * Real.pi * ξ))) ξ := by
        convert HasDerivAt.comp ξ ( h_diff.hasDerivAt ) ( HasDerivAt.add ( hasDerivAt_const _ _ ) ( HasDerivAt.mul ( hasDerivAt_const _ _ ) ( hasDerivAt_id _ |> HasDerivAt.ofReal_comp ) ) ) using 1 ; norm_num ; ring;
      rw [ hasDerivAt_iff_tendsto_slope_zero ] at *;
      convert Complex.continuous_re.continuousAt.tendsto.comp h_deriv |> Filter.Tendsto.neg using 2 <;> norm_num ; ring

/-
The function a(ξ) is continuous for ξ ≥ 0.
-/
lemma continuousOn_a : ContinuousOn a (Ici 0) := by
  refine' ContinuousOn.sub continuousOn_const ( Continuous.continuousOn _ );
  refine' Complex.continuous_re.comp _;
  have h_digamma_cont : ContinuousOn (fun z => deriv Complex.Gamma z / Complex.Gamma z) (Set.univ \ {z : ℂ | z.re ≤ 0 ∧ z.im = 0}) := by
    refine' ContinuousOn.div _ _ _;
    · have h_cont : DifferentiableOn ℂ (deriv Complex.Gamma) (Set.univ \ {z : ℂ | z.re ≤ 0 ∧ z.im = 0}) := by
        have h_cont : DifferentiableOn ℂ Complex.Gamma (Set.univ \ {z : ℂ | z.re ≤ 0 ∧ z.im = 0}) := by
          intro z hz;
          refine' DifferentiableAt.differentiableWithinAt _;
          apply_rules [ Complex.differentiableAt_Gamma ];
          aesop;
        apply_rules [ DifferentiableOn.deriv, h_cont ];
        exact isOpen_univ.sdiff ( isClosed_Iic.preimage Complex.continuous_re |> IsClosed.inter <| isClosed_eq Complex.continuous_im continuous_const );
      exact h_cont.continuousOn;
    · refine' continuousOn_of_forall_continuousAt fun z hz => Complex.differentiableAt_Gamma _ _ |> DifferentiableAt.continuousAt;
      aesop;
    · intro z hz; rw [ Ne.eq_def, Complex.Gamma_eq_zero_iff ] ; aesop;
  refine' continuous_iff_continuousAt.mpr _;
  intro x;
  refine' ContinuousAt.comp ( h_digamma_cont.continuousAt _ ) _;
  · refine' IsOpen.mem_nhds _ _ <;> norm_num [ Complex.ext_iff ];
    exact isOpen_univ.sdiff ( isClosed_Iic.preimage Complex.continuous_re |> IsClosed.inter <| isClosed_eq Complex.continuous_im continuous_const );
  · exact Continuous.continuousAt ( by continuity )

/-
The series defining the trigamma function converges for z with positive real part.
-/
lemma trigamma_summable {z : ℂ} (hz : 0 < z.re) :
    Summable (fun n : ℕ => 1 / (z + n)^2) := by
      have h_abs_conv : Summable (fun n : ℕ => (1 : ℝ) / (n : ℝ)^2) := by
        exact Real.summable_one_div_nat_pow.2 one_lt_two;
      rw [ ← summable_norm_iff ];
      have h_bound : ∀ n : ℕ, n ≥ 1 → ‖(z + n)‖ ≥ n * Real.sqrt (z.re / (z.re + 1)) := by
        intro n hn; rw [ Complex.norm_def ] ; rw [ Complex.normSq_add ] ; norm_num [ Complex.normSq ];
        refine Real.le_sqrt_of_sq_le ?_;
        rw [ mul_pow, Real.sq_sqrt ] <;> nlinarith [ show ( n : ℝ ) ≥ 1 by norm_cast, div_mul_cancel₀ z.re ( by positivity : ( z.re + 1 ) ≠ 0 ) ];
      -- Using the bound, we can show that the series is dominated by a convergent p-series.
      have h_dominate : ∀ n : ℕ, n ≥ 1 → ‖(z + n)⁻¹^2‖ ≤ 1 / (n^2 * (z.re / (z.re + 1))) := by
        intros n hn
        specialize h_bound n hn
        have h_norm_sq : ‖(z + n)⁻¹^2‖ = 1 / ‖z + n‖^2 := by
          norm_num;
        exact h_norm_sq.symm ▸ one_div_le_one_div_of_le ( mul_pos ( sq_pos_of_pos ( Nat.cast_pos.mpr hn ) ) ( div_pos hz ( add_pos hz zero_lt_one ) ) ) ( by exact le_trans ( by rw [ mul_pow, Real.sq_sqrt ( div_nonneg hz.le ( add_nonneg hz.le zero_le_one ) ) ] ) ( pow_le_pow_left₀ ( by positivity ) h_bound 2 ) );
      rw [ ← summable_nat_add_iff 1 ];
      exact Summable.of_nonneg_of_le ( fun n => norm_nonneg _ ) ( fun n => by simpa using h_dominate ( n + 1 ) ( by linarith ) ) ( by simpa [ mul_comm ] using Summable.mul_right _ ( h_abs_conv.comp_injective ( Nat.succ_injective ) ) )

/-
The digamma function satisfies the recurrence relation $\psi(z+1) = \psi(z) + 1/z$.
-/
lemma digamma_add_one {z : ℂ} (hz : 0 < z.re) :
    digamma (z + 1) = digamma z + 1 / z := by
      -- Use the recurrence relation for the digamma function: $\psi(z+1) = \psi(z) + \frac{1}{z}$.
      have h_digamma_rec : deriv (fun w => Complex.Gamma w) (z + 1) = deriv (fun w => w * Complex.Gamma w) z := by
        rw [ ← deriv_comp_add_const ];
        exact Filter.EventuallyEq.deriv_eq ( by filter_upwards [ IsOpen.mem_nhds ( isOpen_lt continuous_const Complex.continuous_re ) hz ] with x hx using by rw [ Complex.Gamma_add_one ] ; aesop );
      erw [ deriv_mul ] at h_digamma_rec <;> norm_num at *;
      · unfold digamma;
        rw [ inv_eq_one_div, div_add_div, div_eq_div_iff ] <;> simp_all +decide [ Complex.Gamma_add_one, mul_comm ];
        · rw [ Complex.Gamma_add_one ] <;> ring ; aesop;
        · exact Complex.Gamma_ne_zero_of_re_pos ( by norm_num; linarith );
        · exact ⟨ by rintro rfl; norm_num at hz, Complex.Gamma_ne_zero_of_re_pos hz ⟩;
        · exact Complex.Gamma_ne_zero_of_re_pos hz;
        · aesop;
      · exact Complex.differentiableAt_Gamma _ ( by contrapose! hz; aesop )