#!/bin/bash
# contribution_stats.sh - Accurate contribution statistics
# Counts ONLY code that is actually used in the proof chain

set -e
cd "$(dirname "$0")/.."

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              Q3 CONTRIBUTION STATISTICS                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Date: $(date)"
echo ""

# ═══════════════════════════════════════════════════════════════════
# SECTION 1: Total Q3/ code
# ═══════════════════════════════════════════════════════════════════
echo "═══ Section 1: Total Q3/ Codebase ═══"
q3_lines=$(find Q3 -name "*.lean" -exec cat {} + | wc -l)
q3_theorems=$(grep -r '^theorem' Q3 --include='*.lean' 2>/dev/null | wc -l)
q3_lemmas=$(grep -r '^lemma' Q3 --include='*.lean' 2>/dev/null | wc -l)
q3_defs=$(grep -rE '^(noncomputable )?def ' Q3 --include='*.lean' 2>/dev/null | wc -l)

echo "  Total lines:    $q3_lines"
echo "  Theorems:       $q3_theorems"
echo "  Lemmas:         $q3_lemmas"
echo "  Definitions:    $q3_defs"
echo ""

# ═══════════════════════════════════════════════════════════════════
# SECTION 2: Aristotle contribution IN PROOF CHAIN
# ═══════════════════════════════════════════════════════════════════
echo "═══ Section 2: Aristotle Contribution (IN PROOF CHAIN) ═══"
echo ""

# A) Files in Q3/Proofs/ generated by Aristotle
echo "A) Aristotle-generated files in Q3/Proofs/:"
aristotle_in_q3=0
while IFS= read -r f; do
  if [ -n "$f" ]; then
    lines=$(wc -l < "$f")
    aristotle_in_q3=$((aristotle_in_q3 + lines))
    printf "   %5d  %s\n" "$lines" "$f"
  fi
done < <(grep -l "This file was generated by Aristotle" Q3/Proofs/*.lean Q3/Proofs/**/*.lean 2>/dev/null || true)
echo "   ─────"
printf "   %5d  SUBTOTAL (integrated into Q3/Proofs/)\n" "$aristotle_in_q3"
echo ""

# B) Files imported from aristotle_output/
echo "B) Aristotle files imported from aristotle_output/:"
imported_files=$(grep -rh "import.*aristotle_output" Q3/ --include="*.lean" 2>/dev/null | sed 's/import //' | sort -u || true)
imported_lines=0
if [ -n "$imported_files" ]; then
  for import in $imported_files; do
    # Convert import path to file path
    file_path=$(echo "$import" | tr '.' '/')".lean"
    if [ -f "$file_path" ]; then
      lines=$(wc -l < "$file_path")
      imported_lines=$((imported_lines + lines))
      printf "   %5d  %s\n" "$lines" "$file_path"
    fi
  done
fi
echo "   ─────"
printf "   %5d  SUBTOTAL (imported)\n" "$imported_lines"
echo ""

total_aristotle=$((aristotle_in_q3 + imported_lines))
echo "╔══════════════════════════════════════════════════════════════╗"
printf "║  TOTAL ARISTOTLE IN PROOF CHAIN: %5d lines              ║\n" "$total_aristotle"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ═══════════════════════════════════════════════════════════════════
# SECTION 3: Human/Manual contribution
# ═══════════════════════════════════════════════════════════════════
echo "═══ Section 3: Human/Manual Contribution ═══"
human_lines=$((q3_lines - aristotle_in_q3))
echo "  Q3/ total:              $q3_lines"
echo "  - Aristotle integrated: $aristotle_in_q3"
echo "  ─────────────────────────"
echo "  Human-written in Q3/:   $human_lines"
echo ""

# ═══════════════════════════════════════════════════════════════════
# SECTION 4: Aristotle experiments (NOT in proof chain)
# ═══════════════════════════════════════════════════════════════════
echo "═══ Section 4: Aristotle Experiments (NOT in proof chain) ═══"
all_aristotle_output=$(find aristotle_output -name "*.lean" -exec cat {} + 2>/dev/null | wc -l)
aristotle_files=$(find aristotle_output -name "*.lean" 2>/dev/null | wc -l)
unused=$((all_aristotle_output - imported_lines))

echo "  Total aristotle_output/ files: $aristotle_files"
echo "  Total aristotle_output/ lines: $all_aristotle_output"
echo "  Used in proof chain:           $imported_lines"
echo "  Unused (experiments):          $unused"
echo ""

# ═══════════════════════════════════════════════════════════════════
# SECTION 5: Q3/Proofs/A1prime/ breakdown
# ═══════════════════════════════════════════════════════════════════
echo "═══ Section 5: Q3/Proofs/A1prime/ (New Module) ═══"
if [ -d "Q3/Proofs/A1prime" ]; then
  a1prime_lines=$(find Q3/Proofs/A1prime -name "*.lean" -exec cat {} + | wc -l)
  echo "  Files:"
  for f in Q3/Proofs/A1prime/*.lean; do
    if [ -f "$f" ]; then
      lines=$(wc -l < "$f")
      printf "   %5d  %s\n" "$lines" "$(basename "$f")"
    fi
  done
  echo "   ─────"
  printf "   %5d  TOTAL A1prime/\n" "$a1prime_lines"
else
  echo "  (directory not found)"
fi
echo ""

# ═══════════════════════════════════════════════════════════════════
# SECTION 6: Summary
# ═══════════════════════════════════════════════════════════════════
echo "═══ SUMMARY ═══"
echo ""
pct_aristotle=$((total_aristotle * 100 / q3_lines))
pct_human=$((human_lines * 100 / q3_lines))

echo "  ┌─────────────────────────────────────────────────────────┐"
echo "  │ Source                    │   Lines │   % of Q3/       │"
echo "  ├─────────────────────────────────────────────────────────┤"
printf "  │ Aristotle (in proof)      │ %7d │ %3d%%             │\n" "$total_aristotle" "$pct_aristotle"
printf "  │ Human/Manual              │ %7d │ %3d%%             │\n" "$human_lines" "$pct_human"
echo "  ├─────────────────────────────────────────────────────────┤"
printf "  │ TOTAL Q3/                 │ %7d │ 100%%             │\n" "$q3_lines"
echo "  └─────────────────────────────────────────────────────────┘"
echo ""
echo "  Aristotle experiments (not used): $unused lines"
echo ""
echo "═══ Done ═══"
