/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f6a9eed5-a06e-4686-86cc-37cecb8a620f
-/

/-
This module proves the A3 Bridge Closure theorem using the Rayleigh lower bound strategy.
It defines the necessary constants and structures, including `c_star`, `w_max`, `A3_Data`, and `A3_Props`.
It proves several lemmas:
- `toeplitz_rayleigh_ge_c_star`: Bounds the Toeplitz quadratic form below by `c_star`.
- `sum_exp_bound`: Bounds a sum of exponentials by a geometric series.
- `RKHS_sum_bound`: Bounds the RKHS quadratic form using the exponential sum bound.
- `RKHS_norm_small`: Shows that for small `t`, the RKHS operator norm is small.
Finally, it proves the main theorem `A3_bridge_closure`, which combines these bounds to show that the difference between the Toeplitz and RKHS forms is bounded below by `c_star / 4`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Define c_star as 1.1 and w_max as 2/e.
-/
/-- c* = 11/10 -/
def c_star : ℝ := 11 / 10

/-- w_max = 2/e -/
def w_max : ℝ := 2 / Real.exp 1

/-
Define A3_Data structure and RKHS_kernel function.
-/
/-- Structure bundling the data and assumptions for the A3 bridge problem -/
structure A3_Data where
  /-- w_RKHS weights -/
  w_RKHS : ℕ → ℝ
  /-- ξ points -/
  ξ : ℕ → ℝ
  /-- Toeplitz entries for a_star -/
  ToeplitzEntry_a_star : (M : ℕ) → Fin M → Fin M → ℝ
  /-- Bound on w_RKHS -/
  w_RKHS_le_w_max : ∀ i, w_RKHS i ≤ w_max

/-- RKHS kernel definition -/
def RKHS_kernel (data : A3_Data) (i j : ℕ) (t : ℝ) : ℝ :=
  Real.sqrt (data.w_RKHS i) * Real.sqrt (data.w_RKHS j) * Real.exp (- (data.ξ i - data.ξ j)^2 / (4 * t))

/-
Define A3_Props structure.
-/
/-- Structure bundling the properties and extra data for the A3 bridge problem -/
structure A3_Props (data : A3_Data) where
  /-- a_star symbol -/
  a_star : ℝ → ℝ
  /-- a_star is continuous -/
  h_cont : Continuous a_star
  /-- a_star lower bound -/
  h_bound : ∀ θ ∈ Set.Icc (-1/2 : ℝ) (1/2), c_star ≤ a_star θ
  /-- Abstract Toeplitz matrix constructor -/
  ToeplitzMatrix : (ℝ → ℝ) → (M : ℕ) → Fin M → Fin M → ℝ
  /-- Link between data.ToeplitzEntry_a_star and ToeplitzMatrix -/
  h_toeplitz_eq : ∀ M i j, data.ToeplitzEntry_a_star M i j = ToeplitzMatrix a_star M i j
  /-- Rayleigh lower bound property -/
  h_rayleigh : ∀ (M : ℕ) (hM : M > 0) (P : ℝ → ℝ) (hP_cont : Continuous P)
    (m : ℝ) (hP_ge : ∀ θ ∈ Set.Icc (-1/2 : ℝ) (1/2), m ≤ P θ)
    (v : Fin M → ℝ) (hv : v ≠ 0),
    (∑ i, ∑ j, v i * ToeplitzMatrix P M i j * v j) / (∑ i, v i ^ 2) ≥ m

/-
Prove that the Rayleigh quotient of the Toeplitz matrix is at least c_star, given the properties in A3_Props.
-/
/-- Lemma 1: Toeplitz Rayleigh Bound -/
lemma toeplitz_rayleigh_ge_c_star (data : A3_Data) (props : A3_Props data)
    (M : ℕ) (hM : M > 0) (v : Fin M → ℝ) (hv : v ≠ 0) :
    (∑ i, ∑ j, v i * data.ToeplitzEntry_a_star M i j * v j) / (∑ i, v i ^ 2) ≥ c_star := by
      have := props.h_rayleigh M hM;
      simpa only [ ← props.h_toeplitz_eq ] using this _ props.h_cont _ ( fun θ hθ => props.h_bound θ hθ ) _ hv

/-
Prove that the sum of exp(-k^2/(4t)) for k from 1 to M-1 is bounded by a geometric series sum.
-/
/-- Bound for sum of exponentials -/
lemma sum_exp_bound (t : ℝ) (ht : t > 0) (M : ℕ) :
    ∑ k ∈ Finset.Icc (1 : ℤ) (M - 1), Real.exp (-k^2 / (4 * t)) ≤
    (Real.exp (-1 / (4 * t))) / (1 - Real.exp (-1 / (4 * t))) := by
  -- Bound the sum of exp(-k^2/(4t)) by a geometric series.
  have h_geo_bound : ∀ k : ℤ, 1 ≤ k → Real.exp (-(k : ℝ) ^ 2 / (4 * t)) ≤ Real.exp (-1 / (4 * t)) * (Real.exp (-1 / (4 * t))) ^ (k - 1).natAbs := by
    intro k hk; rw [ ← Real.exp_nat_mul ] ; norm_num [ ← Real.exp_add, ← Real.exp_neg ] ; ring_nf;
    cases abs_cases ( -1 + ( k : ℝ ) ) <;> nlinarith [ show ( k : ℝ ) ≥ 1 by norm_cast, inv_pos.2 ht, mul_inv_cancel₀ ht.ne', sq_nonneg ( k - 1 : ℝ ) ];
  -- Sum the geometric series.
  have h_geo_sum : ∑ k ∈ Finset.Icc 1 (M - 1 : ℤ), (Real.exp (-1 / (4 * t))) ^ (k - 1).natAbs ≤ (∑ k ∈ Finset.range (M - 1), (Real.exp (-1 / (4 * t))) ^ k) := by
    rcases M with ( _ | _ | M ) <;> norm_num;
    refine' le_of_eq ( Finset.sum_bij ( fun x hx => Int.natAbs ( x - 1 ) ) _ _ _ _ ) <;> norm_num;
    · intro a ha₁ ha₂; cases abs_cases ( a - 1 ) <;> linarith;
    · intros; omega;
    · exact fun b hb => ⟨ b + 1, ⟨ by linarith, by linarith ⟩, by norm_num ⟩;
  refine le_trans ( Finset.sum_le_sum fun x hx => h_geo_bound x <| Finset.mem_Icc.mp hx |>.1 ) ?_;
  rw [ ← Finset.mul_sum _ _ _ ];
  refine le_trans ( mul_le_mul_of_nonneg_left h_geo_sum <| Real.exp_nonneg _ ) ?_;
  rw [ le_div_iff₀ ( sub_pos.mpr <| by rw [ Real.exp_lt_one_iff ] ; ring_nf; norm_num; positivity ) ];
  nlinarith [ Real.exp_pos ( -1 / ( 4 * t ) ), pow_pos ( Real.exp_pos ( -1 / ( 4 * t ) ) ) ( M - 1 ), geom_sum_mul ( Real.exp ( -1 / ( 4 * t ) ) ) ( M - 1 ) ]

/-
Prove that if the points are uniform, the RKHS form is bounded by a specific function of t and w_max.
-/
/-- Assumption that the points are uniform -/
def IsUniform (data : A3_Data) : Prop := ∀ i, data.ξ i = i

/-- Bound for the RKHS double sum -/
lemma RKHS_sum_bound (data : A3_Data) (h_unif : IsUniform data) (t : ℝ) (ht : t > 0) (M : ℕ) (v : Fin M → ℝ) :
    (∑ i : Fin M, ∑ j : Fin M, v i * RKHS_kernel data i j t * v j) ≤
    w_max * (1 + (2 * Real.exp (-1 / (4 * t))) / (1 - Real.exp (-1 / (4 * t)))) * (∑ i : Fin M, v i ^ 2) := by
  -- Let's simplify the expression using the provided solution steps.
  have h_simp : ∑ i : Fin M, ∑ j : Fin M, v i * RKHS_kernel data i j t * v j ≤ w_max * (∑ i : Fin M, v i ^ 2) + w_max * (∑ i : Fin M, ∑ j ∈ Finset.erase Finset.univ i, |v i| * |v j| * Real.exp (-(i - j : ℤ) ^ 2 / (4 * t))) := by
    -- Apply the bound $w_RKHS i \leq w_max$ and the uniformity of $ξ$.
    have h_bound : ∀ i j : Fin M, v i * RKHS_kernel data i j t * v j ≤ w_max * |v i| * |v j| * Real.exp (-(i - j : ℤ) ^ 2 / (4 * t)) := by
      -- Apply the bound $w_RKHS i \leq w_max$ to each term in the sum.
      have h_bound : ∀ i j : Fin M, v i * RKHS_kernel data i j t * v j ≤ w_max * |v i| * |v j| * Real.exp (-(i - j : ℤ) ^ 2 / (4 * t)) := by
        intro i j
        have h_w_bound : Real.sqrt (data.w_RKHS i) * Real.sqrt (data.w_RKHS j) ≤ w_max := by
          have h_bound_term : ∀ i, Real.sqrt (data.w_RKHS i) ≤ Real.sqrt w_max := by
            exact fun i => Real.sqrt_le_sqrt <| data.w_RKHS_le_w_max i
          generalize_proofs at *; (
          exact le_trans ( mul_le_mul ( h_bound_term _ ) ( h_bound_term _ ) ( by positivity ) ( by positivity ) ) ( by rw [ Real.mul_self_sqrt ( show 0 ≤ w_max by exact div_nonneg zero_le_two ( Real.exp_nonneg _ ) ) ] ) ;)
        unfold RKHS_kernel;
        simp_all +decide [ IsUniform, mul_assoc, mul_comm, mul_left_comm ];
        refine' le_of_abs_le _;
        rw [ abs_mul, abs_mul, abs_mul, abs_of_nonneg ( Real.exp_pos _ |> le_of_lt ), abs_of_nonneg ( mul_nonneg ( Real.sqrt_nonneg _ ) ( Real.sqrt_nonneg _ ) ) ] ; nlinarith [ show 0 ≤ |v i| * |v j| * Real.exp ( - ( ( i : ℝ ) - j ) ^ 2 / ( t * 4 ) ) by positivity ];
      assumption;
    refine le_trans ( Finset.sum_le_sum fun i _ => Finset.sum_le_sum fun j _ => h_bound i j ) ?_;
    norm_num [ Finset.mul_sum _ _ _, mul_assoc ];
    norm_num [ ← sq, ← Finset.mul_sum _ _ _, ← Finset.sum_mul ];
    linarith;
  -- Notice that $\sum_{i \ne j} |v_i| |v_j| \exp(-(i-j)^2/(4t)) \leq \sum_{i \ne j} \frac{1}{2} (v_i^2 + v_j^2) \exp(-(i-j)^2/(4t))$.
  have h_bound : ∑ i : Fin M, ∑ j ∈ Finset.erase Finset.univ i, |v i| * |v j| * Real.exp (-(i - j : ℤ) ^ 2 / (4 * t)) ≤ ∑ i : Fin M, ∑ j ∈ Finset.erase Finset.univ i, (v i ^ 2 + v j ^ 2) / 2 * Real.exp (-(i - j : ℤ) ^ 2 / (4 * t)) := by
    exact Finset.sum_le_sum fun i hi => Finset.sum_le_sum fun j hj => mul_le_mul_of_nonneg_right ( by linarith [ sq_nonneg ( |v i| - |v j| ), abs_mul_abs_self ( v i ), abs_mul_abs_self ( v j ) ] ) ( Real.exp_nonneg _ );
  -- Notice that $\sum_{j \ne i} \exp(-(i-j)^2/(4t)) \leq 2 \sum_{k=1}^{M-1} \exp(-k^2/(4t))$.
  have h_sum_bound : ∀ i : Fin M, ∑ j ∈ Finset.erase Finset.univ i, Real.exp (-(i - j : ℤ) ^ 2 / (4 * t)) ≤ 2 * ∑ k ∈ Finset.Icc (1 : ℤ) (M - 1), Real.exp (-k ^ 2 / (4 * t)) := by
    -- For each $i$, the sum $\sum_{j \ne i} \exp(-(i-j)^2/(4t))$ can be split into two parts: one for $j < i$ and one for $j > i$.
    intro i
    have h_split : ∑ j ∈ Finset.erase Finset.univ i, Real.exp (-(i - j : ℤ) ^ 2 / (4 * t)) = ∑ j ∈ Finset.range i.val, Real.exp (-(i - j : ℤ) ^ 2 / (4 * t)) + ∑ j ∈ Finset.Ico (i.val + 1) M, Real.exp (-(i - j : ℤ) ^ 2 / (4 * t)) := by
      rw [ ← Finset.sum_union ];
      · refine' Finset.sum_bij ( fun j hj => j ) _ _ _ _ <;> simp +decide [ Finset.mem_union, Finset.mem_range, Finset.mem_Ico ];
        · exact fun a ha => lt_or_gt_of_ne ( by simpa [ Fin.ext_iff ] using ha ) |> Or.imp id fun h => Nat.succ_le_of_lt h;
        · exact fun a₁ ha₁ a₂ ha₂ h => Fin.ext h;
        · rintro b ( hb | hb ) <;> [ exact ⟨ ⟨ b, by linarith [ Fin.is_lt i ] ⟩, ne_of_lt hb, rfl ⟩ ; exact ⟨ ⟨ b, by linarith [ Fin.is_lt i ] ⟩, ne_of_gt ( Nat.lt_of_succ_le hb.1 ), rfl ⟩ ];
      · exact Finset.disjoint_left.mpr fun x hx₁ hx₂ => by linarith [ Finset.mem_range.mp hx₁, Finset.mem_Ico.mp hx₂ ] ;
    -- Notice that $\sum_{j=0}^{i-1} \exp(-(i-j)^2/(4t)) \leq \sum_{k=1}^{i} \exp(-k^2/(4t))$ and $\sum_{j=i+1}^{M-1} \exp(-(i-j)^2/(4t)) \leq \sum_{k=1}^{M-i-1} \exp(-k^2/(4t))$.
    have h_sum_bound_parts : ∑ j ∈ Finset.range i.val, Real.exp (-(i - j : ℤ) ^ 2 / (4 * t)) ≤ ∑ k ∈ Finset.Icc (1 : ℤ) (i.val), Real.exp (-k ^ 2 / (4 * t)) ∧ ∑ j ∈ Finset.Ico (i.val + 1) M, Real.exp (-(i - j : ℤ) ^ 2 / (4 * t)) ≤ ∑ k ∈ Finset.Icc (1 : ℤ) (M - i.val - 1), Real.exp (-k ^ 2 / (4 * t)) := by
      constructor;
      · refine' le_of_eq _;
        refine' Finset.sum_bij ( fun j hj => i - j ) _ _ _ _ <;> norm_num;
        · exact fun a ha => by linarith;
        · exact fun b hb₁ hb₂ => ⟨ Int.toNat ( i - b ), by linarith [ Int.toNat_of_nonneg ( sub_nonneg.2 hb₂ ) ], by linarith [ Int.toNat_of_nonneg ( sub_nonneg.2 hb₂ ) ] ⟩;
      · refine' le_of_eq _;
        refine' Finset.sum_bij ( fun j hj => j - i ) _ _ _ _ <;> norm_num;
        · exact fun a ha₁ ha₂ => ⟨ by linarith, by linarith ⟩;
        · exact fun b hb₁ hb₂ => ⟨ Int.toNat ( b + i ), ⟨ by linarith [ Int.toNat_of_nonneg ( by linarith : 0 ≤ b + i ) ], by linarith [ Int.toNat_of_nonneg ( by linarith : 0 ≤ b + i ) ] ⟩, by rw [ Int.toNat_of_nonneg ( by linarith : 0 ≤ b + i ) ] ; ring ⟩;
        · intros; ring;
    -- Notice that $\sum_{k=1}^{i} \exp(-k^2/(4t)) + \sum_{k=1}^{M-i-1} \exp(-k^2/(4t)) \leq \sum_{k=1}^{M-1} \exp(-k^2/(4t)) + \sum_{k=1}^{M-1} \exp(-k^2/(4t))$.
    have h_sum_bound_combined : ∑ k ∈ Finset.Icc (1 : ℤ) (i.val), Real.exp (-k ^ 2 / (4 * t)) + ∑ k ∈ Finset.Icc (1 : ℤ) (M - i.val - 1), Real.exp (-k ^ 2 / (4 * t)) ≤ ∑ k ∈ Finset.Icc (1 : ℤ) (M - 1), Real.exp (-k ^ 2 / (4 * t)) + ∑ k ∈ Finset.Icc (1 : ℤ) (M - 1), Real.exp (-k ^ 2 / (4 * t)) := by
      exact add_le_add ( Finset.sum_le_sum_of_subset_of_nonneg ( Finset.Icc_subset_Icc_right ( by linarith [ Fin.is_lt i ] ) ) fun _ _ _ => Real.exp_nonneg _ ) ( Finset.sum_le_sum_of_subset_of_nonneg ( Finset.Icc_subset_Icc_right ( by linarith [ Fin.is_lt i ] ) ) fun _ _ _ => Real.exp_nonneg _ );
    linarith;
  -- Substitute the bound from h_sum_bound into h_bound.
  have h_final_bound : ∑ i : Fin M, ∑ j ∈ Finset.erase Finset.univ i, (v i ^ 2 + v j ^ 2) / 2 * Real.exp (-(i - j : ℤ) ^ 2 / (4 * t)) ≤ (∑ i : Fin M, v i ^ 2) * (2 * ∑ k ∈ Finset.Icc (1 : ℤ) (M - 1), Real.exp (-k ^ 2 / (4 * t))) := by
    have h_final_bound : ∑ i : Fin M, ∑ j ∈ Finset.erase Finset.univ i, (v i ^ 2 + v j ^ 2) / 2 * Real.exp (-(i - j : ℤ) ^ 2 / (4 * t)) ≤ ∑ i : Fin M, (v i ^ 2) * (∑ j ∈ Finset.erase Finset.univ i, Real.exp (-(i - j : ℤ) ^ 2 / (4 * t))) := by
      norm_num [ Finset.mul_sum _ _ _, Finset.sum_add_distrib, add_mul, div_mul_eq_mul_div ];
      norm_num [ Finset.sum_add_distrib, Finset.mul_sum _ _ _, Finset.sum_div, Finset.sum_sub_distrib, mul_sub ];
      norm_num [ Finset.sum_add_distrib, ← Finset.mul_sum _ _ _, ← Finset.sum_div ];
      rw [ ← Finset.sum_comm ] ; ring_nf; norm_num;
      norm_num [ ← Finset.mul_sum _ _ _, ← Finset.sum_mul ] ; ring_nf ; norm_num;
      norm_num [ mul_assoc, mul_comm, mul_left_comm ] ; ring_nf ; norm_num;
    exact h_final_bound.trans ( by rw [ Finset.sum_mul _ _ _ ] ; exact Finset.sum_le_sum fun i _ => mul_le_mul_of_nonneg_left ( h_sum_bound i ) ( sq_nonneg _ ) );
  -- Substitute the bound from sum_exp_bound into h_final_bound.
  have h_final_bound' : (∑ i : Fin M, v i ^ 2) * (2 * ∑ k ∈ Finset.Icc (1 : ℤ) (M - 1), Real.exp (-k ^ 2 / (4 * t))) ≤ (∑ i : Fin M, v i ^ 2) * (2 * (Real.exp (-1 / (4 * t))) / (1 - Real.exp (-1 / (4 * t)))) := by
    have := sum_exp_bound t ht M;
    simpa only [ mul_div_assoc ] using mul_le_mul_of_nonneg_left ( mul_le_mul_of_nonneg_left this zero_le_two ) ( Finset.sum_nonneg fun _ _ => sq_nonneg _ );
  nlinarith [ show 0 ≤ w_max by exact div_nonneg zero_le_two <| Real.exp_nonneg _ ]

/-
Prove that 3 * c_star / 4 is greater than w_max.
-/
/-- Bound check -/
lemma c_star_bound_check : 3 * c_star / 4 > w_max := by
  rw [c_star, w_max]
  -- 3 * (11/10) / 4 = 33/40 = 0.825
  -- 2 / e. e < 2.719. 2/2.718 > 0.735
  -- We need to prove 33/40 > 2/e
  -- 33e > 80
  -- e > 80/33 = 2.42...
  -- We know e > 2.7
  rw [ gt_iff_lt, div_lt_iff₀ ( by positivity ) ];
  have := Real.exp_one_gt_d9.le ; norm_num1 at * ; linarith

/-
Prove that for epsilon > w_max, there exists t such that the RKHS norm is bounded by epsilon.
-/
/-- Lemma 2: RKHS Operator Norm Bound for Small t (Corrected) -/
lemma RKHS_norm_small (data : A3_Data) (h_unif : IsUniform data) (ε : ℝ) (hε : ε > w_max) :
    ∃ t > 0, ∀ M : ℕ, ∀ v : Fin M → ℝ,
    (∑ i : Fin M, ∑ j : Fin M, v i * RKHS_kernel data i j t * v j) / (∑ i : Fin M, v i ^ 2) ≤ ε := by
  -- We want to find t such that w_max * (1 + S(t)) <= ε
  -- S(t) = 2 * exp(...) / (1 - exp(...))
  -- Let target = ε / w_max - 1. Since ε > w_max, target > 0.
  -- We need S(t) <= target.
  -- S(t) -> 0 as t -> 0. So such t exists.
  -- Since ε > w_max, we can find t small enough such that the bound from RKHS_sum_bound is less than ε.
  obtain ⟨t, ht_pos, ht_bound⟩ : ∃ t > 0, w_max * (1 + (2 * Real.exp (-1 / (4 * t))) / (1 - Real.exp (-1 / (4 * t)))) ≤ ε := by
    have h_lim : Filter.Tendsto (fun t => w_max * (1 + (2 * Real.exp (-1 / (4 * t))) / (1 - Real.exp (-1 / (4 * t))))) (nhdsWithin 0 (Set.Ioi 0)) (nhds w_max) := by
      -- As $t \to 0^+$, $\exp(-1/(4t)) \to 0$, so we can simplify the expression.
      have h_exp_zero : Filter.Tendsto (fun t => Real.exp (-1 / (4 * t))) (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
        norm_num [ neg_div ];
        exact Filter.Tendsto.atTop_mul_const ( by norm_num ) ( tendsto_inv_nhdsGT_zero );
      convert tendsto_const_nhds.mul ( tendsto_const_nhds.add ( Filter.Tendsto.div ( tendsto_const_nhds.mul h_exp_zero ) ( tendsto_const_nhds.sub h_exp_zero ) _ ) ) using 2 <;> norm_num;
    have := h_lim.eventually ( ge_mem_nhds hε ) ; have := this.and self_mem_nhdsWithin; obtain ⟨ t, ht₁, ht₂ ⟩ := this.exists; exact ⟨ t, ht₂, ht₁ ⟩ ;
  refine' ⟨ t, ht_pos, fun M v ↦ _ ⟩;
  refine' le_trans ( div_le_of_le_mul₀ _ _ _ ) ht_bound;
  · exact Finset.sum_nonneg fun _ _ => sq_nonneg _;
  · exact mul_nonneg ( by exact div_nonneg zero_le_two ( Real.exp_nonneg _ ) ) ( add_nonneg zero_le_one ( div_nonneg ( mul_nonneg zero_le_two ( Real.exp_nonneg _ ) ) ( sub_nonneg.2 ( Real.exp_le_one_iff.2 ( by ring_nf; norm_num; positivity ) ) ) ) );
  · convert RKHS_sum_bound data h_unif t ht_pos M v using 1

/-
Prove that for sufficiently large M and small t, the difference between the Toeplitz form of a_star and the RKHS kernel form is bounded below by c_star/4.
-/
/-- Main Theorem: A3 Bridge Closure -/
theorem A3_bridge_closure (data : A3_Data) (props : A3_Props data) (h_unif : IsUniform data) :
    ∃ M₀ : ℕ, ∃ t > 0, ∀ M ≥ M₀,
    ∀ (v : Fin M → ℝ), v ≠ 0 →
    (∑ i : Fin M, ∑ j : Fin M, v i * v j * (data.ToeplitzEntry_a_star M i j - RKHS_kernel data i j t)) /
    (∑ i : Fin M, v i ^ 2) ≥ c_star / 4 := by
      -- Use `RKHS_norm_small` to find `t` such that the RKHS part is bounded by `3 * c_star / 4`.
      obtain ⟨t, ht_pos, ht_bound⟩ : ∃ t > 0, ∀ M : ℕ, ∀ v : Fin M → ℝ, (∑ i : Fin M, (∑ j : Fin M, v i * RKHS_kernel data i j t * v j)) / (∑ i : Fin M, v i ^ 2) ≤ 3 * c_star / 4 := by
        exact RKHS_norm_small data h_unif ( 3 * c_star / 4 ) ( by linarith [ c_star_bound_check ] );
      refine' ⟨ 1, t, ht_pos, fun M hM v hv ↦ _ ⟩;
      have := toeplitz_rayleigh_ge_c_star data props M hM v hv;
      simp_all +decide [ mul_sub, mul_assoc, mul_comm, mul_left_comm, Finset.sum_sub_distrib, div_eq_mul_inv ];
      norm_num at * ; linarith [ ht_bound M v ]