/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 2b3cd17f-bac2-4b35-901f-0adb5ac43b85
-/

/-
This module proves that the Rayleigh quotient of the compressed prime operator T_P_comp is bounded by ρ(1) < 1/25.
It defines the quadratic form and Rayleigh quotient, and proves key properties for rank-one matrices and their sums.
The main result is `rkhs_cap_rayleigh`, which establishes the bound using the sum of weights.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators
open Finset


def normSq {M : ℕ} (v : Fin M → ℝ) : ℝ :=
  ∑ i, (v i) ^ (2 : ℕ)

def quadForm {M : ℕ} (A : Matrix (Fin M) (Fin M) ℝ) (v : Fin M → ℝ) : ℝ :=
  ∑ i, ∑ j, v i * A i j * v j

def rayleighQ {M : ℕ} (A : Matrix (Fin M) (Fin M) ℝ) (v : Fin M → ℝ) : ℝ :=
  quadForm A v / normSq v

-- Rank-one matrix from vector u with weight α
def rankOne {M : ℕ} (α : ℝ) (u : Fin M → ℝ) : Matrix (Fin M) (Fin M) ℝ :=
  fun i j => α * u i * u j

def rho_one : ℝ := (1 : ℝ) / 25

/-
T_P_comp as rank-one sum
-/
def T_P_comp_abstract {NodesK : Type*} [Fintype NodesK]
    (weight : NodesK → ℝ)
    (basis_vec : NodesK → (M : ℕ) → Fin M → ℝ)
    (M : ℕ) : Matrix (Fin M) (Fin M) ℝ :=
  fun i j => ∑ n : NodesK, weight n * basis_vec n M i * basis_vec n M j

/-
Quadratic form of rank-one matrix
-/
lemma quadForm_rankOne {M : ℕ} (α : ℝ) (u v : Fin M → ℝ) :
    quadForm (rankOne α u) v = α * (∑ i, u i * v i)^2 := by
  unfold quadForm; ring;
  simp +decide [ pow_two, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Finset.sum_mul, rankOne ]

/-
Rank-one quadratic form is nonnegative when α ≥ 0
-/
lemma quadForm_rankOne_nonneg {M : ℕ} (α : ℝ) (u v : Fin M → ℝ) (hα : 0 ≤ α) :
    0 ≤ quadForm (rankOne α u) v := by
  exact quadForm_rankOne α u v ▸ mul_nonneg hα ( sq_nonneg _ )

/-
Quadratic form of sum = sum of quadratic forms
-/
lemma quadForm_sum {M : ℕ} {ι : Type*} [Fintype ι]
    (A : ι → Matrix (Fin M) (Fin M) ℝ) (v : Fin M → ℝ) :
    quadForm (∑ i, A i) v = ∑ i, quadForm (A i) v := by
  -- By definition of quadratic form, we can expand both sides.
  have h_expand : ∑ x : Fin M × Fin M, v x.1 * (∑ i, A i x.1 x.2) * v x.2 = ∑ x : Fin M × Fin M, (∑ i, v x.1 * (A i x.1 x.2) * v x.2) := by
    simp +decide only [Finset.mul_sum _ _ _, sum_mul, mul_assoc];
  unfold quadForm;
  convert h_expand using 1;
  · erw [ Finset.sum_product ];
    simp +decide [ Matrix.sum_apply ];
  · erw [ Finset.sum_product ];
    exact Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ => Finset.sum_comm )

/-
Rayleigh quotient bounded by sum of weights
-/
lemma rayleighQ_rankOne_sum_le
    {M : ℕ} {ι : Type*} [Fintype ι]
    (α : ι → ℝ) (u : ι → Fin M → ℝ) (v : Fin M → ℝ)
    (hα : ∀ i, 0 ≤ α i)
    (hu : ∀ i, ∑ j : Fin M, (u i j)^2 = 1)
    (hv : v ≠ 0) :
    rayleighQ (fun i j => ∑ n, α n * u n i * u n j) v ≤ ∑ n, α n := by
  -- By the properties of the quadratic form, we can expand $\text{quadForm}(\sum_{n} \alpha_n u_n u_n^T, v)$ as $\sum_{n} \alpha_n (\sum_{i} u_n[i] v[i])^2$.
  have h_quad_form : quadForm (fun i j => ∑ n, α n * u n i * u n j) v = ∑ n, α n * (∑ i, (u n i) * (v i)) ^ 2 := by
    simp +decide only [quadForm, mul_comm];
    simp +decide only [mul_left_comm, mul_comm, Finset.mul_sum _ _ _, pow_two];
    exact Eq.symm ( Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ => Finset.sum_comm ) );
  -- Since $\|u_n\|^2 = 1$ for all $n$, we have $(\sum_{i} u_n[i] v[i])^2 \leq \|v\|^2$.
  have h_cauchy_schwarz : ∀ n, (∑ i, (u n i) * (v i)) ^ 2 ≤ (∑ i, (v i) ^ 2) := by
    intro n
    have h_cauchy_schwarz : (∑ i, (u n i) * (v i)) ^ 2 ≤ (∑ i, (u n i) ^ 2) * (∑ i, (v i) ^ 2) := by
      exact?;
    aesop;
  -- Therefore, $\text{quadForm}(\sum_{n} \alpha_n u_n u_n^T, v) \leq \sum_{n} \alpha_n \|v\|^2$.
  have h_quad_form_le : quadForm (fun i j => ∑ n, α n * u n i * u n j) v ≤ (∑ n, α n) * (∑ i, (v i) ^ 2) := by
    simpa only [ h_quad_form, Finset.sum_mul _ _ _ ] using Finset.sum_le_sum fun n _ => mul_le_mul_of_nonneg_left ( h_cauchy_schwarz n ) ( hα n );
  exact div_le_of_le_mul₀ ( Finset.sum_nonneg fun _ _ => sq_nonneg _ ) ( Finset.sum_nonneg fun _ _ => hα _ ) h_quad_form_le

/-
Main theorem: Rayleigh quotient of T_P_comp is bounded by rho_one
-/
theorem rkhs_cap_rayleigh
    (NodesK : Type*) [Fintype NodesK]
    (weight : NodesK → ℝ)
    (basis_vec : NodesK → (M : ℕ) → Fin M → ℝ)
    (h_weight_nonneg : ∀ n, 0 ≤ weight n)
    (h_basis_norm : ∀ n M, ∑ i : Fin M, (basis_vec n M i)^2 = 1)
    (h_weight_sum : ∑ n : NodesK, weight n ≤ rho_one)
    : ∀ M : ℕ, ∀ v : Fin M → ℝ, v ≠ 0 →
        rayleighQ (T_P_comp_abstract weight basis_vec M) v ≤ rho_one := by
  intros M v hv_nonzero
  apply le_trans (rayleighQ_rankOne_sum_le (weight) (basis_vec · M) v h_weight_nonneg (fun n => h_basis_norm n M) hv_nonzero) h_weight_sum