import Q3.ForMathlib.GaussianMajorant
import Q3.ForMathlib.GaussianTailKernel
import Q3.ForMathlib.ArchHeatMajorant
import Q3.ForMathlib.PrimeHeatDigammaShift
import Q3.ForMathlib.PrimeHeatArchPiecewiseKernel
